"""
Sidecar Generator - The Crown Engine
Generates metadata.json and .nfo files for physical organization.

Standard:
metadata.json v1.0:
{
  "canonical_id": "uuid",
  "title": "Game Title",
  "overridden_fields": { ... },
  "files": [ ... ],
  "curated_at": "ISO-8601"
}
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class SidecarGenerator:
    @staticmethod
    def generate_metadata_json(
        canonical_data: Dict[str, Any], 
        files: List[Dict[str, str]], 
        target_path: Path
    ) -> Path:
        """
        Write metadata.json to target_path with checksum verification.
        """
        import hashlib
        
        payload = {
            "canonical_id": canonical_data.get('id'),
            "title": canonical_data.get('display_title'),
            "overridden_fields": canonical_data.get('overridden_fields', {}),
            "files": files, # List of {rel_path, role}
            "curated_at": datetime.now().isoformat(),
            "generator": "Galroon v0.2.0 - The Crown Engine",
            "metadata_snapshot": canonical_data.get('metadata_snapshot', {})
        }

        # Generate checksum (first 16 chars of SHA256)
        checksum = hashlib.sha256(
            json.dumps(payload, sort_keys=True).encode()
        ).hexdigest()[:16]
        payload['_checksum'] = checksum

        output_file = target_path / "metadata.json"
        
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
            return output_file
        except Exception as e:
            logger.error(f"Failed to generate metadata.json: {e}")
            raise

    @staticmethod
    def generate_nfo(canonical_data: Dict[str, Any], target_path: Path) -> Path:
        """
        Write basic .nfo file (human readable).
        """
        game_title = canonical_data.get('display_title', 'Unknown Title')
        dev = canonical_data.get('metadata_snapshot', {}).get('developer', 'Unknown Developer')
        desc = canonical_data.get('metadata_snapshot', {}).get('description', '')
        
        content = f"""
================================================================================
{game_title}
================================================================================

Developer: {dev}
Curated:   {datetime.now().strftime('%Y-%m-%d')}

{desc}

--------------------------------------------------------------------------------
Generated by Galroon
"""
        output_file = target_path / "game.nfo"
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content.strip())
            return output_file
        except Exception as e:
             logger.error(f"Failed to generate nfo: {e}")
             raise
