"""
Match Cluster Data Models for Galroon v0.2.0

Sprint 5: MatchCluster Mechanism

Architecture Overview:
- MatchCluster: Represents a suggested grouping of LocalInstances
- MatchClusterMember: Links LocalInstances to a MatchCluster

This implements the decision engine for accepting/rejecting cluster suggestions.
"""

import json
from typing import Dict, Any, List, Optional, Literal
from dataclasses import dataclass, asdict


@dataclass
class MatchCluster:
    """
    Suggested cluster of LocalInstances that may represent the same game.

    This is the "decision unit" - users accept or reject clusters to create
    Canonical entities. Clusters are typically generated by AI matching or
    heuristic similarity algorithms.

    States:
    - suggested: New cluster, awaiting user decision
    - accepted: Cluster was accepted, converted to CanonicalGame
    - rejected: Cluster was rejected, members remain as orphans

    Attributes:
        id: Unique cluster ID (UUID)
        status: Current state of the cluster
        confidence_score: AI confidence (0.0 to 1.0)
        suggested_title: Title suggested for this cluster
        suggested_canonical_id: Optional: Existing CanonicalGame ID if this cluster
                               suggests an attachment to an existing canonical
        metadata_snapshot: JSON blob of clustering metadata (why these match?)
        created_at: Creation timestamp
        updated_at: Last update timestamp
    """

    id: str
    status: Literal['suggested', 'accepted', 'rejected']
    confidence_score: float
    suggested_title: str
    suggested_canonical_id: Optional[str] = None
    metadata_snapshot: Optional[Dict[str, Any]] = None
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MatchCluster':
        """Create instance from dictionary."""
        if isinstance(data.get('metadata_snapshot'), str):
            data['metadata_snapshot'] = json.loads(data['metadata_snapshot'])
        return cls(**data)


@dataclass
class MatchClusterMember:
    """
    Member of a MatchCluster - links LocalInstance to Cluster.

    A LocalInstance can only belong to one active (suggested) cluster at a time.
    Once a cluster is accepted/rejected, these links remain for audit trail.

    Attributes:
        id: Unique member ID
        cluster_id: Foreign key to MatchCluster.id
        instance_path: Path to LocalInstance (FK reference to games.folder_path)
        match_score: Individual match score for this instance in this cluster
        is_primary: Whether this is the primary instance (best representative)
        metadata_snapshot: JSON blob of matching metadata (why this instance fits?)
        created_at: Creation timestamp
    """

    id: str
    cluster_id: str
    instance_path: str
    match_score: float
    is_primary: bool
    metadata_snapshot: Optional[Dict[str, Any]] = None
    created_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MatchClusterMember':
        """Create instance from dictionary."""
        if isinstance(data.get('metadata_snapshot'), str):
            data['metadata_snapshot'] = json.loads(data['metadata_snapshot'])
        return cls(**data)


# Table definitions for Database class
MATCH_CLUSTERS_TABLE_SQL = """
    CREATE TABLE IF NOT EXISTS match_clusters (
        id TEXT PRIMARY KEY,
        status TEXT NOT NULL CHECK(status IN ('suggested', 'accepted', 'rejected')),
        confidence_score REAL NOT NULL CHECK(confidence_score >= 0.0 AND confidence_score <= 1.0),
        suggested_title TEXT NOT NULL,
        suggested_canonical_id TEXT,  -- Optional: attach to existing CanonicalGame
        metadata_snapshot TEXT,  -- JSON blob
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (suggested_canonical_id) REFERENCES canonical_games(id) ON DELETE SET NULL
    )
"""

MATCH_CLUSTER_MEMBERS_TABLE_SQL = """
    CREATE TABLE IF NOT EXISTS match_cluster_members (
        id TEXT PRIMARY KEY,
        cluster_id TEXT NOT NULL,
        instance_path TEXT NOT NULL,  -- FK reference to games.folder_path
        match_score REAL NOT NULL CHECK(match_score >= 0.0 AND match_score <= 1.0),
        is_primary BOOLEAN NOT NULL DEFAULT 0,
        metadata_snapshot TEXT,  -- JSON blob
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (cluster_id) REFERENCES match_clusters(id) ON DELETE CASCADE,
        UNIQUE(cluster_id, instance_path)
    )
"""

# Indexes for match_cluster tables
MATCH_CLUSTER_INDEXES_SQL = [
    "CREATE INDEX IF NOT EXISTS idx_match_cluster_status ON match_clusters(status)",
    "CREATE INDEX IF NOT EXISTS idx_match_cluster_confidence ON match_clusters(confidence_score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_match_cluster_canonical_id ON match_clusters(suggested_canonical_id)",
    "CREATE INDEX IF NOT EXISTS idx_match_member_cluster_id ON match_cluster_members(cluster_id)",
    "CREATE INDEX IF NOT EXISTS idx_match_member_instance_path ON match_cluster_members(instance_path)",
    "CREATE INDEX IF NOT EXISTS idx_match_member_primary ON match_cluster_members(is_primary)",
]

__all__ = [
    "MatchCluster",
    "MatchClusterMember",
    "MATCH_CLUSTERS_TABLE_SQL",
    "MATCH_CLUSTER_MEMBERS_TABLE_SQL",
    "MATCH_CLUSTER_INDEXES_SQL",
]
