; Generated by scripts/generate_installer_hooks.py. Do not edit.
; Cleanup happens only after normal app-running checks and file operations.
; Keep every shipped entrypoint/chunk, including dynamic imports.
!macro NSIS_HOOK_POSTINSTALL
  Push $R0
  Push $R1
  FindFirst $R0 $R1 "$INSTDIR\web\assets\index-????????.js"
  IfErrors galroon_cleanup_js_end
galroon_cleanup_js_loop:
  StrCmp $R1 "" galroon_cleanup_js_close
  StrCmp $R1 "index-C7I_Jw0y.js" galroon_cleanup_js_next
  StrCmp $R1 "index-D1s1McWQ.js" galroon_cleanup_js_next
  StrCmp $R1 "index-DVAWzEqV.css" galroon_cleanup_js_next
  Delete "$INSTDIR\web\assets\$R1"
galroon_cleanup_js_next:
  FindNext $R0 $R1
  Goto galroon_cleanup_js_loop
galroon_cleanup_js_close:
  FindClose $R0
galroon_cleanup_js_end:
  FindFirst $R0 $R1 "$INSTDIR\web\assets\index-????????.css"
  IfErrors galroon_cleanup_css_end
galroon_cleanup_css_loop:
  StrCmp $R1 "" galroon_cleanup_css_close
  StrCmp $R1 "index-C7I_Jw0y.js" galroon_cleanup_css_next
  StrCmp $R1 "index-D1s1McWQ.js" galroon_cleanup_css_next
  StrCmp $R1 "index-DVAWzEqV.css" galroon_cleanup_css_next
  Delete "$INSTDIR\web\assets\$R1"
galroon_cleanup_css_next:
  FindNext $R0 $R1
  Goto galroon_cleanup_css_loop
galroon_cleanup_css_close:
  FindClose $R0
galroon_cleanup_css_end:
  Pop $R1
  Pop $R0
!macroend

!macro NSIS_HOOK_POSTUNINSTALL
  Delete "$INSTDIR\web\assets\index-????????.js"
  Delete "$INSTDIR\web\assets\index-????????.css"
  RMDir "$INSTDIR\web\assets"
  RMDir "$INSTDIR\web"
  RMDir "$INSTDIR"
!macroend
