//! Same-engine generated-only SQL stage profiling; never opens the source database for writes.
use std::{fs,path::PathBuf,time::Instant};
use rusqlite::{Connection,OpenFlags,params};
use serde_json::json;
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let source=PathBuf::from(&args[1]).canonicalize().unwrap();let out=PathBuf::from(&args[2]);assert!(!out.exists());fs::create_dir_all(&out).unwrap();let auto:i64=args[3].parse().unwrap();assert!([0,1000].contains(&auto));let mut origin=Connection::open_with_flags(&source,OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();origin.backup(rusqlite::MAIN_DB,out.join("profile.sqlite"),None).unwrap();drop(origin);
 let c=Connection::open(out.join("profile.sqlite")).unwrap();c.execute_batch("PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;PRAGMA synchronous=FULL;").unwrap();c.pragma_update(None,"wal_autocheckpoint",auto).unwrap();let synchronous:i64=c.pragma_query_value(None,"synchronous",|r|r.get(0)).unwrap();assert_eq!(synchronous,2);
 let works:i64=c.query_row("SELECT count(*) FROM works",[],|r|r.get(0)).unwrap();assert_eq!(works,100000);let edition:String=c.query_row("SELECT id FROM releases LIMIT 1",[],|r|r.get(0)).unwrap();let mut stages=vec![];
 let start=Instant::now();c.execute_batch("BEGIN").unwrap();{let mut q=c.prepare("SELECT work_id FROM work_releases WHERE release_id=?1").unwrap();let ids=q.query_map([&edition],|r|r.get::<_,String>(0)).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();assert_eq!(ids.len(),100000);}stages.push(json!({"stage":"begin_and_members","ms":start.elapsed().as_secs_f64()*1000.0}));
 for(name,sql)in [("edition","UPDATE releases SET notes='Profile note',revision=revision+1 WHERE id=?1"),("works","UPDATE works SET revision=revision+1 WHERE id IN (SELECT work_id FROM work_releases WHERE release_id=?1)"),("resources","UPDATE resources SET release_label='Profile edition',revision=revision+1 WHERE EXISTS(SELECT 1 FROM resource_bindings b WHERE b.resource_id=resources.id AND b.work_id=resources.work_id AND b.release_id=?1)")]{let start=Instant::now();let rows=c.execute(sql,params![edition]).unwrap();let stage=json!({"stage":name,"ms":start.elapsed().as_secs_f64()*1000.0,"rows":rows});println!("{stage}");stages.push(stage);}
 let start=Instant::now();c.execute_batch("COMMIT").unwrap();let commit=json!({"stage":"commit","ms":start.elapsed().as_secs_f64()*1000.0});println!("{commit}");stages.push(commit);
 let wal_bytes=fs::metadata(out.join("profile.sqlite-wal")).unwrap().len();let start=Instant::now();let checkpoint:(i64,i64,i64)=c.query_row("PRAGMA wal_checkpoint(PASSIVE)",[],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).unwrap();stages.push(json!({"stage":"explicit_checkpoint","ms":start.elapsed().as_secs_f64()*1000.0,"result":checkpoint}));let report=json!({"finished":true,"sqlite_version":rusqlite::version(),"works":works,"automatic_checkpoint_pages":auto,"synchronous":synchronous,"source_read_only":source,"wal_bytes":wal_bytes,"stages":stages});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
