use galroon_core::local_core::{self,Session};
use serde_json::{json,Value};
use std::{fs,path::PathBuf,time::Duration};
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::builder().timeout(Duration::from_secs(20)).build().unwrap();let url=format!("{}/api{path}",s.url);let req=if let Some(body)=body{client.post(url).json(&body)}else{client.get(url)};let response=req.bearer_auth(&s.token).send().await.unwrap();assert!(response.status().is_success(),"API failed at {path}: {}",response.status());response.json().await.unwrap()}
#[tokio::main]async fn main(){
 let args:Vec<_>=std::env::args().collect();let output=PathBuf::from(args.get(1).expect("Fresh fixture output"));let exe=PathBuf::from(args.get(2).expect("Core executable")).canonicalize().unwrap();assert!(!output.exists());fs::create_dir_all(&output).unwrap();let output=output.canonicalize().unwrap();let state=output.join("state");fs::create_dir(&state).unwrap();
 let raw=json!({"fetched_at":galroon_core::db::now(),"vn":{"id":"v1","title":"Fixture","developers":[{"id":"p1","name":"Studio"}],"staff":[{"id":"s1","name":"Writer","role":"scenario"}],"va":[{"staff":{"id":"s1","name":"Writer"},"character":{"id":"c1"}}],"relations":[]},"characters":[{"id":"c1","name":"Character","vns":[{"id":"v1","spoiler":0}]}],"more":false});
 {let db=galroon_core::db::open(&state.join("library.sqlite")).unwrap();let c=db.lock().unwrap();c.execute("INSERT INTO works(id,title,original_title,vndb_id) VALUES('w','Fixture','Fixture','v1')",[]).unwrap();c.execute("INSERT INTO settings(key,value) VALUES('exploration.v4.work.v1.1',?1)",[raw.to_string()]).unwrap();for(kind,id)in [("person","s1"),("character","c1"),("company","p1")]{let profile=json!({"fetched_at":galroon_core::db::now(),(kind):{"id":id,"name":"Fixture","vns":[{"id":"v1"}]},"works":[raw["vn"].clone()],"page":1,"more":false});c.execute("INSERT INTO settings(key,value) VALUES(?1,?2)",rusqlite::params![format!("exploration.v3.{kind}.{id}.1"),profile.to_string()]).unwrap();}}
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let restart_state=state.clone();let restart_exe=exe.clone();let expected=raw.clone();
 let outcome=tokio::spawn(async move{
 let tag=api(&first,"/custom-tags",Some(json!({"name":"Fixture creators"}))).await;let id=tag["id"].as_str().unwrap();api(&first,"/entity-tags/s1",Some(json!({"tag_id":id,"revision":1,"assigned":true,"request_id":"tag"}))).await;
 let definition=json!({"schema_version":1,"scope":"collection","sort":"title","rule":{"kind":"field","predicate":{"field":"related_personal_tags","mode":"any","values":[id]}}});assert_eq!(api(&first,"/smart-lists/preview",Some(definition.clone())).await["total"],1);
 let hidden=json!({"people":["s1"],"characters":["c1"],"companies":["p1"],"works":[]});let input=json!({"revision":0,"request_id":"hide","hidden":hidden});let saved=api(&first,"/vns/v1/relationship-decisions",Some(input.clone())).await;assert_eq!(saved["revision"],1);
 for path in ["/works/w/exploration","/vns/v1/exploration"]{let value=api(&first,path,None).await;for field in ["staff","va","developers"]{assert!(value["vn"][field].as_array().unwrap().is_empty());}assert!(value["characters"].as_array().unwrap().is_empty());}
 for path in ["/people/s1","/characters/c1","/companies/p1"]{let value=api(&first,path,None).await;assert!(value["works"].as_array().unwrap().is_empty());}
 assert_eq!(api(&first,"/smart-lists/preview",Some(definition.clone())).await["total"],0);assert!(api(&first,"/works/w/related-tags",None).await["tags"].as_array().unwrap().is_empty());
 local_core::request(&restart_state,&restart_exe,"stop").await.unwrap();let second=local_core::connect_or_start(restart_state.clone(),restart_exe).await.unwrap();assert_eq!(api(&second,"/vns/v1/relationship-decisions",Some(input)).await,saved);assert_eq!(api(&second,"/vns/v1/relationship-decisions",None).await["hidden"],hidden);
 api(&second,"/vns/v1/relationship-decisions",Some(json!({"revision":1,"request_id":"reset","hidden":{"people":[],"characters":[],"companies":[],"works":[]}}))).await;
 assert_eq!(api(&second,"/works/w/exploration",None).await,expected);for path in ["/people/s1","/characters/c1","/companies/p1"]{assert_eq!(api(&second,path,None).await["works"].as_array().unwrap().len(),1);}
 assert_eq!(api(&second,"/smart-lists/preview",Some(definition)).await["total"],1);let history=api(&second,"/vns/v1/relationship-history",None).await;assert_eq!(history["items"].as_array().unwrap().len(),2);assert_eq!(history["items"][0]["before"],hidden);
 let c=rusqlite::Connection::open_with_flags(restart_state.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();let cache:String=c.query_row("SELECT value FROM settings WHERE key='exploration.v4.work.v1.1'",[],|r|r.get(0)).unwrap();assert_eq!(serde_json::from_str::<Value>(&cache).unwrap(),expected);
 json!({"separate_core":true,"forward_and_reverse_hide_restore":true,"restart_receipt":true,"raw_cache_unchanged":true,"history_records":2,"smart_tag_counts":[1,0,1],"source_files":0,"schema":galroon_core::db::SCHEMA_VERSION})
 }).await;
 let stopped=local_core::request(&state,&exe,"stop").await;let report=outcome.expect("Validation failed; stop attempted");stopped.unwrap();fs::write(output.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
