//! Reads only generated archives; publication targets are under the same fresh fixture root.
use galroon_core::{acquire,db,scan,plans};use serde_json::{json,Value};use std::{fs,path::PathBuf};
fn main(){let out=PathBuf::from(std::env::args().nth(1).expect("Generated corpus root")).canonicalize().unwrap();assert!(out.join("originals.json").is_file());assert!(!out.join("state").exists());let source=out.join("source");let destination=out.join("destination");fs::create_dir(&destination).unwrap();let originals:Value=serde_json::from_slice(&fs::read(out.join("originals.json")).unwrap()).unwrap();let d=db::open(&out.join("state/library.sqlite")).unwrap();d.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES('r',?1,'Generated archive corpus')",[source.to_str().unwrap()]).unwrap();let scanjob=scan::create(&d,scan::ScanSpec{root_id:"r".into(),scope:"".into(),exclude:vec![]}).unwrap();scan::run(d.clone(),scanjob);
 let mut results=vec![];for name in ["case-collision","reserved","traversal","file-directory","symlink","corrupt","unicode","iso"]{
  let rid:String=d.lock().unwrap().query_row("SELECT id FROM resources WHERE title=?1",[name],|r|r.get(0)).unwrap();let before=acquire::preview(&d,&rid).unwrap();if name=="iso"{assert_eq!(before["files"].as_array().unwrap().len(),2);}
  let job=acquire::create(&d,&rid,destination.to_str().unwrap(),true).unwrap();acquire::run(d.clone(),job.clone(),None);let(state,message,spec):(String,String,String)=d.lock().unwrap().query_row("SELECT state,message,spec FROM jobs WHERE id=?1",[&job],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).unwrap();let spec:acquire::Spec=serde_json::from_str(&spec).unwrap();let final_folder=PathBuf::from(&spec.final_folder);
  if matches!(name,"unicode"|"iso"){
   assert_eq!(state,"completed","{name}: {message}");let dir=final_folder.join(if name=="iso"{"disc.iso-extracted"}else{"sample.zip-extracted"});let expected=if name=="iso"{b"Generated ISO content\n".as_slice()}else{b"generated Unicode text".as_slice()};assert_eq!(fs::read(dir.join("日本語/説明.txt")).unwrap(),expected);assert_eq!(fs::metadata(dir.join("empty.txt")).unwrap().len(),0);if name=="iso"{assert_eq!(fs::read(final_folder.join("disc.cue")).unwrap(),fs::read(source.join("iso/disc.cue")).unwrap());}
  }else{assert_eq!(state,"failed","{name}: {message}");assert!(!final_folder.exists());if name!="corrupt"{let stage=destination.join(format!(".galroon-{job}"));assert!(fs::read_dir(stage).unwrap().all(|e|!e.unwrap().file_name().to_string_lossy().starts_with("extract-")),"Unsafe manifest reached extraction: {name}");}if name=="symlink"{assert!(message.contains("links"));}}
  results.push(json!({"case":name,"state":state,"message":message,"published":final_folder.exists()}));
 }
 assert!(!destination.join("escape.txt").exists());for(path,hash)in originals.as_object().unwrap(){assert_eq!(&plans::hash(&source.join(path)).unwrap().1,hash.as_str().unwrap());}
 let report=json!({"cases":results,"source_files_unchanged":originals.as_object().unwrap().len(),"iso_joliet_unicode_and_empty_file":true,"iso_companion_scanned_and_copied":true,"failed_archives_not_published":true,"schema":db::SCHEMA_VERSION});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");}
