//! Verify generated tag membership, receipts and undo through installed Core backup/restore.
use galroon_core::{backup,local_core::{self,Session},plans};
use serde_json::{Value,json};
use std::{path::{Path,PathBuf},fs,collections::BTreeMap,time::Duration};
fn snapshot(path:&Path)->BTreeMap<String,Vec<String>>{
 let c=rusqlite::Connection::open_with_flags(path,rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();
 assert_eq!(c.query_row("PRAGMA integrity_check",[],|r|r.get::<_,String>(0)).unwrap(),"ok");assert_eq!(c.query_row("SELECT count(*) FROM pragma_foreign_key_check",[],|r|r.get::<_,i64>(0)).unwrap(),0);
 let mut out=BTreeMap::new();for table in ["works","releases","work_releases","work_preferences","resources","resource_bindings","jobs","custom_tags","custom_tag_works","tag_requests","tag_undo"]{let mut s=c.prepare(&format!("SELECT * FROM {table}")).unwrap();let count=s.column_count();let mut rows=s.query_map([],|r|Ok((0..count).map(|i|format!("{:?}",r.get_ref(i).unwrap())).collect::<Vec<_>>().join("\n"))).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();rows.sort();out.insert(table.into(),rows);}out
}
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::builder().no_proxy().timeout(Duration::from_secs(30)).build().unwrap();let url=format!("{}/api{path}",s.url);let r=if let Some(body)=body{client.post(url).json(&body)}else{client.get(url)}.bearer_auth(&s.token).send().await.unwrap();assert!(r.status().is_success(),"API {path}: {}",r.status());r.json().await.unwrap()}
async fn stop(state:&Path,exe:&Path){local_core::request(state,exe,"stop").await.unwrap();let f=fs::OpenOptions::new().read(true).write(true).open(state.join("core.lock")).unwrap();let end=tokio::time::Instant::now()+Duration::from_secs(15);while fs2::FileExt::try_lock_exclusive(&f).is_err(){assert!(tokio::time::Instant::now()<end);tokio::time::sleep(Duration::from_millis(50)).await;}}
#[tokio::main]async fn main(){let args=std::env::args().collect::<Vec<_>>();let state=PathBuf::from(&args[1]).canonicalize().unwrap();let exe=PathBuf::from(&args[2]).canonicalize().unwrap();let out=PathBuf::from(&args[3]);assert!(!out.exists());fs::create_dir_all(&out).unwrap();let out=out.canonicalize().unwrap();let restored=out.join("restored");let backups=out.join("backups");fs::create_dir(&backups).unwrap();
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let original_pid=first.pid;
 let before=snapshot(&state.join("library.sqlite"));assert_eq!(before["works"].len(),125);
 let tags=api(&first,"/works/collection-000000/assets",None).await;
 let exported=api(&first,"/backups",Some(json!({"destination":backups}))).await;let folder=PathBuf::from(exported["path"].as_str().unwrap());let manifest=backup::inspect(&folder).unwrap();assert_eq!(snapshot(&folder.join("collection.sqlite")),before);
 let source_hashes=[("present.dat",b"abc".as_slice()),("unknown.dat",b"unknown".as_slice()),("missing.dat",b"no".as_slice())].into_iter().map(|(name,expected)|{let p=state.join("generated-source").join(name);assert_eq!(fs::read(&p).unwrap(),expected);(name.to_owned(),plans::hash(&p).unwrap().1)}).collect::<BTreeMap<_,_>>();
 stop(&state,&exe).await;backup::restore_new(&folder,&restored,Some(&manifest.sha256)).unwrap();assert_eq!(snapshot(&restored.join("library.sqlite")),before);
 let second=local_core::connect_or_start(restored.clone(),exe.clone()).await.unwrap();assert_ne!(original_pid,second.pid);assert_eq!(first.library_id,second.library_id);let restored_tags=api(&second,"/works/collection-000000/assets",None).await;assert!(restored_tags["revision"].as_i64().unwrap()>=tags["revision"].as_i64().unwrap());let normalize=|mut value:Value|{value.as_object_mut().unwrap().remove("revision");value};assert_eq!(normalize(restored_tags),normalize(tags));
 let restored_pid=second.pid;stop(&restored,&exe).await;
 let c=rusqlite::Connection::open_with_flags(restored.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM source_watch WHERE enabled=1",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(c.query_row("SELECT count(*) FROM jobs WHERE state IN ('queued','running','pausing','cancelling')",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(c.query_row("SELECT count(*) FROM sessions",[],|r|r.get::<_,i64>(0)).unwrap(),0);
 let report=json!({"passed":true,"installed_core":true,"standalone_debug":false,"native_ui_restore":false,"generated_works":125,"exact_tables":before.keys().collect::<Vec<_>>(),"backup_sha256":manifest.sha256,"http_export":true,"isolated_restore":true,"restored_core_started":true,"original_pid":original_pid,"restored_pid":restored_pid,"core_sha256":plans::hash(&exe).unwrap().1,"source_hashes":source_hashes,"watchers_disabled":true,"both_cores_identity_stopped":true});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
