//! Windows native notification and independent Core restart acceptance; generated files only.
use galroon_core::{local_core::{self,Session},db};
use serde_json::{Value,json};
use std::{fs,path::PathBuf,time::Duration};
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::new();let r=if let Some(v)=body{client.post(format!("{}/api{path}",s.url)).json(&v)}else{client.get(format!("{}/api{path}",s.url))};let r=r.bearer_auth(&s.token).send().await.unwrap();assert!(r.status().is_success(),"{path}: {}",r.status());r.json().await.unwrap()}
async fn wait_watch(s:&Session,rid:&str,key:&str,value:Value){let deadline=tokio::time::Instant::now()+Duration::from_secs(30);loop{let w=api(s,&format!("/roots/{rid}/watch"),None).await;if w[key]==value{return;}assert!(tokio::time::Instant::now()<deadline,"Watcher did not reach {key}={value}: {w}");tokio::time::sleep(Duration::from_millis(100)).await;}}
async fn idle(s:&Session){let deadline=tokio::time::Instant::now()+Duration::from_secs(30);loop{let jobs=api(s,"/jobs",None).await;if !jobs.as_array().unwrap().iter().any(|j|["queued","running","pausing","cancelling"].contains(&j["state"].as_str().unwrap())){return;}assert!(tokio::time::Instant::now()<deadline);tokio::time::sleep(Duration::from_millis(100)).await;}}
fn count(path:&std::path::Path,suffix:&str,state:&str)->i64{let c=rusqlite::Connection::open(path).unwrap();c.query_row("SELECT count(*) FROM files WHERE relative_path LIKE ?1 AND availability=?2",rusqlite::params![format!("%{suffix}"),state],|r|r.get(0)).unwrap()}
async fn indexed(path:&std::path::Path,suffix:&str,state:&str){let deadline=tokio::time::Instant::now()+Duration::from_secs(30);loop{if count(path,suffix,state)==1{return;}assert!(tokio::time::Instant::now()<deadline,"File not indexed: {suffix} {state}");tokio::time::sleep(Duration::from_millis(100)).await;}}
#[tokio::main]async fn main(){
 let args:Vec<_>=std::env::args().collect();let out=PathBuf::from(args.get(1).expect("Fresh output directory"));assert!(!out.exists());fs::create_dir_all(&out).unwrap();let out=out.canonicalize().unwrap();let exe=PathBuf::from(args.get(2).expect("Core executable")).canonicalize().unwrap();let state=out.join("state");let database=state.join("library.sqlite");let source=out.join("source");fs::create_dir_all(source.join("Existing")).unwrap();fs::create_dir_all(source.join("Excluded")).unwrap();fs::write(source.join("Existing/keep.bin"),b"unchanged original").unwrap();
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let root=api(&first,"/roots",Some(json!({"path":source,"label":"Native watch fixture"}))).await;let rid=root["id"].as_str().unwrap();wait_watch(&first,rid,"status",json!("watching")).await;
 let watch=api(&first,&format!("/roots/{rid}/watch"),None).await;api(&first,&format!("/roots/{rid}/watch"),Some(json!({"revision":watch["revision"],"enabled":true,"exclude":["Excluded"]}))).await;wait_watch(&first,rid,"status",json!("watching")).await;
 api(&first,"/scans",Some(json!({"root_id":rid,"scope":"","exclude":["Excluded"]}))).await;idle(&first).await;wait_watch(&first,rid,"needs_scan",json!(false)).await;
 fs::create_dir_all(source.join("Incoming/deep")).unwrap();fs::write(source.join("Incoming/deep/new.bin"),b"incoming game fixture").unwrap();fs::write(source.join("Excluded/ignored.bin"),b"excluded fixture").unwrap();indexed(&database,"new.bin","present").await;idle(&first).await;assert_eq!(count(&database,"ignored.bin","present"),0);
 let c=rusqlite::Connection::open(&database).unwrap();let visits:i64=c.query_row("SELECT count(*) FROM observations o JOIN jobs j ON j.id=o.job_id JOIN files f ON f.id=o.file_id WHERE json_extract(j.spec,'$.automatic')=1 AND f.relative_path LIKE '%keep.bin'",[],|r|r.get(0)).unwrap();assert_eq!(visits,0,"Incremental scan visited unrelated existing subtree");drop(c);
 fs::remove_file(source.join("Incoming/deep/new.bin")).unwrap();fs::remove_dir(source.join("Incoming/deep")).unwrap();indexed(&database,"new.bin","missing").await;idle(&first).await;
 fs::write(source.join("Existing/after-restart.bin"),b"durable pending change").unwrap();let deadline=tokio::time::Instant::now()+Duration::from_secs(10);loop{let w=api(&first,&format!("/roots/{rid}/watch"),None).await;if w["pending"].as_u64().unwrap()>0{break;}assert!(tokio::time::Instant::now()<deadline);tokio::time::sleep(Duration::from_millis(20)).await;}
 local_core::request(&state,&exe,"stop").await.unwrap();tokio::time::sleep(Duration::from_millis(700)).await;let second=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();assert_ne!(first.instance_id,second.instance_id);indexed(&database,"after-restart.bin","present").await;wait_watch(&second,rid,"needs_scan",json!(true)).await;idle(&second).await;
 // Taking the whole root offline must preserve its indexed files.
 let offline=out.join("offline-source");fs::rename(&source,&offline).unwrap();wait_watch(&second,rid,"status",json!("offline")).await;assert_eq!(count(&database,"keep.bin","present"),1);fs::rename(&offline,&source).unwrap();wait_watch(&second,rid,"status",json!("watching")).await;
 let w=api(&second,&format!("/roots/{rid}/watch"),None).await;api(&second,&format!("/roots/{rid}/watch"),Some(json!({"revision":w["revision"],"enabled":false,"exclude":["Excluded"]}))).await;wait_watch(&second,rid,"status",json!("disabled")).await;fs::write(source.join("Existing/disabled.bin"),b"not auto indexed").unwrap();tokio::time::sleep(Duration::from_secs(4)).await;assert_eq!(count(&database,"disabled.bin","present"),0);idle(&second).await;local_core::request(&state,&exe,"stop").await.unwrap();
 assert_eq!(fs::read(source.join("Existing/keep.bin")).unwrap(),b"unchanged original");let report=json!({"schema":db::SCHEMA_VERSION,"native_create":true,"directory_delete_marks_missing":true,"excluded_file_not_indexed":true,"unrelated_subtree_not_scanned":true,"pending_changes_survive_core_restart":true,"restart_gap_visible":true,"offline_preserves_catalog":true,"reattach_after_reconnect":true,"disabled_watch_stays_idle":true,"original_unchanged":true});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
