use galroon_core::local_core::{self,Session};
use serde_json::{json,Value};
use std::{fs,path::PathBuf,time::Duration};
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::builder().timeout(Duration::from_secs(20)).build().unwrap();let url=format!("{}/api{path}",s.url);let req=if let Some(body)=body{client.post(url).json(&body)}else{client.get(url)};let response=req.bearer_auth(&s.token).send().await.unwrap();assert!(response.status().is_success(),"API failed at {path}: {}",response.status());response.json().await.unwrap()}
#[tokio::main]async fn main(){
 use sha2::{Digest,Sha256};
 let args:Vec<_>=std::env::args().collect();let output=PathBuf::from(args.get(1).expect("Fresh fixture output"));let exe=PathBuf::from(args.get(2).expect("Core executable")).canonicalize().unwrap();assert!(!output.exists());fs::create_dir_all(&output).unwrap();let output=output.canonicalize().unwrap();let state=output.join("state");fs::create_dir(&state).unwrap();
 let client=reqwest::Client::builder().timeout(Duration::from_secs(20)).build().unwrap();let source:Value=client.post("https://api.vndb.org/kana/vn").json(&json!({"filters":["id","=","v1"],"fields":"title,developers.id,developers.name","results":1})).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();let work=source["results"][0].clone();assert_eq!(work["id"],"v1");let developers=work["developers"].as_array().unwrap();assert!(!developers.is_empty());let studio=developers[0]["name"].as_str().unwrap().to_owned();let hidden=developers.iter().map(|v|v["id"].clone()).collect::<Vec<_>>();
 let query=json!({"filters":["developer","=",["search","=",studio]],"fields":"title,alttitle,released,image.url,image.sexual,image.violence,developers.id,developers.name","sort":"released","reverse":true,"results":24,"page":1});let cache_key=format!("discovery.v1.{}",hex::encode(Sha256::digest(format!("vn:{query}").as_bytes())));let raw=json!({"results":[work],"more":false,"page":1,"fetched_at":galroon_core::db::now()});
 {let db=galroon_core::db::open(&state.join("library.sqlite")).unwrap();db.lock().unwrap().execute("INSERT INTO settings(key,value) VALUES(?1,?2)",rusqlite::params![cache_key,raw.to_string()]).unwrap();}
 fs::write(output.join("public-source.json"),serde_json::to_vec_pretty(&source).unwrap()).unwrap();
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let checking_state=state.clone();
 let outcome=tokio::spawn(async move{
 let mut url=reqwest::Url::parse(&format!("{}/api/discover",first.url)).unwrap();url.query_pairs_mut().append_pair("kind","studio").append_pair("value",&studio).append_pair("target","works");let path=format!("/discover?{}",url.query().unwrap());assert_eq!(api(&first,&path,None).await["results"].as_array().unwrap().len(),1);
 api(&first,"/vns/v1/relationship-decisions",Some(json!({"revision":0,"request_id":"hide","hidden":{"companies":hidden,"people":[],"characters":[],"works":[]}}))).await;
 let start=std::time::Instant::now();let cold=api(&first,&path,None).await;let cold_ms=start.elapsed().as_millis();assert!(cold["results"].as_array().unwrap().is_empty());
 let c=rusqlite::Connection::open_with_flags(checking_state.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();let count:i64=c.query_row("SELECT count(*) FROM settings WHERE key LIKE 'discovery.membership.v1.%'",[],|r|r.get(0)).unwrap();assert_eq!(count,1);let cache:String=c.query_row("SELECT value FROM settings WHERE key LIKE 'discovery.membership.v1.%'",[],|r|r.get(0)).unwrap();assert_eq!(serde_json::from_str::<Value>(&cache).unwrap()["keep"],false);
 let start=std::time::Instant::now();let warm=api(&first,&path,None).await;let warm_ms=start.elapsed().as_millis();assert_eq!(warm,cold);assert_eq!(c.query_row("SELECT value FROM settings WHERE key LIKE 'discovery.membership.v1.%'",[],|r|r.get::<_,String>(0)).unwrap(),cache);
 api(&first,"/vns/v1/relationship-decisions",Some(json!({"revision":1,"request_id":"restore","hidden":{"companies":[],"people":[],"characters":[],"works":[]}}))).await;assert_eq!(api(&first,&path,None).await,raw);assert_eq!(c.query_row("SELECT count(*) FROM works",[],|r|r.get::<_,i64>(0)).unwrap(),0);
 json!({"separate_core":true,"live_vndb_membership_request":true,"public_work":"v1","isolated_seeded_search_rows":1,"hidden_developers":hidden,"result_counts":[1,0,0,1],"cold_ms":cold_ms,"warm_ms":warm_ms,"verdict_cache_rows":count,"collection_entries":0,"source_files":0,"schema":galroon_core::db::SCHEMA_VERSION})
 }).await;
 let stopped=local_core::request(&state,&exe,"stop").await;let report=outcome.expect("Search verification failed; stop attempted");stopped.unwrap();fs::write(output.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
