//! Verify generated tag membership, receipts and undo through installed Core backup/restore.
use galroon_core::{backup,local_core::{self,Session},plans};
use serde_json::{Value,json};
use std::{path::{Path,PathBuf},fs,collections::BTreeMap,time::Duration};
fn snapshot(path:&Path)->BTreeMap<String,Vec<String>>{
 let c=rusqlite::Connection::open_with_flags(path,rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();
 assert_eq!(c.query_row("PRAGMA integrity_check",[],|r|r.get::<_,String>(0)).unwrap(),"ok");assert_eq!(c.query_row("SELECT count(*) FROM pragma_foreign_key_check",[],|r|r.get::<_,i64>(0)).unwrap(),0);
 let mut out=BTreeMap::new();for table in ["member_catalog_state","resources","resource_files","files","roots","membership_history"]{let mut s=c.prepare(&format!("SELECT * FROM {table}")).unwrap();let count=s.column_count();let mut rows=s.query_map([],|r|Ok((0..count).map(|i|format!("{:?}",r.get_ref(i).unwrap())).collect::<Vec<_>>().join("\n"))).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();rows.sort();out.insert(table.into(),rows);}out
}
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::builder().no_proxy().timeout(Duration::from_secs(30)).build().unwrap();let url=format!("{}/api{path}",s.url);let r=if let Some(body)=body{client.post(url).json(&body)}else{client.get(url)}.bearer_auth(&s.token).send().await.unwrap();assert!(r.status().is_success(),"API {path}: {}",r.status());r.json().await.unwrap()}
async fn stop(state:&Path,exe:&Path){local_core::request(state,exe,"stop").await.unwrap();let f=fs::OpenOptions::new().read(true).write(true).open(state.join("core.lock")).unwrap();let end=tokio::time::Instant::now()+Duration::from_secs(15);while fs2::FileExt::try_lock_exclusive(&f).is_err(){assert!(tokio::time::Instant::now()<end);tokio::time::sleep(Duration::from_millis(50)).await;}}
#[tokio::main]async fn main(){
 let args=std::env::args().collect::<Vec<_>>();let state=PathBuf::from(&args[1]).canonicalize().unwrap();let exe=PathBuf::from(&args[2]).canonicalize().unwrap();let out=PathBuf::from(&args[3]);assert!(!out.exists());fs::create_dir_all(&out).unwrap();let out=out.canonicalize().unwrap();let backups=out.join("backups");fs::create_dir(&backups).unwrap();let restored=out.join("restored");
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();
 let original=snapshot(&state.join("library.sqlite"));assert_eq!(original["files"].len(),6539);
 let page=api(&first,"/resources/source/members/page",None).await;assert_eq!(page["total"],6539);
 let exported=api(&first,"/backups",Some(json!({"destination":backups}))).await;let folder=PathBuf::from(exported["path"].as_str().unwrap());let manifest=backup::inspect(&folder).unwrap();assert_eq!(manifest.schema,Some(42));assert!(manifest.tables.contains(&"member_catalog_state".to_owned()));assert_eq!(snapshot(&folder.join("collection.sqlite")),original);
 stop(&state,&exe).await;backup::restore_new(&folder,&restored,Some(&manifest.sha256)).unwrap();assert_eq!(snapshot(&restored.join("library.sqlite")),original);
 let second=local_core::connect_or_start(restored.clone(),exe.clone()).await.unwrap();assert_eq!(first.library_id,second.library_id);assert_eq!(api(&second,"/resources/source/members/page",None).await,page);
 let client=reqwest::Client::builder().no_proxy().timeout(Duration::from_secs(30)).build().unwrap();let url=format!("{}/api/resources/source/members/page",second.url);let cursor=page["next"].as_str().unwrap();let next:Value=client.get(&url).bearer_auth(&second.token).query(&[("before",cursor)]).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();assert_eq!(next["items"][0]["id"],"f00060");
 {let c=rusqlite::Connection::open(restored.join("library.sqlite")).unwrap();c.execute("UPDATE files SET availability='missing' WHERE id='f00000'",[]).unwrap();}
 assert_eq!(client.get(&url).bearer_auth(&second.token).query(&[("before",cursor)]).send().await.unwrap().status(),400);let fresh=api(&second,"/resources/source/members/page",None).await;assert_eq!(fresh["items"][0]["availability"],"missing");assert!(fresh["catalog_revision"].as_i64().unwrap()>page["catalog_revision"].as_i64().unwrap());
 stop(&restored,&exe).await;let c=rusqlite::Connection::open_with_flags(restored.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM sessions",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(c.query_row("SELECT count(*) FROM source_watch WHERE enabled=1",[],|r|r.get::<_,i64>(0)).unwrap(),0);
 let report=json!({"passed":true,"schema":42,"members":6539,"exact_tables":original.keys().collect::<Vec<_>>(),"backup_manifest_verified":true,"backup_sha256":manifest.sha256,"same_page_after_restore":true,"restored_cursor_continues":true,"file_change_invalidates_cursor":true,"watchers_disabled":true,"no_sessions":true,"both_core_stopped":true,"core_sha256":plans::hash(&exe).unwrap().1,"physical_files":0,"scope":"HTTP backup using supplied Core executable plus restore_new helper and restarted Core; not native UI restore"});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
