use galroon_core::local_core::{self,Session};
use serde_json::{json,Value};
use std::{fs,path::PathBuf,time::Duration};
async fn api(s:&Session,path:&str,body:Option<Value>)->Value{let client=reqwest::Client::builder().timeout(Duration::from_secs(20)).build().unwrap();let url=format!("{}/api{path}",s.url);let req=if let Some(body)=body{client.post(url).json(&body)}else{client.get(url)};let response=req.bearer_auth(&s.token).send().await.unwrap();assert!(response.status().is_success(),"API failed at {path}: {}",response.status());response.json().await.unwrap()}
#[tokio::main]async fn main(){
 let args:Vec<_>=std::env::args().collect();let output=PathBuf::from(args.get(1).expect("Fresh fixture output"));let exe=PathBuf::from(args.get(2).expect("Core executable")).canonicalize().unwrap();assert!(!output.exists());fs::create_dir_all(&output).unwrap();let output=output.canonicalize().unwrap();let state=output.join("state");fs::create_dir(&state).unwrap();
 let password=format!("Generated-{}",uuid::Uuid::new_v4());
 {let db=galroon_core::db::open(&state.join("library.sqlite")).unwrap();galroon_core::access::setup(&db,&password,false).unwrap();let c=db.lock().unwrap();c.execute("INSERT INTO works(id,title,original_title,vndb_id) VALUES('w','Fixture','Fixture','v1')",[]).unwrap();let cached=json!({"fetched_at":galroon_core::db::now(),"vn":{"developers":[],"staff":[{"id":"s1","name":"Person","role":"scenario"}],"va":[]},"characters":[],"more":false});c.execute("INSERT INTO settings(key,value) VALUES('exploration.v4.work.v1.1',?1)",[cached.to_string()]).unwrap();c.execute("INSERT INTO settings(key,value) VALUES('exploration.v4.work.v99.1',?1)",[cached.to_string()]).unwrap();}
 let first=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let restart_state=state.clone();let restart_exe=exe.clone();
 let outcome=tokio::spawn(async move{
 let tag=api(&first,"/custom-tags",Some(json!({"name":"Favourite creators"}))).await;let id=tag["id"].as_str().unwrap();
 let assignment=json!({"tag_id":id,"revision":1,"assigned":true,"request_id":"assign"});let assigned=api(&first,"/entity-tags/s1",Some(assignment.clone())).await;assert_eq!(assigned["revision"],2);assert_eq!(api(&first,"/entity-tags/s1",Some(assignment.clone())).await,assigned);
 let tags=api(&first,"/custom-tags",None).await;assert_eq!(tags[0]["entity_count"],1);assert_eq!(api(&first,"/entity-tags/s1",None).await[0]["id"],id);
 let reasons=api(&first,"/works/w/related-tags",None).await;assert_eq!(reasons["complete"],true);assert_eq!(reasons["tags"][0]["id"],id);assert_eq!(reasons["tags"][0]["reasons"],json!([{"entity_id":"s1","name":"Person","kind":"person"}]));
 let definition=json!({"schema_version":1,"scope":"collection","sort":"title","rule":{"kind":"field","predicate":{"field":"related_personal_tags","mode":"any","values":[id]}}});let preview=api(&first,"/smart-lists/preview",Some(definition.clone())).await;assert_eq!(preview["total"],1);assert_eq!(preview["sample"][0]["work_key"],"local:w");
 let client=reqwest::Client::builder().timeout(Duration::from_secs(20)).build().unwrap();let login=client.post(format!("{}/api/access/login",first.url)).header("Origin",&first.url).json(&json!({"password":password,"name":"Generated readonly verification"})).send().await.unwrap();assert!(login.status().is_success());let cookie=login.headers()["set-cookie"].to_str().unwrap().split(';').next().unwrap().to_owned();
 let read=client.get(format!("{}/api/entity-tags/s1",first.url)).header("Cookie",&cookie).send().await.unwrap();assert!(read.status().is_success());let visible:Value=read.json().await.unwrap();assert_eq!(visible[0]["id"],id);
 let web_reasons=client.get(format!("{}/api/works/w/related-tags",first.url)).header("Cookie",&cookie).send().await.unwrap();assert!(web_reasons.status().is_success());assert_eq!(web_reasons.json::<Value>().await.unwrap(),reasons);
 let external=api(&first,"/vns/v99/related-tags",None).await;assert_eq!(external,reasons);
 let external_web=client.get(format!("{}/api/vns/v99/related-tags",first.url)).header("Cookie",&cookie).send().await.unwrap();assert!(external_web.status().is_success());assert_eq!(external_web.json::<Value>().await.unwrap(),external);
 let absent=api(&first,"/vns/v98/related-tags",None).await;assert_eq!(absent,json!({"tags":[],"complete":false}));
 {let c=rusqlite::Connection::open_with_flags(restart_state.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM works",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert_eq!(c.query_row("SELECT count(*) FROM works WHERE vndb_id='v99'",[],|r|r.get::<_,i64>(0)).unwrap(),0);}
 let mutation=json!({"tag_id":id,"revision":2,"assigned":false,"request_id":"web-refused"});let refused=client.post(format!("{}/api/entity-tags/s1",first.url)).header("Cookie",&cookie).header("Origin",&first.url).json(&mutation).send().await.unwrap();assert_eq!(refused.status(),reqwest::StatusCode::FORBIDDEN);assert_eq!(api(&first,"/entity-tags/s1",None).await[0]["revision"],2);
 local_core::request(&restart_state,&restart_exe,"stop").await.unwrap();let second=local_core::connect_or_start(restart_state,restart_exe).await.unwrap();assert_eq!(api(&second,"/entity-tags/s1",Some(assignment)).await,assigned);
 api(&second,"/entity-tags/s1",Some(json!({"tag_id":id,"revision":2,"assigned":false,"request_id":"remove"}))).await;assert_eq!(api(&second,"/smart-lists/preview",Some(definition)).await["total"],0);
 assert!(api(&second,"/works/w/related-tags",None).await["tags"].as_array().unwrap().is_empty());
 json!({"separate_core_process":true,"entity_assign_and_same_receipt_replay":true,"entity_count":1,"external_owner_web_equal":true,"external_not_added_to_collection":true,"missing_external_cache_incomplete":true,"owner_and_web_reasons_equal":true,"removed_reasons_absent":true,"related_rule_before_after":[1,0],"web_cookie_read":true,"web_write_forbidden":true,"restart_preserved_receipt_and_assignment":true,"generated_works":1,"source_files":0,"schema":galroon_core::db::SCHEMA_VERSION})
 }).await;
 let stopped=local_core::request(&state,&exe,"stop").await;let report=outcome.expect("Entity tag validation failed; stop attempted");stopped.unwrap();fs::write(output.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
