use galroon_core::local_core;use serde_json::{json,Value};use std::{fs,path::PathBuf,sync::{Arc,atomic::{AtomicUsize,Ordering}},time::Duration};
#[tokio::main]async fn main(){
 use tokio::io::{AsyncReadExt,AsyncWriteExt};
 let args:Vec<_>=std::env::args().collect();let output=PathBuf::from(args.get(1).expect("Fresh output"));let exe=PathBuf::from(args.get(2).expect("Core executable")).canonicalize().unwrap();assert!(!output.exists());fs::create_dir_all(&output).unwrap();let output=output.canonicalize().unwrap();let state=output.join("state");fs::create_dir(&state).unwrap();
 let mut expected=vec![];{let db=galroon_core::db::open(&state.join("library.sqlite")).unwrap();let c=db.lock().unwrap();
 for(kind,id,endpoint)in [("person","s1","people"),("character","c1","characters"),("company","p1","companies")]{
  let key=format!("exploration.v3.{kind}.{id}.1");let page=json!({(kind):{"id":id,"name":"Saved identity","description":"Saved introduction"},"works":[{"id":"v1","title":"Saved credit","staff":[{"id":"s1","name":"Actual alias","role":"scenario"}]}],"page":1,"more":true,"fetched_at":0});
  c.execute("INSERT INTO settings(key,value) VALUES(?1,?2)",rusqlite::params![key,page.to_string()]).unwrap();
  c.execute("INSERT INTO settings(key,value) VALUES(?1,?2)",rusqlite::params![format!("exploration.v3.profile.{kind}.{id}"),json!({"profile":{"id":id,"name":"New identity","description":"New introduction"},"fetched_at":galroon_core::db::now()}).to_string()]).unwrap();expected.push((format!("/{endpoint}/{id}"),key,page));
 }
 let key="exploration.v4.work.v1.1";let page=json!({"vn":{"id":"v1","title":"Saved work","description":"Saved work introduction"},"characters":[{"id":"c1","name":"Saved character"}],"more":false,"fetched_at":0});c.execute("INSERT INTO settings(key,value) VALUES(?1,?2)",rusqlite::params![key,page.to_string()]).unwrap();expected.push(("/vns/v1/exploration".into(),key.into(),page));}
 let listener=tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();let address=format!("http://{}",listener.local_addr().unwrap());let failures=Arc::new(AtomicUsize::new(0));let count=failures.clone();let proxy=tokio::spawn(async move{loop{let(mut socket,_)=listener.accept().await.unwrap();let mut buf=[0;4096];let n=socket.read(&mut buf).await.unwrap();assert!(String::from_utf8_lossy(&buf[..n]).starts_with("CONNECT api.vndb.org:443 "));count.fetch_add(1,Ordering::SeqCst);let _=socket.write_all(b"HTTP/1.1 502 Offline fixture\r\nContent-Length: 0\r\nConnection: close\r\n\r\n").await;}});
 std::env::set_var("HTTPS_PROXY",&address);std::env::set_var("https_proxy",&address);std::env::set_var("NO_PROXY","127.0.0.1,localhost");std::env::set_var("no_proxy","127.0.0.1,localhost");
 let session=local_core::connect_or_start(state.clone(),exe.clone()).await.unwrap();let rs=state.clone();
 let outcome=tokio::spawn(async move{
 let client=reqwest::Client::builder().no_proxy().timeout(Duration::from_secs(20)).build().unwrap();
 for(path,key,old)in expected{let response=client.get(format!("{}/api{path}",session.url)).bearer_auth(&session.token).send().await.unwrap().error_for_status().unwrap();let mut value:Value=response.json().await.unwrap();assert_eq!(value["stale"],true);assert!(value["warning"].is_string());value.as_object_mut().unwrap().remove("stale");value.as_object_mut().unwrap().remove("warning");assert_eq!(value,old,"{path}");let c=rusqlite::Connection::open_with_flags(rs.join("library.sqlite"),rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY).unwrap();let saved:String=c.query_row("SELECT value FROM settings WHERE key=?1",[key],|r|r.get(0)).unwrap();assert_eq!(serde_json::from_str::<Value>(&saved).unwrap(),old);}
 assert_eq!(failures.load(Ordering::SeqCst),4);json!({"separate_core":true,"partial_profile_failures":3,"work_refresh_failure":1,"stale_pages_keep_exact_previous_data":true,"cached_pages_unchanged":4,"outbound_proxy_failures":4,"source_files":0,"schema":galroon_core::db::SCHEMA_VERSION})
 }).await;let stopped=local_core::request(&state,&exe,"stop").await;proxy.abort();let report=outcome.expect("Verification failed; stop attempted");stopped.unwrap();fs::write(output.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
