//! Generated archives only. Verifies successful full-volume acquisition and missing-last-volume rejection.
use galroon_core::{acquire,db,scan,plans};
use std::{path::{Path,PathBuf},fs,process::{Command,Stdio}};
fn index(d:&db::Db,path:&Path,root:&str)->String{d.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES(?1,?2,'Volumes')",rusqlite::params![root,path.to_str().unwrap()]).unwrap();let j=scan::create(d,scan::ScanSpec{root_id:root.into(),scope:"".into(),exclude:vec![]}).unwrap();scan::run(d.clone(),j);d.lock().unwrap().query_row("SELECT id FROM resources WHERE root_id=?1",[root],|r|r.get(0)).unwrap()}
fn state(d:&db::Db,j:&str)->(String,String){d.lock().unwrap().query_row("SELECT state,message FROM jobs WHERE id=?1",[j],|r|Ok((r.get(0)?,r.get(1)?))).unwrap()}
fn main(){
 let out=PathBuf::from(std::env::args().nth(1).expect("Fresh fixture directory required"));assert!(!out.exists());fs::create_dir_all(&out).unwrap();let out=out.canonicalize().unwrap();for name in ["full","missing-last","gap","destination","legacy-destination"]{fs::create_dir(out.join(name)).unwrap();}
 let input=out.join("fixture.bin");let bytes:Vec<u8>=(0..512*1024).map(|i|(i%251)as u8).collect();fs::write(&input,&bytes).unwrap();let helper=acquire::helper().unwrap();let mut cmd=Command::new(helper);#[cfg(windows)]{use std::os::windows::process::CommandExt;cmd.creation_flags(0x08000000);}let status=cmd.args(["a","-t7z","-mx=0","-v128k"]).arg(out.join("full/story.7z")).arg(&input).stdout(Stdio::null()).stderr(Stdio::null()).status().unwrap();assert!(status.success());
 let mut parts=fs::read_dir(out.join("full")).unwrap().map(|e|e.unwrap().path()).collect::<Vec<_>>();parts.sort();assert!(parts.len()>=4);let originals:Vec<_>=parts.iter().map(|p|plans::hash(p).unwrap()).collect();
 for (i,p)in parts.iter().enumerate(){if i+1<parts.len(){fs::copy(p,out.join("missing-last").join(p.file_name().unwrap())).unwrap();}if i!=1{fs::copy(p,out.join("gap").join(p.file_name().unwrap())).unwrap();}}
 let d=db::open(&out.join("state/library.sqlite")).unwrap();let full=index(&d,&out.join("full"),"full");assert_eq!(d.lock().unwrap().query_row("SELECT count(*) FROM resources WHERE root_id='full'",[],|r|r.get::<_,i64>(0)).unwrap(),1);let preview=acquire::preview(&d,&full).unwrap();assert_eq!(preview["files"].as_array().unwrap().len(),parts.len());
 let j=acquire::create(&d,&full,out.join("destination").to_str().unwrap(),true).unwrap();acquire::run(d.clone(),j.clone(),None);let(st,message)=state(&d,&j);assert_eq!(st,"completed","{message}");let spec:String=d.lock().unwrap().query_row("SELECT spec FROM jobs WHERE id=?1",[&j],|r|r.get(0)).unwrap();let spec:acquire::Spec=serde_json::from_str(&spec).unwrap();assert_eq!(fs::read(Path::new(&spec.final_folder).join("story.7z.001-extracted/fixture.bin")).unwrap(),bytes);
 let missing=index(&d,&out.join("missing-last"),"missing");let j=acquire::create(&d,&missing,out.join("destination").to_str().unwrap(),false).unwrap();acquire::run(d.clone(),j.clone(),None);let(st,message)=state(&d,&j);assert_eq!(st,"failed");assert!(message.contains("volume verification failed"),"{message}");let spec:String=d.lock().unwrap().query_row("SELECT spec FROM jobs WHERE id=?1",[&j],|r|r.get(0)).unwrap();let spec:acquire::Spec=serde_json::from_str(&spec).unwrap();assert!(!Path::new(&spec.final_folder).exists());
 let gap=index(&d,&out.join("gap"),"gap");assert!(acquire::create(&d,&gap,out.join("destination").to_str().unwrap(),false).unwrap_err().contains("Missing archive volumes"));
 // Model a pre-grouping catalog with one resource per volume. Acquiring its first volume includes siblings.
 {let c=d.lock().unwrap();let mut s=c.prepare("SELECT file_id FROM resource_files rf JOIN files f ON f.id=rf.file_id WHERE resource_id=?1 ORDER BY f.path").unwrap();let ids=s.query_map([&full],|r|r.get::<_,String>(0)).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();for fid in ids.iter().skip(1){c.execute("DELETE FROM resource_files WHERE resource_id=?1 AND file_id=?2",rusqlite::params![full,fid]).unwrap();}}
 assert_eq!(acquire::preview(&d,&full).unwrap()["files"].as_array().unwrap().len(),parts.len());let j=acquire::create(&d,&full,out.join("legacy-destination").to_str().unwrap(),false).unwrap();acquire::run(d.clone(),j.clone(),None);assert_eq!(state(&d,&j).0,"completed");for(p,hash)in parts.iter().zip(originals){assert_eq!(plans::hash(p).unwrap(),hash);}
 let report=serde_json::json!({"volumes":parts.len(),"single_resource_group":true,"all_volumes_copied_and_extracted":true,"missing_last_volume_rejected":true,"gap_rejected_before_queue":true,"legacy_first_volume_expands_siblings":true,"sources_unchanged":true});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
