//! Generated archives only: same names in different directories must extract independently.
use galroon_core::{acquire,db,scan,plans};
use std::{fs,path::PathBuf,process::{Command,Stdio}};
fn main(){
 let out=PathBuf::from(std::env::args().nth(1).expect("Fresh fixture directory required"));assert!(!out.exists());fs::create_dir_all(&out).unwrap();let out=out.canonicalize().unwrap();let source=out.join("source");let dest=out.join("destination");fs::create_dir(&dest).unwrap();let helper=acquire::helper().expect("7-Zip is required");
 for(name,data)in [("base",b"base archive content".as_slice()),("extras",b"extra archive content")]{let dir=source.join("Game").join(name);fs::create_dir_all(&dir).unwrap();let input=out.join(format!("{name}.txt"));fs::write(&input,data).unwrap();let mut cmd=Command::new(&helper);#[cfg(windows)]{use std::os::windows::process::CommandExt;cmd.creation_flags(0x08000000);}assert!(cmd.args(["a","-tzip"]).arg(dir.join("game.zip")).arg(input).stdout(Stdio::null()).stderr(Stdio::null()).status().unwrap().success());}
 fs::write(source.join("Game/ignored.bin"),b"not selected").unwrap();let originals=[plans::hash(&source.join("Game/base/game.zip")).unwrap(),plans::hash(&source.join("Game/extras/game.zip")).unwrap()];
 let d=db::open(&out.join("state/library.sqlite")).unwrap();d.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES('r',?1,'Selection fixture')",[source.to_str().unwrap()]).unwrap();let j=scan::create(&d,scan::ScanSpec{root_id:"r".into(),scope:"".into(),exclude:vec![]}).unwrap();scan::run(d.clone(),j);let rid:String=d.lock().unwrap().query_row("SELECT id FROM resources",[],|r|r.get(0)).unwrap();let p=acquire::preview(&d,&rid).unwrap();let selection=acquire::Selection{manifest_digest:p["manifest_digest"].as_str().unwrap().into(),file_ids:p["files"].as_array().unwrap().iter().filter(|f|f["archive_entry"]==true).map(|f|f["id"].as_str().unwrap().into()).collect()};
 let job=acquire::create_selected(&d,&rid,dest.to_str().unwrap(),true,Some(&selection)).unwrap();acquire::run(d.clone(),job.clone(),None);let(state,message,spec):(String,String,String)=d.lock().unwrap().query_row("SELECT state,message,spec FROM jobs WHERE id=?1",[&job],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).unwrap();assert_eq!(state,"completed","{message}");let spec:acquire::Spec=serde_json::from_str(&spec).unwrap();let published=PathBuf::from(&spec.final_folder);
 for(name,data)in [("base",b"base archive content".as_slice()),("extras",b"extra archive content")]{assert_eq!(fs::read(published.join(format!("{name}/game.zip-extracted/{name}.txt"))).unwrap(),data);}
 assert!(!published.join("ignored.bin").exists());assert_eq!(fs::read(source.join("Game/ignored.bin")).unwrap(),b"not selected");for(index,name)in ["base","extras"].iter().enumerate(){assert_eq!(plans::hash(&source.join(format!("Game/{name}/game.zip"))).unwrap(),originals[index]);}
 d.lock().unwrap().execute("UPDATE jobs SET state='queued' WHERE id=?1",[&job]).unwrap();acquire::run(d.clone(),job.clone(),None);assert_eq!(d.lock().unwrap().query_row("SELECT state FROM jobs WHERE id=?1",[job],|r|r.get::<_,String>(0)).unwrap(),"completed");
 let report=serde_json::json!({"selected":2,"source_files":3,"same_name_archives_extracted_independently":true,"relative_layout_preserved":true,"unselected_file_omitted":true,"sources_unchanged":true,"publication_recovery":true});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}
