use galroon_core::{acquire,scan,db};
use std::{fs,process::{Command,Stdio},io::Write};
fn main(){
 let out=std::env::args().nth(1).expect("new test output folder required");let out=std::path::Path::new(&out);assert!(!out.exists(),"Use a fresh test folder");fs::create_dir_all(out).unwrap();let out=out.canonicalize().unwrap();let source=out.join("source");let dest=out.join("destination");fs::create_dir(&source).unwrap();fs::create_dir(&dest).unwrap();let input=out.join("hello.txt");fs::write(&input,b"Galroon encrypted archive verification\n").unwrap();
 let exe=acquire::helper().expect("Archive helper is required for this verification");let mut cmd=Command::new(exe);cmd.args(["a","-t7z","-p","-mhe=on"]).arg(source.join("encrypted.7z")).arg(&input).stdin(Stdio::piped()).stdout(Stdio::null()).stderr(Stdio::null());let mut child=cmd.spawn().unwrap();{let mut stdin=child.stdin.take().unwrap();stdin.write_all(b"fixture-password\nfixture-password\n").unwrap();}assert!(child.wait().unwrap().success());
 let d=db::open(&out.join("state/library.sqlite")).unwrap();d.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES('r',?1,'Synthetic fixture')",[source.to_str().unwrap()]).unwrap();let s=scan::create(&d,scan::ScanSpec{root_id:"r".into(),scope:"".into(),exclude:vec![]}).unwrap();scan::run(d.clone(),s);
 let rid:String=d.lock().unwrap().query_row("SELECT id FROM resources",[],|r|r.get(0)).unwrap();let j=acquire::create(&d,&rid,dest.to_str().unwrap(),true).unwrap();acquire::run(d.clone(),j.clone(),Some("fixture-password".into()));
 let(state,message,spec):(String,String,String)=d.lock().unwrap().query_row("SELECT state,message,spec FROM jobs WHERE id=?1",[&j],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).unwrap();assert_eq!(state,"completed","{message}");assert!(!spec.contains("fixture-password"));let spec:acquire::Spec=serde_json::from_str(&spec).unwrap();assert_eq!(fs::read(std::path::Path::new(&spec.final_folder).join("encrypted.7z-extracted/hello.txt")).unwrap(),fs::read(&input).unwrap());assert!(source.join("encrypted.7z").exists());
 d.lock().unwrap().execute("UPDATE jobs SET state='queued' WHERE id=?1",[&j]).unwrap();acquire::run(d.clone(),j.clone(),None);let recovered:String=d.lock().unwrap().query_row("SELECT state FROM jobs WHERE id=?1",[&j],|r|r.get(0)).unwrap();assert_eq!(recovered,"completed");
 let report=serde_json::json!({"publication_recovery":"passed","encrypted_7z":"passed","password_on_command_line":false,"password_persisted":false,"source_preserved":true,"extracted_content_matches":true});fs::write(out.join("report.json"),serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("{report}");
}

