"""Generate NSIS post-operation cleanup from the built Vite entrypoint."""
from pathlib import Path
import re

root=Path(__file__).resolve().parents[1]
html=(root/'dist/index.html').read_text(encoding='utf-8')
referenced=set(re.findall(r'assets/(index-[A-Za-z0-9_-]{8}\.(?:js|css))',html))
current=sorted(p.name for p in (root/'dist/assets').iterdir() if p.is_file() and re.fullmatch(r'index-[A-Za-z0-9_-]{8}\.(?:js|css)',p.name))
if not referenced.issubset(current):
    raise SystemExit('Referenced entrypoint missing from dist/assets')
if not current or not any(name.endswith('.js') for name in current):
    raise SystemExit('Expected hashed Vite entrypoints in dist/index.html; refusing unsafe cleanup')
for name in current:
    if not (root/'dist/assets'/name).is_file():
        raise SystemExit(f'Missing referenced entrypoint: {name}')
lines=['; Generated by scripts/generate_installer_hooks.py. Do not edit.',
       '; Cleanup happens only after normal app-running checks and file operations.',
       '; Keep every shipped entrypoint/chunk, including dynamic imports.',
       '!macro NSIS_HOOK_POSTINSTALL','  Push $R0','  Push $R1']
for ext in ['js','css']:
    prefix=f'galroon_cleanup_{ext}'
    lines += [f'  FindFirst $R0 $R1 "$INSTDIR\\web\\assets\\index-????????.{ext}"',f'  IfErrors {prefix}_end',f'{prefix}_loop:',f'  StrCmp $R1 "" {prefix}_close']
    for name in current:
        lines += [f'  StrCmp $R1 "{name}" {prefix}_next']
    lines += ['  Delete "$INSTDIR\\web\\assets\\$R1"',f'{prefix}_next:','  FindNext $R0 $R1',f'  Goto {prefix}_loop',f'{prefix}_close:','  FindClose $R0',f'{prefix}_end:']
lines += ['  Pop $R1','  Pop $R0','!macroend','',
          '!macro NSIS_HOOK_POSTUNINSTALL',
          '  Delete "$INSTDIR\\web\\assets\\index-????????.js"',
          '  Delete "$INSTDIR\\web\\assets\\index-????????.css"',
          '  RMDir "$INSTDIR\\web\\assets"','  RMDir "$INSTDIR\\web"','  RMDir "$INSTDIR"','!macroend','']
(root/'apps/desktop/src-tauri/installer-hooks.nsh').write_text('\n'.join(lines),encoding='utf-8')
print('Preserved installer entrypoints: '+', '.join(current))
