import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {ShieldCheck} from 'lucide-react';
import {api,coreUrl} from './api';
type Device={id:string;name:string;role:string;created:number;expires:number;last_used:number;revoked:boolean};
export function AccessPanel(){
 const {t}=useTranslation();const [configured,setConfigured]=useState<boolean|null>(null),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[review,setReview]=useState(false),[deviceName,setDeviceName]=useState(''),[devices,setDevices]=useState<Device[]>([]),[pair,setPair]=useState<{code:string;expires:number}|null>(null),[now,setNow]=useState(Date.now()/1000),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const reload=async()=>{const [status,list]=await Promise.all([api<{configured:boolean}>('/access/status'),api<Device[]>('/access/devices')]);setConfigured(status.configured);setDevices(list);};
 useEffect(()=>{void reload().catch(e=>setError(e.message));const timer=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(timer);},[]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <section className="section access-panel"><h2><ShieldCheck size={20}/> {t('accessTitle')}</h2><p>{t('accessHint')}</p>{configured===null?<p>{t('loading')}</p>:<><h3>{t(configured?'changeOwnerPassword':'setupOwner')}</h3><p>{t('ownerPasswordHint')}</p><div className="access-fields"><label>{t('ownerPassword')}<input type="password" autoComplete="new-password" value={password} onChange={e=>{setPassword(e.target.value);setReview(false);}}/></label><label>{t('confirmOwnerPassword')}<input type="password" autoComplete="new-password" value={confirm} onChange={e=>{setConfirm(e.target.value);setReview(false);}}/></label></div>{review?<div className="plan-item"><p>{t(configured?'passwordResetReview':'ownerSetupReview')}</p><button className="primary" disabled={busy} onClick={()=>void act(async()=>{await api(configured?'/access/password':'/access/setup',{password});setPassword('');setConfirm('');setReview(false);setPair(null);await reload();setMessage(t('ownerSaved'));})}>{t(configured?'confirmPasswordReset':'confirmOwnerSetup')}</button></div>:<button disabled={busy||Array.from(password).length<12||password!==confirm} onClick={()=>setReview(true)}>{t('reviewOwnerSettings')}</button>}{configured&&<><h3>{t('pairDevice')}</h3><p>{t('pairHint')}</p><label>{t('deviceName')}<input value={deviceName} maxLength={80} onChange={e=>setDeviceName(e.target.value)}/></label><button disabled={busy||!deviceName.trim()} onClick={()=>void act(async()=>{setPair(await api('/access/pairing',{name:deviceName}));})}>{t('createPairCode')}</button>{pair&&<div className="pair-code" role="status">{pair.expires>now?<><strong>{pair.code}</strong><span>{t('pairExpires',{seconds:Math.max(0,Math.ceil(pair.expires-now))})}</span></>:t('pairExpired')}</div>}<h3>{t('webAccess')}</h3><p>{t('webAccessHint')}</p><p className="path">{coreUrl()}/</p><div className="inline"><h3>{t('signedInDevices')}</h3><button disabled={busy} onClick={()=>void act(reload)}>{t('refreshDevices')}</button></div>{devices.length===0&&<p>{t('noDevices')}</p>}{devices.map(d=><div className="access-device" key={d.id}><div><strong>{d.name}</strong><p>{t(d.role==='web'?'readOnlyBrowser':'pairedDesktop')} · {t(d.revoked?'revoked':d.expires<=now?'expired':'activeDevice')}</p><small>{t('lastUsed')}: {new Date(d.last_used*1000).toLocaleString()}</small></div>{!d.revoked&&d.expires>now&&<button disabled={busy} onClick={()=>void act(async()=>{await api(`/access/devices/${d.id}/revoke`,{});await reload();setMessage(t('deviceRevoked'));})}>{t('revokeDevice')}</button>}</div>)}</>}</>}{message&&<p role="status">{message}</p>}{error&&<p className="error-text" role="alert">{error}</p>}</section>;
}
