import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
export type ListMember={work_key:string;title:string};
export function AddToList({members,onClose}:{members:ListMember[];onClose:()=>void}){
 const {t}=useTranslation(),dialog=useRef<HTMLDialogElement>(null),sending=useRef(false),request=useRef({key:'',id:''});
 const [lists,setLists]=useState<{id:string;name:string;revision:number}[]>([]),[next,setNext]=useState<string|null>(null),[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{added:number;skipped:number}|null>(null);
 async function load(after?:string){setBusy(true);setError('');try{const page=await api<{lists:typeof lists;next_after:string|null}>('/lists'+(after?'?after='+encodeURIComponent(after):''));setLists(old=>after?[...old,...page.lists]:page.lists);setNext(page.next_after);}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{dialog.current?.showModal();void load();},[]);
 async function save(){const list=lists.find(l=>l.id===target);if(!list||sending.current)return;const body={revision:list.revision,edit:{action:'add',members}},key=JSON.stringify([target,body]);if(request.current.key!==key)request.current={key,id:crypto.randomUUID()};sending.current=true;setBusy(true);setError('');try{setResult(await api(`/lists/${encodeURIComponent(target)}`,{...body,request_id:request.current.id}));}catch(e){setError(String(e));}finally{sending.current=false;setBusy(false);}}
 return <dialog ref={dialog} className="focus-tag-dialog add-to-list-dialog" aria-labelledby="add-to-list-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="add-to-list-title">{t('listAdd')}</h2>{result?<p role="status">{t('listAddedResult',result)}</p>:<><p>{t('listScopeCount',{count:members.length})}</p><details><summary>{t('listReviewWorks')}</summary><ol style={{maxHeight:180,overflow:'auto'}}>{members.map(m=><li key={m.work_key}>{m.title}</li>)}</ol></details><label>{t('listDestination')}<select aria-label={t('listDestination')} disabled={busy} value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('listChooseDestination')}</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{next&&<button disabled={busy} onClick={()=>void load(next)}>{t('listMore')}</button>}{!lists.length&&!busy&&!error&&<p>{t('listCreateFirst')}</p>}<button disabled={busy} onClick={()=>void load()}>{t('refreshView')}</button></>}{error&&<p role="alert">{error}</p>}<footer><button disabled={busy} onClick={onClose}>{t(result?'done':'cancel')}</button>{!result&&<button disabled={busy||!target||!members.length||members.length>10000} onClick={()=>void save()}>{t('listConfirmAdd')}</button>}</footer></dialog>;
}
