import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Search,RefreshCw} from 'lucide-react';
import {api,bytes,folder,type Root,type Job,type Plan} from './api';
type Report={job_id:string;state:string;candidates:number;verified:number;stale:number;errors:{path:string;error:string}[];groups:{sha256:string;files:{id:string;path:string;size:number}[]}[]};
export function DuplicatePanel({roots,jobs,onStarted,onPlan,onActivity}:{roots:Root[];jobs:Job[];onStarted:()=>Promise<void>;onPlan:(p:Plan)=>void;onActivity:()=>void}){
 const {t}=useTranslation();const [source,setSource]=useState('*'),[selected,setSelected]=useState(''),[report,setReport]=useState<Report|null>(null),[retained,setRetained]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');const checks=jobs.filter(j=>j.kind==='hash');const selectedId=selected||checks[0]?.id||'';const state=checks.find(j=>j.id===selectedId)?.state;const sources=roots.filter(r=>r.role!=='quarantine');
 useEffect(()=>{let current=true;setReport(null);setError('');if(selectedId)api<Report>(`/duplicate-checks/${selectedId}`).then(r=>{if(current)setReport(r);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[selectedId,state]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <section className="section duplicate-panel"><h2>{t('duplicates')}</h2><p>{t('hashJobHint')}</p><div className="inline"><label>{t('hashSources')}<select value={source} onChange={e=>setSource(e.target.value)}><option value="*">{t('allHashSources')}</option>{sources.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><button disabled={busy||sources.length===0} onClick={()=>void act(async()=>{const result=await api<{job_id:string}>('/duplicates',{root_ids:source==='*'?sources.map(r=>r.id):[source]});setSelected(result.job_id);setRetained({});await onStarted();})}><Search size={16}/>{t('startHashCheck')}</button><button onClick={onActivity}>{t('openActivity')}</button></div>{checks.length>0&&<label>{t('hashHistory')}<select value={selectedId} onChange={e=>{setSelected(e.target.value);setRetained({});}}>{checks.map(j=><option key={j.id} value={j.id}>{new Date(j.created*1000).toLocaleString()} · {t(j.state)}</option>)}</select></label>}{report&&<><div className="inline"><span className={`pill ${report.state}`}>{t(report.state)}</span><button disabled={busy} onClick={()=>void act(async()=>setReport(await api<Report>(`/duplicate-checks/${selectedId}`)))}><RefreshCw size={15}/>{t('refreshHashResults')}</button></div><p>{t('hashResultCounts',{verified:report.verified,candidates:report.candidates,groups:report.groups.length})}</p>{report.state!=='completed'&&<p>{t('hashNotFinished')}</p>}{report.stale>0&&<p className="error-text">{t('hashStale',{count:report.stale})}</p>}{report.errors.length>0&&<details><summary>{t('hashErrors',{count:report.errors.length})}</summary>{report.errors.map((e,i)=><p className="path error-text" key={i}>{e.path}: {e.error}</p>)}</details>}{report.state==='completed'&&report.groups.length===0&&<p>{t('noDuplicateGroups')}</p>}{report.groups.map(g=>{const keep=g.files.some(f=>f.id===retained[g.sha256])?retained[g.sha256]:g.files[0].id;return <div className="duplicate-group" key={g.sha256}><p>{t('hashEvidence')}</p>{g.files.map(f=><div className="resource-row" key={f.id}><label className="checkbox-label"><input type="radio" name={`retain-${g.sha256}`} checked={f.id===keep} onChange={()=>setRetained({...retained,[g.sha256]:f.id})}/><span>{t('keep')}<strong>{f.path.split(/[\\/]/).pop()}</strong><small className="path">{f.path}</small></span></label><span>{bytes(f.size)}</span>{f.id!==keep&&<button disabled={busy||report.state!=='completed'} onClick={()=>void act(async()=>{const destination=await folder();if(destination)onPlan(await api<Plan>('/quarantine',{file_id:f.id,retained_id:keep,destination}));})}>{t('isolate')}</button>}</div>)}</div>;})}</>}{error&&<p className="error-text" role="alert">{error}</p>}</section>;
}
