import type {WorkEditionSummary} from './useWorkAssets';
import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,bytes,type Work,type Resource,type Root,type WorkPreference} from './api';
import {editionResources,resourceStates} from './editionAvailability';
export function EditionComparison({work,editions,resources,roots,readOnly,onPreferenceChanged}:{work:Work;editions:WorkEditionSummary[];resources:Resource[];roots:Root[];readOnly:boolean;onPreferenceChanged:(value:WorkPreference)=>Promise<void>}){
 const {t}=useTranslation();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const related=editions.filter(e=>e.work_id===work.id);const preferred=editions.find(e=>e.id===work.preferred_release_id);const preferredResources=preferred?editionResources(work.id,preferred.id,resources,roots):null;
 const choose=async(release_id:string|null)=>{setBusy(true);setError('');try{const saved=await api<WorkPreference>(`/works/${work.id}/preferred-edition`,{revision:work.revision,release_id});await onPreferenceChanged(saved);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <div className="edition-comparison"><div className="preferred-summary"><div><strong>{t('preferredEdition')}: {preferred?.label||(work.preferred_release_id?t('unknown'):t('noPreferredEdition'))}</strong><p>{t('preferredEditionHint')}</p>{work.preferred_release_id&&(!preferredResources||preferredResources.available===0)&&<p className="preference-unavailable">{t('preferredUnavailable')}</p>}</div>{!readOnly&&work.preferred_release_id&&<button disabled={busy} onClick={()=>void choose(null)}>{t('clearPreferredEdition')}</button>}</div>{related.length>0&&<details><summary>{t('compareEditions',{count:related.length})}</summary><p>{t('comparisonEvidenceHint')}</p><div className="edition-compare-grid">{related.map(e=>{const summary=editionResources(work.id,e.id,resources,roots);return <article className="edition-compare-card" key={e.id}><h3>{e.label}</h3>{e.id===work.preferred_release_id&&<span className="pill">{t('preferredEdition')}</span>}<dl><dt>{t('comparisonLanguages')}</dt><dd>{e.languages.join(', ')||t('unknown')}</dd><dt>{t('comparisonPlatforms')}</dt><dd>{e.platforms?.join(', ')||t('unknown')}</dd><dt>{t('released')}</dt><dd>{e.released_date||t('unknown')}</dd><dt>{t('editionType')}</dt><dd>{t(e.edition_type?'editionType_'+e.edition_type:'unknown')}</dd><dt>{t('editionOrigin')}</dt><dd>{t(e.origin?'editionOrigin_'+e.origin:'unknown')}</dd><dt>{t('indexedResources')}</dt><dd>{t('editionAvailableCount',{available:summary.available,total:summary.members.length})} · {bytes(summary.bytes)}</dd><dt>{t('role_patch')}</dt><dd>{summary.patches}</dd></dl>{e.work_count>1&&<p>{t('sharedEdition',{count:e.work_count})}</p>}{e.notes&&<p className="edition-notes">{e.notes}</p>}{summary.members.map(r=><div className="comparison-resource" key={r.id}><strong>{r.title}</strong><small>{roots.find(root=>root.id===r.root_id)?.label||t('unknown')} · {t('resourceKind_'+r.kind,{defaultValue:r.kind})} · {bytes(r.bytes)}</small><small>{resourceStates(r,roots).map(state=>t('resourceState_'+state)).join(' · ')}</small></div>)}{!readOnly&&e.id!==work.preferred_release_id&&<button disabled={busy} aria-label={t('preferNamedEdition',{edition:e.label})} onClick={()=>void choose(e.id)}>{t('usePreferredEdition')}</button>}</article>;})}</div></details>}{error&&<p className="error-text" role="alert">{error}</p>}</div>;
}
