import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
type Tag={id:string;name:string;revision:number};
export function EntityTags({id,canWrite}:{id:string;canWrite:boolean}){
 const {t}=useTranslation(),gate=useRef(false),receipt=useRef({key:'',id:''});
 const [tags,setTags]=useState<Tag[]>([]),[options,setOptions]=useState<Tag[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const [assigned,all]=await Promise.all([api<Tag[]>(`/entity-tags/${encodeURIComponent(id)}`),canWrite?api<Tag[]>('/custom-tags'):Promise.resolve([])]);setTags(assigned);setOptions(all);}
 useEffect(()=>{let live=true;setTags([]);setOptions([]);setError('');setSelected('');void Promise.all([api<Tag[]>(`/entity-tags/${encodeURIComponent(id)}`),canWrite?api<Tag[]>('/custom-tags'):Promise.resolve([])]).then(([assigned,all])=>{if(live){setTags(assigned);setOptions(all);}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[id,canWrite]);
 async function change(tag:Tag,assigned:boolean){if(gate.current)return;gate.current=true;setBusy(true);setError('');const body={tag_id:tag.id,revision:tag.revision,assigned},key=JSON.stringify([id,body]);if(receipt.current.key!==key)receipt.current={key,id:crypto.randomUUID()};try{await api(`/entity-tags/${encodeURIComponent(id)}`,{...body,request_id:receipt.current.id});receipt.current={key:'',id:''};await load();setSelected('');}catch(e){setError(String(e));}finally{gate.current=false;setBusy(false);}}
 return <section className="section entity-tags"><h2>{t('entityPersonalTags')}</h2>{error&&<p role="alert">{error} <button disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(String(e)))}>{t('retry')}</button></p>}<div className="tag-list">{tags.map(tag=><span className="pill" key={tag.id}>{tag.name}{canWrite&&<button disabled={busy} aria-label={t('entityRemoveTag',{name:tag.name})} onClick={()=>void change(tag,false)}>×</button>}</span>)}</div>{canWrite&&<div className="inline"><select aria-label={t('entityPersonalTags')} disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t('entityChooseTag')}</option>{options.filter(tag=>!tags.some(assigned=>assigned.id===tag.id)).map(tag=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button disabled={busy||!selected} onClick={()=>{const tag=options.find(tag=>tag.id===selected);if(tag)void change(tag,true);}}>{t('entityAssignTag')}</button></div>}</section>;
}
