import {useEffect,useRef,useState} from 'react';import {useTranslation} from 'react-i18next';import {api} from './api';import {relationshipsChanged} from './relationshipChanges';
type Fields={name:string|null;description:string|null};type Snapshot={revision:number;fields:Fields};type History={items:{revision:number;before:Fields}[];next:number|null};
export function EntityFieldEditor({id,name,description,onClose}:{id:string;name:string;description:string;onClose:()=>void}){
 const {t}=useTranslation(),dialog=useRef<HTMLDialogElement>(null),gate=useRef(false),receipt=useRef({key:'',id:''});const [saved,setSaved]=useState<Snapshot|null>(null),[draft,setDraft]=useState<Fields|null>(null),[history,setHistory]=useState<History>({items:[],next:null}),[busy,setBusy]=useState(true),[error,setError]=useState(''),[review,setReview]=useState(false);
 const base=`/entities/${encodeURIComponent(id)}`;
 async function run(action:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(String(e));}finally{gate.current=false;setBusy(false);}}
 async function load(){const [data,entries]=await Promise.all([api<Snapshot>(base+'/field-decisions'),api<History>(base+'/field-history')]);setSaved(data);setDraft(data.fields);setHistory(entries);setReview(false);receipt.current={key:'',id:''};}
 useEffect(()=>{dialog.current?.showModal();void run(load);},[]);
 const changed=saved&&draft&&JSON.stringify(saved.fields)!==JSON.stringify(draft);const valid=draft&&(draft.name===null||draft.name.trim().length>0);
 async function save(){if(!saved||!draft)return;const body={revision:saved.revision,fields:draft},key=JSON.stringify(body);if(receipt.current.key!==key)receipt.current={key,id:crypto.randomUUID()};await api(base+'/field-decisions',{...body,request_id:receipt.current.id});relationshipsChanged();onClose();}
 return <dialog ref={dialog} className="focus-tag-dialog relationship-editor entity-field-editor" aria-labelledby="entity-edit-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="entity-edit-title">{t('entityEditFields')}</h2><p>{name}</p>{busy&&<p role="status">{t('loading')}</p>}{error&&<p role="alert">{error}<button disabled={busy} onClick={()=>void run(load)}>{t('relationReload')}</button></p>}{draft&&saved&&<>{(['name','description'] as const).map(field=><section key={field}><h3>{t('entityField_'+field)}</h3>{review?<p className="description">{draft[field]===null?t('entityFollowSource'):draft[field]||t('entityEmptyIntroduction')}</p>:<><label className="checkbox-label"><input type="checkbox" checked={draft[field]===null} disabled={busy} onChange={e=>setDraft({...draft,[field]:e.target.checked?null:field==='name'?name:description})}/>{t('entityFollowSource')}</label>{field==='name'?<input aria-label={t('entityField_name')} maxLength={300} disabled={busy||draft.name===null} value={draft.name??name} onChange={e=>setDraft({...draft,name:e.target.value})}/>:<textarea aria-label={t('entityField_description')} rows={6} maxLength={20000} disabled={busy||draft.description===null} value={draft.description??description} onChange={e=>setDraft({...draft,description:e.target.value})}/>}</>}</section>)}{!review&&<details><summary>{t('relationHistory')}</summary>{history.items.map(item=><div className="relationship-history" key={item.revision}><span>#{item.revision}</span><button disabled={busy} onClick={()=>setDraft(item.before)}>{t('relationUseBefore')}</button></div>)}{history.next!==null&&<button disabled={busy} onClick={()=>void run(async()=>{const next=await api<History>(base+`/field-history?before=${history.next}`);setHistory({items:[...history.items,...next.items],next:next.next});})}>{t('historyOlder')}</button>}</details>}</>}<footer><button disabled={busy} onClick={onClose}>{t('cancel')}</button>{review?<><button disabled={busy} onClick={()=>setReview(false)}>{t('back')}</button><button disabled={busy||!changed||!valid} className="primary" onClick={()=>void run(save)}>{t('relationSave')}</button></>:<button disabled={busy||!changed||!valid} onClick={()=>setReview(true)}>{t('relationReview')}</button>}</footer></dialog>;
}
