import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,readApi} from './api';
import {relationshipsChanged} from './relationshipChanges';
import {exactIdentity,sameExactKey,type Candidate,type ExactCorrection,type ExactEdge,type ExactEdit,type ExactHistory,type ExactKey,type ExactPreview,type ExactState} from './exactRelationships';
type Props={id:string;onClose:()=>void;onSaved:()=>void};
type Form={id:string;replaces:ExactKey|null;kind:ExactKey['kind'];target:string;character:string;alias:string;role:string;note:string;relation:string;spoiler:string;person:Candidate|null;characterCandidate:Candidate|null};
function emptyForm():Form{return {id:crypto.randomUUID(),replaces:null,kind:'company',target:'',character:'',alias:'',role:'scenario',note:'',relation:'seq',spoiler:'',person:null,characterCandidate:null};}
export function ExactRelationshipEditor({id,onClose,onSaved}:Props){
 const {t}=useTranslation(),dialog=useRef<HTMLDialogElement>(null),controller=useRef<AbortController|null>(null),gate=useRef(false),alive=useRef(true);
 const [restoreRevision,setRestoreRevision]=useState<number|undefined>(),[revealed,setRevealed]=useState(false),[saved,setSaved]=useState<ExactState|null>(null),[draft,setDraft]=useState<ExactCorrection[]>([]),[entries,setEntries]=useState<ExactHistory>({items:[],next:null}),[form,setForm]=useState<Form|null>(null),[review,setReview]=useState<{edit:ExactEdit;value:ExactPreview;history_revision?:number}|null>(null),[busy,setBusy]=useState(false),[writing,setWriting]=useState(false),[error,setError]=useState('');
 const base=`/vns/${encodeURIComponent(id)}/relationship-corrections`;
 useEffect(()=>{alive.current=true;dialog.current?.showModal();return()=>{alive.current=false;controller.current?.abort();};},[]);
 async function run(action:(signal:AbortSignal)=>Promise<void>,write=false){if(gate.current)return;gate.current=true;const ctl=new AbortController();controller.current=ctl;setBusy(true);setWriting(write);setError('');try{await action(ctl.signal);}catch(e){if(alive.current&&!ctl.signal.aborted)setError(String(e));}finally{gate.current=false;if(alive.current){setBusy(false);setWriting(false);}}}
 async function load(signal:AbortSignal){const [state,history]=await Promise.all([readApi<ExactState>(base+'?spoilers=true',signal),readApi<ExactHistory>(base+'/history?spoilers=true',signal)]);if(signal.aborted||!alive.current)return;setSaved(state);setDraft(state.corrections);setRestoreRevision(undefined);setEntries(history);setForm(null);setReview(null);}
 function start(source?:ExactEdge,existing?:ExactCorrection){const link=existing?.link,key=link?.key||source?.key;let f=emptyForm();if(key){f={...f,id:existing?.id||f.id,replaces:existing?existing.replaces:source!.key,kind:key.kind,target:key.id,character:key.kind==='voice'?key.character:'',alias:key.kind==='voice'?String(key.alias):key.kind==='staff'&&key.aid!=null?String(key.aid):'',role:key.kind==='staff'?key.role:'scenario',note:key.kind==='staff'||key.kind==='voice'?key.note:'',relation:key.kind==='work'?key.relation:'seq',spoiler:link?String(link.spoiler):''};}setForm(f);setReview(null);}
 function modify(value:ExactCorrection){setRestoreRevision(undefined);setDraft(rows=>[...rows.filter(row=>row.id!==value.id),value]);setReview(null);setForm(null);}
 function hide(source:ExactEdge){modify({id:crypto.randomUUID(),replaces:source.key,link:null});}
 async function resolve(signal:AbortSignal){if(!form)return;const snapshot=form;const values=await Promise.all([readApi<Candidate>(`/relationship-candidates/${encodeURIComponent(snapshot.target.trim())}?refresh=true`,signal),...(snapshot.kind==='voice'?[readApi<Candidate>(`/relationship-candidates/${encodeURIComponent(snapshot.character.trim())}?refresh=true`,signal)]:[])]);if(signal.aborted||!alive.current)return;const expected={company:'company',character:'character',staff:'person',voice:'person',work:'work'}[snapshot.kind];if(values[0].kind!==expected||values[0].id!==snapshot.target.trim()||(snapshot.kind==='voice'&&(values[1]?.kind!=='character'||values[1].id!==snapshot.character.trim())))throw new Error(t('exactWrongKind'));setForm({...snapshot,person:values[0],characterCandidate:values[1]||null,alias:values[0].aliases?.some(a=>String(a.aid)===snapshot.alias)?snapshot.alias:''});}
 function stage(){if(!form?.person||form.spoiler==='')return;const f=form,person=f.person!,aid=Number(f.alias),needsAlias=f.kind==='staff'||f.kind==='voice';const alias=person.aliases?.find(a=>a.aid===aid);if(needsAlias&&(!f.alias||!alias))return;
 let key:ExactKey;switch(f.kind){case 'staff':key={kind:f.kind,id:person.id,aid,role:f.role,note:f.note};break;case 'voice':if(!f.characterCandidate)return;key={kind:f.kind,id:person.id,character:f.characterCandidate.id,alias:aid,note:f.note};break;case 'work':key={kind:f.kind,id:person.id,relation:f.relation};break;default:key={kind:f.kind,id:person.id};}
 modify({id:f.id,replaces:f.replaces,link:{key,name:needsAlias?alias!.name:person.name,character_name:f.kind==='voice'?f.characterCandidate!.name:null,spoiler:Number(f.spoiler)}});
 }
 async function preview(){if(!saved)return;const edit:ExactEdit={revision:saved.revision,request_id:crypto.randomUUID(),corrections:draft};const value=await api<ExactPreview>(base+'/preview',{edit,spoilers:true,history_revision:restoreRevision});if(alive.current)setReview({edit,value,history_revision:restoreRevision});}
 async function commit(){if(!review)return;await api(base,{edit:review.edit,preview_digest:review.value.preview_digest,spoilers:true,history_revision:review.history_revision});relationshipsChanged();if(alive.current){onSaved();onClose();}}
 const changed=!!saved&&JSON.stringify(saved.corrections)!==JSON.stringify(draft);
 const label=(edge:ExactEdge)=>`${edge.name||edge.key.id}${edge.character_name?' / '+edge.character_name:''}`;
 const edgeList=(rows:ExactEdge[])=><ul className="exact-edges">{rows.map((edge,i)=><li key={i}><strong>{label(edge)}</strong><small>{t('exactKind_'+edge.key.kind)} · {exactIdentity(edge.key)}</small>{edge.local&&<small>{t('exactLocal')} · {t('exactSpoiler_'+(edge.spoiler??2))}</small>}</li>)}</ul>;
 return <dialog ref={dialog} className="focus-tag-dialog relationship-editor exact-editor" aria-labelledby="exact-heading" onCancel={e=>{e.preventDefault();if(!writing)onClose();}}><h2 id="exact-heading">{t('exactTitle')}</h2><p>{t('exactScope')}</p>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{t('loading')}</p>}
 {!revealed?<><p>{t('exactRevealHint')}</p><button className="primary" onClick={()=>{setRevealed(true);void run(load);}}>{t('exactReveal')}</button></>:<>
 {error&&!writing&&<button disabled={busy} onClick={()=>void run(load)}>{t('relationReload')}</button>}
 {saved&&<>{(saved.source_partial||saved.source_unavailable)&&<p role="status">{t('exactIncomplete')}</p>}
 {review?<><h3>{t('relationReview')}</h3>{review.value.shadowed_correction_ids.length>0&&<p role="status">{t('exactShadowed')}</p>}<div className="exact-comparison"><section><h4>{t('exactBefore')}</h4>{edgeList(review.value.before)}</section><section><h4>{t('exactAfter')}</h4>{edgeList(review.value.after)}</section></div></>:<>
 {form?<section className="exact-form"><h3>{t(form.replaces?'exactRebind':'exactAdd')}</h3>{form.replaces&&<p>{t('exactSource')}: {exactIdentity(form.replaces)}</p>}
 <label>{t('exactKind')}<select disabled={busy||!!form.replaces} value={form.kind} onChange={e=>setForm({...emptyForm(),id:form.id,kind:e.target.value as Form['kind']})}>{(['company','character','staff','voice','work'] as const).map(kind=><option key={kind} value={kind}>{t('exactKind_'+kind)}</option>)}</select></label>
 <label>{t('exactTargetId')}<input disabled={busy} value={form.target} maxLength={13} placeholder={form.kind==='company'?'p123':form.kind==='character'?'c123':form.kind==='work'?'v123':'s123'} onChange={e=>setForm({...form,target:e.target.value,person:null,alias:''})}/></label>
 {form.kind==='voice'&&<label>{t('exactCharacterId')}<input disabled={busy} value={form.character} maxLength={13} placeholder="c123" onChange={e=>setForm({...form,character:e.target.value,characterCandidate:null})}/></label>}
 <button disabled={busy||!form.target.trim()||(form.kind==='voice'&&!form.character.trim())} onClick={()=>void run(resolve)}>{t('exactResolve')}</button>
 {form.person&&<div className="exact-candidate"><strong>{form.person.name}</strong><small>{form.person.original} · {form.person.id}</small>{form.characterCandidate&&<p>{form.characterCandidate.name} · {form.characterCandidate.id}</p>}{(form.person.stale||form.characterCandidate?.stale)&&<p role="status">{t('exactCachedCandidate')}</p>}{['staff','voice'].includes(form.kind)&&<label>{t('exactAlias')}<select disabled={busy} value={form.alias} onChange={e=>setForm({...form,alias:e.target.value})}><option value="">{t('exactSelectAlias')}</option>{form.person.aliases?.map(a=><option key={a.aid} value={a.aid}>{a.name}{a.latin?' / '+a.latin:''} · #{a.aid}</option>)}</select></label>}</div>}
 {form.kind==='staff'&&<label>{t('exactRole')}<select disabled={busy} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['scenario','chardesign','art','music','songs','director','staff'].map(role=><option key={role} value={role}>{t('staff_'+role)}</option>)}</select></label>}
 {['staff','voice'].includes(form.kind)&&<label>{t('exactNote')}<input disabled={busy} value={form.note} maxLength={500} onChange={e=>setForm({...form,note:e.target.value})}/></label>}
 {form.kind==='work'&&<label>{t('exactRelation')}<select disabled={busy} value={form.relation} onChange={e=>setForm({...form,relation:e.target.value})}>{['seq','pre','set','alt','char','side','par','ser','fan','orig'].map(relation=><option key={relation} value={relation}>{t('relation_'+relation)}</option>)}</select></label>}
 <label>{t('exactSpoiler')}<select disabled={busy} value={form.spoiler} onChange={e=>setForm({...form,spoiler:e.target.value})}><option value="">{t('exactSelectSpoiler')}</option>{[0,1,2].map(level=><option key={level} value={level}>{t('exactSpoiler_'+level)}</option>)}</select></label>
 <div className="exact-actions"><button disabled={busy} onClick={()=>setForm(null)}>{t('cancel')}</button><button disabled={busy||!form.person||form.spoiler===''||(['staff','voice'].includes(form.kind)&&!form.alias)||(form.kind==='voice'&&!form.characterCandidate)} onClick={stage}>{t('exactStage')}</button></div></section>:<button disabled={busy} onClick={()=>start()}>{t('exactAdd')}</button>}
 <h3>{t('exactSavedDraft')}</h3><ul className="exact-edges">{draft.map(row=><li key={row.id}><strong>{row.link?.name||t('relationHide')}</strong><small>{row.replaces?exactIdentity(row.replaces):t('exactAdd')}{row.link?' → '+exactIdentity(row.link.key):''}</small>{row.link&&<small>{t('exactSpoiler_'+row.link.spoiler)}</small>}<div className="exact-actions">{row.link&&<button disabled={busy} onClick={()=>start(undefined,row)}>{t('edit')}</button>}<button disabled={busy} onClick={()=>{setRestoreRevision(undefined);setDraft(draft.filter(v=>v.id!==row.id));setReview(null);}}>{t('exactRemove')}</button></div></li>)}</ul>
 <details><summary>{t('exactSource')}</summary><ul className="exact-edges">{saved.source.map((edge,i)=><li key={i}><strong>{label(edge)}</strong><small>{t('exactKind_'+edge.key.kind)} · {exactIdentity(edge.key)}</small><div className="exact-actions"><button disabled={busy||draft.some(v=>sameExactKey(v.replaces,edge.key))} onClick={()=>hide(edge)}>{t('exactHideOne')}</button><button disabled={busy||draft.some(v=>sameExactKey(v.replaces,edge.key))} onClick={()=>start(edge)}>{t('exactRebind')}</button></div></li>)}</ul></details>
 <details><summary>{t('relationHistory')}</summary>{entries.items.map(item=><div className="relationship-history" key={item.revision}><span>#{item.revision} · {new Date(item.created*1000).toLocaleString()}</span><button disabled={busy} onClick={()=>{setDraft(item.before);setRestoreRevision(item.revision);setForm(null);setReview(null);}}>{t('relationUseBefore')}</button></div>)}{entries.next!==null&&<button disabled={busy} onClick={()=>void run(async signal=>{const page=await readApi<ExactHistory>(base+`/history?spoilers=true&before=${entries.next}`,signal);if(!signal.aborted&&alive.current)setEntries({items:[...entries.items,...page.items],next:page.next});})}>{t('historyOlder')}</button>}</details>
 </>}</>}
 </>}
 <footer><button disabled={writing} onClick={onClose}>{t('cancel')}</button>{saved&&(review?<><button disabled={busy} onClick={()=>setReview(null)}>{t('back')}</button><button className="primary" disabled={busy} onClick={()=>void run(commit,true)}>{t('relationSave')}</button></>:<button disabled={busy||!changed||!!form} onClick={()=>void run(preview)}>{t('relationReview')}</button>)}</footer></dialog>;
}
