import {ListWorkChoice} from './ListWorkChoice';
import {useWorkAssets} from './useWorkAssets';
import {SplitPrivateReview,type SplitSelection} from './SplitPrivateReview';
import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {X} from 'lucide-react';
import {api,type Work,type Resource} from './api';
export function GroupingEditor({work,onClose,onSaved}:{work:Work;onClose:()=>void;onSaved:()=>Promise<void>}){
 const assets=useWorkAssets(work),{t}=useTranslation();
 if(!assets.data)return <div className="scrim"><aside className="drawer"><button aria-label={t('close')} onClick={onClose}><X/></button>{assets.loading?<p role="status">{t('loading')}</p>:<div role="alert"><p>{assets.error}</p><button onClick={assets.reload}>{t('retry')}</button></div>}</aside></div>;
 return <GroupingForm key={assets.data.work.id+':'+assets.data.work.revision} work={assets.data.work} resources={assets.data.resources} onClose={onClose} onSaved={onSaved}/>;
}
function GroupingForm({work,resources,onClose,onSaved}:{work:Work;resources:Resource[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t}=useTranslation();const [mode,setMode]=useState('merge'),[destination,setDestination]=useState<Work|null>(null),[title,setTitle]=useState(''),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [privateSelection,setPrivateSelection]=useState<SplitSelection|null>(null);
 const members=resources.filter(r=>r.bindings.some(b=>b.work_id===work.id));const moved=mode==='merge'?members:members.filter(r=>selected.includes(r.id));
 const submit=async()=>{setBusy(true);setError('');try{await api(`/works/${work.id}/${mode}`,mode==='merge'?{revision:work.revision,target_id:destination?.id,target_revision:destination?.revision}:{revision:work.revision,title,resources:selected,private:privateSelection});await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <div className="scrim"><aside className="drawer"><button className="drawer-close icon-button" disabled={busy} aria-label={t('close')} onClick={onClose}><X/></button><h2>{t('groupingTitle')}</h2><p>{t('groupingHint')}</p>{!preview?<><label>{t('groupingAction')}<select aria-label={t('groupingAction')} value={mode} onChange={e=>setMode(e.target.value)}><option value="merge">{t('mergeWork')}</option><option value="split">{t('splitWork')}</option></select></label>{mode==='merge'?<ListWorkChoice value={destination} onChange={setDestination} disabled={busy} excludeId={work.id}/>:<><label>{t('newWorkTitle')}<input value={title} onChange={e=>setTitle(e.target.value)}/></label>{members.map(r=><label className="checkbox-label" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/><span>{r.title}<small className="path">{r.path}</small></span></label>)}</>}<footer><button className="primary" disabled={mode==='merge'?!destination:!title.trim()||selected.length===0} onClick={()=>setPreview(true)}>{t('reviewGrouping')}</button></footer></>:<><p><strong>{work.title}</strong> → <strong>{mode==='merge'?destination?.title:title}</strong></p><p>{t(mode==='merge'?'mergePreviewHint':'splitPreviewHint')}</p><p>{t(mode==='merge'?'mergePreferenceHint':'splitPreferenceHint')}</p><p>{moved.length} {t('resources')}</p>{moved.map(r=><p className="path" key={r.id}>{r.release} · {r.path}</p>)}<fieldset disabled={busy} style={{border:0,padding:0}}>{mode==='split'&&<SplitPrivateReview workId={work.id} onChange={setPrivateSelection}/>}</fieldset><footer><button disabled={busy} onClick={()=>{setPrivateSelection(null);setPreview(false);}}>{t('back')}</button><button className="primary" disabled={busy||(mode==='split'&&!privateSelection)} onClick={()=>void submit()}>{t('confirmGrouping')}</button></footer></>}{error&&<p className="error-text" role="alert">{error}</p>}</aside></div>;
}
