import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api} from './api';
type Task={id:string;state:string;message:string;destination:string|null;final_folder:string|null;files:number;extract:boolean;reuse_existing:boolean};
export function IssueTask({id,onClose}:{id:number;onClose:()=>void}){
 const {t}=useTranslation(),dialog=useRef<HTMLDialogElement>(null),sending=useRef(false);const [task,setTask]=useState<Task|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;dialog.current?.showModal();api<Task>(`/issues/${id}/task`).then(x=>{if(active)setTask(x);}).catch(e=>{if(active)setError(e instanceof Error?e.message:String(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[id]);
 async function resume(){if(!task||sending.current)return;sending.current=true;setBusy(true);setError('');try{await api(`/jobs/${encodeURIComponent(task.id)}/resume`,{password:password||undefined});setPassword('');onClose();}catch(e){setPassword('');setError(e instanceof Error?e.message:String(e));}finally{sending.current=false;setBusy(false);}}
 return <dialog ref={dialog} className="match-history-dialog" aria-labelledby="issue-task-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><header><h2 id="issue-task-title">{t('issueTask')}</h2><button disabled={busy} aria-label={t('close')} onClick={onClose}>×</button></header>{task&&<><p>{t(task.state,{defaultValue:task.state})} · {t(task.reuse_existing?'job_reuse':'job_acquire')}</p><p>{task.message}</p><h3>{t('issueTaskTarget')}</h3><p className="path">{task.final_folder||task.destination}</p><p>{t('issueTaskFiles',{count:task.files})}</p><p>{t('issueTaskResumeHint')}</p>{['failed','interrupted','cancelled','paused'].includes(task.state)&&<label>{t('password')}<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label>}</>}{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{t('loading')}</p>}<footer><button disabled={busy} onClick={onClose}>{t('close')}</button>{task&&['failed','interrupted','cancelled','paused'].includes(task.state)&&<button disabled={busy} onClick={()=>void resume()}>{t('resume')}</button>}</footer></dialog>;
}
