import {CachedImage} from './CachedImage';
import {AddToList,type ListMember} from './AddToList';
import {TagManager} from './TagManager';
import {plainDescription} from './exploration';
import {CustomTagForm} from './CustomTagForm';
import {useCollectionPage} from './useCollectionPage';
import {api} from './api';
import {releaseMonth} from './search';
import {useEffect,useMemo,useState,useRef} from 'react';
import {useTranslation} from 'react-i18next';
import {BookOpen,Heart,Plus,ArrowUpRight,Tags,X,Minus,ChevronDown,ChevronRight,Grid2X2,GalleryVerticalEnd,List} from 'lucide-react';
import type {Work} from './api';
import {emptyFilters,titleFor,type Filters} from './library';
const PAGE_SIZE=60;
export function LibraryBrowser({generation,query,setQuery,status,setStatus,safe,canWrite,onAdd,onSource,onSelect,onStudio,titleMode,setTitleMode}:{generation:number;query:string;setQuery:(s:string)=>void;status:string;setStatus:(s:string)=>void;safe:boolean;canWrite:boolean;onAdd:()=>void;onSource:()=>void;onSelect:(w:Work)=>void;onStudio:(w:Work,studio:string)=>void;titleMode:'display'|'original';setTitleMode:(s:'display'|'original')=>void}){
 const [selecting,setSelecting]=useState(false),[selected,setSelected]=useState<string[]>([]);
 const [listScope,setListScope]=useState<ListMember[]|null>(null);
 const [viewMode,setViewMode]=useState<'compact'|'posters'|'details'>(()=>{try{const saved=localStorage.getItem('galroon.collectionView');return saved==='compact'||saved==='details'?saved:'posters';}catch{return 'posters';}});
 const chooseView=(mode:'compact'|'posters'|'details')=>{setViewMode(mode);try{localStorage.setItem('galroon.collectionView',mode);}catch{/* The current view remains usable without storage. */}};
 const {t,i18n}=useTranslation();const [filters,setFilters]=useState<Filters>(emptyFilters),[sort,setSort]=useState('added'),[tagQuery,setTagQuery]=useState(''),[focusOpen,setFocusOpen]=useState(false),[tagsOpen,setTagsOpen]=useState(false),[managingTags,setManagingTags]=useState(false),[creatingTag,setCreatingTag]=useState(false),[tagBusy,setTagBusy]=useState(false),[tagError,setTagError]=useState(''),[scopeBusy,setScopeBusy]=useState(false),[scopeError,setScopeError]=useState('');
 const tagDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(tagsOpen){tagDialog.current?.showModal();tagDialog.current?.querySelector('input')?.focus();}else tagDialog.current?.close();},[tagsOpen]);
 const request={filters,query,status,sort,titleMode,locale:i18n.language};
 const catalog=useCollectionPage(request,generation),result=catalog.data,metadata=result||catalog.metadata;
 const customTags=useMemo(()=>(metadata?.custom_tags||[]).map(tag=>({...tag,work_ids:[]})),[metadata]);
 const tagCounts=new Map(Object.entries(metadata?.tag_counts||{}));
 const options=metadata?.options||{studio:[],year:[],language:[],tag:[]};
 const tagOptions=useMemo(()=>[...customTags.map(tag=>({value:'custom:'+tag.id,label:tag.name})),...options.tag],[customTags,options]);
 const total=metadata?.total,filtered=result?.filtered||0;
 const pages=Math.max(1,Math.ceil(filtered/PAGE_SIZE)),current=catalog.pageIndex,slice=result?.items||[];
 const clear=()=>{setFilters(emptyFilters);setQuery('');setStatus('all');};
 const scopeEpoch=useRef(0);
 useEffect(()=>{scopeEpoch.current++;setScopeError('');},[JSON.stringify(request),generation,selected]);
 useEffect(()=>()=>{scopeEpoch.current++;},[]);
 async function openListScope(ids?:string[]){if(!result||scopeBusy)return;const epoch=++scopeEpoch.current;setScopeBusy(true);setScopeError('');try{const response=await api<{members:ListMember[]}>('/collection/selection',{query:request,view_token:result.view_token,...(ids?{ids}:{})});if(epoch===scopeEpoch.current)setListScope(response.members);}catch(error){if(epoch===scopeEpoch.current)setScopeError(error instanceof Error?error.message:String(error));}finally{setScopeBusy(false);}}
 function openTagEditor(manage:boolean){setTagError('');if(manage)setManagingTags(true);else setCreatingTag(true);}
 return <>
 {listScope&&<AddToList members={listScope} onClose={()=>setListScope(null)}/>}
 {scopeBusy&&<p role="status">{t('loading')}</p>}{scopeError&&<p role="alert">{scopeError}</p>}
  <section className="page-heading"><div className="collection-heading"><h1>{t('myCollection')}</h1><span>{total??'—'} {t('works')}</span></div>{canWrite&&<button className="primary" onClick={onAdd}><Plus size={17}/>{t('addWork')}</button>}</section>
  <div className="collection-browser-tools">{canWrite&&<><button aria-pressed={selecting} onClick={()=>setSelecting(!selecting)}>{t('listSelectWorks')}</button>{selected.length>0&&<><span role="status">{t('listScopeCount',{count:selected.length})}</span><button onClick={()=>setSelected([])}>{t('tagSelectNone')}</button><button disabled={scopeBusy||!result||selected.length>10000} onClick={()=>void openListScope(selected)}>{t('listAddSelected')}</button></>}</>}{canWrite&&<button disabled={scopeBusy||!result||!filtered||filtered>10000} onClick={()=>void openListScope()}>{t('listAddFiltered')}</button>}
   <nav className="collection-tags" aria-label={t('collectionFocus')}>
    <button className={'focus-toggle '+(focusOpen?'selected':'')} aria-expanded={focusOpen} aria-controls="collection-focus-panel" onClick={()=>setFocusOpen(!focusOpen)}>{focusOpen?<ChevronDown size={16}/>:<ChevronRight size={16}/>} {t('focus')}</button>
    <button className={'focus-icon '+(filters.favorites||status==='favorite'?'selected':'')} aria-label={t('favorite')} title={t('favorite')} aria-pressed={Boolean(filters.favorites||status==='favorite')} onClick={()=>{setFilters(previous=>({...previous,favorites:!previous.favorites&&status!=='favorite'}));if(status==='favorite')setStatus('all');}}><Heart size={16} fill={filters.favorites||status==='favorite'?'currentColor':'none'}/></button>
    <button className={'focus-icon '+(filters.tags?.length?'selected':'')} aria-label={t('focusTags')} title={t('focusTags')} aria-haspopup="dialog" onClick={()=>setTagsOpen(true)}><Tags size={16}/></button>
    {status!=='all'&&status!=='favorite'&&<button className="focus-chip selected" aria-label={t('removeFocus',{label:t(status)})} onClick={()=>setStatus('all')}>{t(status)}<X size={13}/></button>}
    {(['studio','year','language','availability'] as const).filter(key=>filters[key]).map(key=>{const label=key==='availability'?t('availability_'+filters[key]):options[key].find(o=>o.value===filters[key])?.label||t('unknown');return <button key={key} className="focus-chip selected" aria-label={t('removeFocus',{label})} onClick={()=>setFilters(previous=>({...previous,[key]:''}))}><span>{t('facet_'+key)}: {label}</span><X size={13}/></button>;})}
    {(filters.tags||[]).map(tag=>{const excluded=filters.excludedTags?.includes(tag)||false,label=tagOptions.find(o=>o.value===tag)?.label||tag;return <span key={tag} className={'focus-tag-chip '+(excluded?'excluded':'included')}>
     <button className="tag-invert" title={t(excluded?'includeTag':'excludeTag',{tag:label})} aria-label={t(excluded?'includeTag':'excludeTag',{tag:label})} onClick={()=>setFilters(previous=>({...previous,excludedTags:excluded?(previous.excludedTags||[]).filter(value=>value!==tag):[...(previous.excludedTags||[]),tag]}))}>{excluded?<Minus size={13}/>:<Plus size={13}/>}<span>{label}</span></button>
     <button className="tag-remove" aria-label={t('removeFocus',{label})} onClick={()=>setFilters(previous=>({...previous,tags:previous.tags?.filter(value=>value!==tag),excludedTags:previous.excludedTags?.filter(value=>value!==tag)}))}><X size={13}/></button>
    </span>;})}
   </nav>
   <div className="library-results">{(query||status!=='all'||Object.values(filters).some(value=>Array.isArray(value)?value.length:Boolean(value)))&&<button className="clear-filters" onClick={clear}>{t('clearFilters')}</button>}<div className="collection-view-switch" role="group" aria-label={t('collectionView')}>{([['compact',Grid2X2],['posters',GalleryVerticalEnd],['details',List]] as const).map(([mode,Icon])=><button key={mode} aria-label={t('view_'+mode)} title={t('view_'+mode)} aria-pressed={viewMode===mode} onClick={()=>chooseView(mode)}><Icon size={17}/></button>)}</div><label>{t('titleDisplay')}<select value={titleMode} onChange={e=>setTitleMode(e.target.value as 'display'|'original')}><option value="display">{t('displayTitle')}</option><option value="original">{t('originalTitleChoice')}</option></select></label><label>{t('sortWorks')}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="added">{t('sortAdded')}</option><option value="title">{t('sortTitle')}</option><option value="newest">{t('sortNewest')}</option><option value="oldest">{t('sortOldest')}</option></select></label></div>
  </div>
  <section id="collection-focus-panel" className="collection-focus-panel" hidden={!focusOpen} aria-label={t('focus')}>
   <div className="focus-facet"><h3>{t('focusStatus')}</h3>{['all','backlog','playing','completed','on_hold','dropped'].map(value=><button key={value} aria-pressed={status===value} onClick={()=>setStatus(status===value?'all':value)}>{t(value)}<span>{metadata?.status_counts[value]??0}</span></button>)}</div>
   {(['studio','year','language'] as const).map(key=><div className="focus-facet" key={key}><h3>{t('facet_'+key)}</h3><select aria-label={t('facet_'+key)} value={filters[key]} onChange={e=>setFilters(previous=>({...previous,[key]:e.target.value}))}><option value="">{t('anyValue')}</option><option value="unknown">{t('unknown')}</option>{options[key].map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>{options[key].slice(0,5).map(option=><button key={option.value} aria-pressed={filters[key]===option.value} onClick={()=>setFilters(previous=>({...previous,[key]:previous[key]===option.value?'':option.value}))}>{option.label}</button>)}</div>)}
   <div className="focus-facet"><h3>{t('facet_availability')}</h3><select aria-label={t('facet_availability')} value={filters.availability} onChange={e=>setFilters(previous=>({...previous,availability:e.target.value}))}><option value="">{t('anyValue')}</option>{['available','missing','unverified','offline','unknown','no_resources'].map(value=><option value={value} key={value}>{t('availability_'+value)}</option>)}</select><p>{t('availabilityFilterHint')}</p></div>
  </section>
  <dialog ref={tagDialog} className="focus-tag-dialog" aria-labelledby="focus-tags-title" onCancel={event=>{if(tagBusy)event.preventDefault();else{setCreatingTag(false);setManagingTags(false);setTagsOpen(false);}}} onClose={()=>{setCreatingTag(false);setManagingTags(false);setTagsOpen(false);}} onClick={event=>{if(!tagBusy&&event.target===event.currentTarget){const box=event.currentTarget.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)setTagsOpen(false);}}}>
   <header><h2 id="focus-tags-title">{t(managingTags?'manageTags':creatingTag?'addCustomTag':'focusTags')}</h2><button className="icon-button" disabled={tagBusy} aria-label={t('close')} onClick={()=>{setCreatingTag(false);setManagingTags(false);setTagsOpen(false);}}><X size={18}/></button></header>
   {managingTags?<TagManager titleMode={titleMode} onChanged={tags=>{catalog.reload();const valid=new Set(tags.map(t=>'custom:'+t.id));setFilters(old=>({...old,tags:old.tags?.filter(x=>!x.startsWith('custom:')||valid.has(x)),excludedTags:old.excludedTags?.filter(x=>!x.startsWith('custom:')||valid.has(x))}));}} onClose={()=>setManagingTags(false)} onBusy={setTagBusy}/>:creatingTag?<CustomTagForm tags={customTags} titleMode={titleMode} onBusy={setTagBusy} onCancel={()=>setCreatingTag(false)} onSaved={tag=>{catalog.reload();setTagQuery(tag.name);setCreatingTag(false);setTagError('');}}/>:<>
    {canWrite&&<button disabled={tagBusy} onClick={()=>void openTagEditor(true)}>{t('manageTags')}</button>}<div className="tag-search-row"><input autoFocus aria-label={t('findTags')} placeholder={t('findTags')} value={tagQuery} onChange={event=>setTagQuery(event.target.value)}/>{canWrite&&<button className="add-custom-tag" disabled={tagBusy} onClick={()=>void openTagEditor(false)}><Plus size={15}/>{t('addCustomTag')}</button>}</div>
    {tagError&&<p className="error-text" role="alert">{tagError}</p>}
    <div className="focus-tag-options">{tagOptions.filter(option=>option.label.toLowerCase().includes(tagQuery.toLowerCase())).map(option=><button type="button" key={option.value} aria-pressed={filters.tags?.includes(option.value)||false} onClick={()=>setFilters(previous=>({...previous,tags:previous.tags?.includes(option.value)?previous.tags.filter(value=>value!==option.value):[...(previous.tags||[]),option.value],excludedTags:(previous.excludedTags||[]).filter(value=>value!==option.value)}))}><span>{option.label}{option.value.startsWith('custom:')&&<small className="tag-kind">{t('customTag')}</small>}</span><small>{tagCounts.get(option.value)||0}</small></button>)}{!tagOptions.some(option=>option.label.toLowerCase().includes(tagQuery.toLowerCase()))&&<p>{t('noTagsFound')}</p>}</div>
    <footer><span>{t('filteredWorks',{count:filtered,total:total??0})}</span><button className="primary" onClick={()=>setTagsOpen(false)}>{t('done')}</button></footer>
   </>}

  </dialog>
  {catalog.loading?<p role="status">{t('loading')}</p>:catalog.error?<div role="alert"><p>{catalog.error}</p><button onClick={catalog.reload}>{t('retry')}</button></div>:total===0?<div className="empty"><BookOpen size={38} strokeWidth={1}/><h2>{t('emptyTitle')}</h2><p>{t('emptyBody')}</p>{canWrite&&<button className="primary" onClick={onSource}>{t('addSource')}<ArrowUpRight size={17}/></button>}</div>:filtered===0?<div className="empty"><BookOpen size={38}/><h2>{t('noResults')}</h2><p>{t('noFilteredWorks')}</p><button onClick={clear}>{t('clearFilters')}</button></div>:<div className={'book-grid collection-view-'+viewMode}>{slice.map((w,index)=><article className="book" key={w.id}>{canWrite&&selecting&&<button className="book-select" aria-label={t('listSelectNamed',{title:titleFor(w,titleMode)})} aria-pressed={selected.includes(w.id)} onClick={()=>setSelected(old=>old.includes(w.id)?old.filter(id=>id!==w.id):[...old,w.id])}>{selected.includes(w.id)?'✓':t('listSelect')}</button>}<button className="book-open" aria-label={t('openWorkNamed',{name:titleFor(w,titleMode)})} onClick={()=>onSelect(w)}><div className={`cover cover-${index%4}`}>{w.cover&&!safe?<CachedImage source={w.cover} fallback={<><span className="cover-number">{String(current*PAGE_SIZE+index+1).padStart(2,'0')}</span><span className="cover-title">{w.original_title}</span><span className="cover-imprint">{t('collectionImprint')}</span></>}/>:<><span className="cover-number">{String(current*PAGE_SIZE+index+1).padStart(2,'0')}</span><span className="cover-title">{w.original_title}</span><span className="cover-imprint">{t('collectionImprint')}</span></>}{w.favorite&&<Heart className="cover-heart" size={17} fill="currentColor"/>}</div></button><div className="book-meta"><h3><button className="metadata-link" onClick={()=>onSelect(w)}>{titleFor(w,titleMode)}</button></h3><p className="book-studios">{w.developer?[...new Set(w.developer.split(/,\s*/).map(name=>name.trim()).filter(Boolean))].map((studio,i)=><span key={studio}>{i>0&&', '}<button className="metadata-link" onClick={()=>onStudio(w,studio)}>{studio}</button></span>):w.original_title}</p><span>{viewMode==='details'?w.released:releaseMonth(w.released)}</span>{viewMode==='details'&&<><p className="book-reading-status">{t(w.status)}</p><p className="book-description">{plainDescription(w.description||'')}</p></>}</div></article>)}</div>}
  {pages>1&&<nav className="library-pagination" aria-label={t('collectionPages')}><button disabled={catalog.loading||current===0} onClick={catalog.previous}>{t('previousPage')}</button><span>{t('pageOf',{page:current+1,pages})}</span><button disabled={catalog.loading||!result?.next} onClick={catalog.next}>{t('nextPage')}</button></nav>}
 </>;
}





