import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,type Resource} from './api';
type Entry={seq:number;revision:number;state:string;job_state:string;created:number;recorded_at:number|null;algorithm_version:number|null;reason:string|null;titles:string[]|null;source:{queries?:string[]}|null;candidates:{id:string;title:string;strength:string|null;reason:string|null;ambiguous:boolean|null}[]};
type Page={items:Entry[];next:number|null};
export function MatchHistory({resource,onClose}:{resource:Pick<Resource,'id'|'title'|'path'>;onClose:()=>void}){
 const {t,i18n}=useTranslation();const dialog=useRef<HTMLDialogElement>(null),generation=useRef(0);const [attempts,setAttempts]=useState(false);const [items,setItems]=useState<Entry[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(cursor:number|null){const current=generation.current;setBusy(true);setError('');try{const page=await api<Page>(`/resources/${encodeURIComponent(resource.id)}/matching-history?attempts=${attempts}${cursor===null?'':`&before=${cursor}`}`);if(current!==generation.current)return;setItems(old=>cursor===null?page.items:[...old,...page.items]);setNext(page.next);}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:String(e));}finally{if(current===generation.current)setBusy(false);}}
 useEffect(()=>{generation.current++;setItems([]);setNext(null);dialog.current?.showModal();void load(null);return()=>{generation.current++;};},[resource.id,attempts]);
 return <dialog className="match-history-dialog" ref={dialog} onCancel={onClose} aria-labelledby="match-history-title"><header><h2 id="match-history-title">{t('matchingHistory')}</h2><button onClick={onClose} aria-label={t('close')}>×</button></header><h3>{resource.title||resource.path}</h3><p>{t('matchingHistoryHint')}</p>
 <div className="inline"><button aria-pressed={!attempts} onClick={()=>setAttempts(false)}>{t('historySequences')}</button><button aria-pressed={attempts} onClick={()=>setAttempts(true)}>{t('historyAttempts')}</button></div>{attempts&&<p>{t('historyAttemptsHint')}</p>}<div className="match-history-items">{items.map(item=><article key={item.seq}><div className="inline"><strong>{t('historyState_'+item.state,{defaultValue:item.state})}</strong><time>{new Date((item.recorded_at??item.created)*1000).toLocaleString(i18n.language)}</time></div><small>{t('historyRevision',{revision:item.revision})}{item.algorithm_version!==null&&` · ${t('historyAlgorithm',{version:item.algorithm_version})}`}</small>{item.reason&&<p>{item.reason}</p>}{item.state==='pending'&&<p>{t('historyJobState',{state:t(item.job_state,{defaultValue:item.job_state})})}</p>}{item.titles?.length? <p>{t('matchSearched')}: {item.titles.join(' · ')}</p>:<p>{t('historyNoSource')}</p>}
 {item.candidates.length>0&&<ul>{item.candidates.map((candidate,i)=><li key={candidate.id+':'+i}><strong>{candidate.title}</strong> <small>{candidate.id}</small><p>{candidate.reason?t('matchReason_'+candidate.reason,{defaultValue:candidate.reason}):t('matchReview')}{candidate.ambiguous&&` · ${t('matchAmbiguous')}`}</p></li>)}</ul>}</article>)}</div>
 {!busy&&!error&&items.length===0&&<p>{t('historyEmpty')}</p>}{busy&&<p role="status">{t('loading')}</p>}{error&&<p role="alert">{error}</p>}<footer>{error?<button disabled={busy} onClick={()=>void load(items.length?next:null)}>{t('retry')}</button>:next!==null&&<button disabled={busy} onClick={()=>void load(next)}>{t('historyOlder')}</button>}<button onClick={onClose}>{t('close')}</button></footer></dialog>;
}
