import {describe,it,expect} from 'vitest';import {mergeProfileCredits} from './profileCredits';import type {Related} from './exploration';
describe('manual profile credit merge',()=>{
 it('keeps complete provider metadata and distinct aliases/duties when manual subset arrives',()=>{const source:Related[]=[{id:'v1',title:'Full title',image:{url:'saved'},staff:[{id:'s1',aid:1,name:'Source alias',role:'scenario'},{id:'s1',aid:2,name:'Another alias',role:'scenario'},{id:'s1',aid:1,name:'Composer',role:'music'}]}];const snapshot=JSON.stringify(source);const manual:Related[]=[{id:'v1',title:'Fallback title',staff:[{id:'s1',aid:1,name:'Corrected alias',role:'scenario'}]}];const merged=mergeProfileCredits(source,manual);expect(merged[0].title).toBe('Full title');expect(merged[0].image).toEqual({url:'saved'});expect(merged[0].staff?.map(v=>v.name)).toEqual(['Corrected alias','Another alias','Composer']);expect(JSON.stringify(source)).toBe(snapshot);expect(mergeProfileCredits(merged,manual)).toEqual(merged);});
 it('retains different voice character/alias/note combinations and adds external works once',()=>{const voice={staff:{id:'s1',aid:1,name:'Voice'},character:{id:'c1',name:'Character'}};const source:Related[]=[{id:'v1',title:'Work',va:[voice]}];const manual:Related[]=[{id:'v1',title:'Work',va:[{...voice,character:{id:'c2',name:'Other character'}},{...voice,note:'Alternate voice'},{...voice,staff:{...voice.staff,aid:2}}]},{id:'v2',title:'External'}];const result=mergeProfileCredits(source,manual);expect(result).toHaveLength(2);expect(result[0].va).toHaveLength(4);expect(mergeProfileCredits(result,manual)).toEqual(result);});
});

it('preserves nested provider metadata when an exact manual credit only supplies labels',()=>{
 const source:Related[]=[{id:'v1',title:'Work',staff:[{id:'s1',aid:1,name:'Old',role:'music',eid:8,image:{url:'cached-staff'}}],va:[{staff:{id:'s1',aid:2,name:'Voice',original:'Original alias'},character:{id:'c1',name:'Character',description:'Saved biography',vns:[{id:'v1',spoiler:0}]}}]}];
 const before=JSON.stringify(source);const result=mergeProfileCredits(source,[{id:'v1',title:'Fallback',staff:[{id:'s1',aid:1,name:'New',role:'music'}],va:[{staff:{id:'s1',aid:2,name:'New voice'},character:{id:'c1',name:'New character'}}]}]);
 expect(result[0].staff?.[0]).toMatchObject({name:'New',eid:8,image:{url:'cached-staff'}});expect(result[0].va?.[0].staff.original).toBe('Original alias');expect(result[0].va?.[0].character.description).toBe('Saved biography');expect(JSON.stringify(source)).toBe(before);
});
