import {describe,it,expect,vi,beforeEach} from 'vitest';
vi.mock('./api',()=>({readApi:vi.fn()}));
import {readApi} from './api';
import {collectMatchingMemberIds,memberPagePath,type MemberPage} from './resourceMemberSelection';
const pin={library_id:'library',catalog_revision:7};
function page(offset:number,total=125):MemberPage{return {source:{id:'source',root_id:'root',title:'Source',revision:1},...pin,offset,total,file_count:total,items:Array.from({length:Math.min(60,total-offset)},(_,i)=>({id:'f'+(offset+i),relative:'Game/'+(offset+i),size:1,availability:'present'})),next:offset+60<total?'cursor'+(offset+60):null};}
beforeEach(()=>vi.mocked(readApi).mockReset());
describe('matching member collection',()=>{
 it('collects every page with the same query and pinned identity',async()=>{vi.mocked(readApi).mockResolvedValueOnce(page(0)).mockResolvedValueOnce(page(60)).mockResolvedValueOnce(page(120));const progress=vi.fn();const ids=await collectMatchingMemberIds('source','資料',pin,new AbortController().signal,progress);expect(ids).toEqual(Array.from({length:125},(_,i)=>'f'+i));expect(progress.mock.calls).toEqual([[60,125],[120,125],[125,125]]);for(const [path] of vi.mocked(readApi).mock.calls){const u=new URL(String(path),'http://fixture');expect(u.searchParams.get('query')).toBe('資料');expect(u.searchParams.get('catalog_revision')).toBe('7');expect(u.searchParams.get('library_id')).toBe('library');}});
 it('cancels between pages without requesting or returning a partial selection',async()=>{const c=new AbortController();vi.mocked(readApi).mockResolvedValueOnce(page(0));await expect(collectMatchingMemberIds('source','',pin,c.signal,()=>c.abort())).rejects.toThrow();expect(readApi).toHaveBeenCalledTimes(1);});
 it('rejects a response arriving after cancellation',async()=>{const c=new AbortController();vi.mocked(readApi).mockImplementationOnce(async()=>{c.abort();return page(0);});await expect(collectMatchingMemberIds('source','',pin,c.signal)).rejects.toThrow();});
 it('rejects stale or foreign pages',async()=>{for(const extra of [{library_id:'other'},{catalog_revision:8},{source:{...page(0).source,id:'other'}}]){vi.mocked(readApi).mockResolvedValueOnce({...page(0),...extra});await expect(collectMatchingMemberIds('source','',pin,new AbortController().signal)).rejects.toThrow('changed');}});
 it('rejects missing and repeated members',async()=>{vi.mocked(readApi).mockResolvedValueOnce({...page(0),next:null});await expect(collectMatchingMemberIds('source','',pin,new AbortController().signal)).rejects.toThrow('changed');vi.mocked(readApi).mockResolvedValueOnce(page(0)).mockResolvedValueOnce({...page(60),items:page(0).items});await expect(collectMatchingMemberIds('source','',pin,new AbortController().signal)).rejects.toThrow('Repeated');});
 it('propagates a later read failure without a partial result',async()=>{vi.mocked(readApi).mockResolvedValueOnce(page(0)).mockRejectedValueOnce(Error('Unavailable'));await expect(collectMatchingMemberIds('source','',pin,new AbortController().signal)).rejects.toThrow('Unavailable');});
 it('handles no matching files and escapes a source identity',async()=>{vi.mocked(readApi).mockResolvedValueOnce(page(0,0));expect(await collectMatchingMemberIds('source','',pin,new AbortController().signal)).toEqual([]);expect(memberPagePath('a/b','')).toBe('/resources/a%2Fb/members/page?query=');});
});
