import {useTranslation} from 'react-i18next';
import {newCondition,type Rule,type Predicate} from './smartLists';
export type Options=Record<string,{id:string;name:string}[]>;
const available=['status','favorite','organizing_state','personal_tags','source_locations','matching_state','source_tags','brands','people','person_roles','characters'];
const unavailable:string[]=[];
export function SmartRuleEditor({rule,onChange,options,depth=0}:{rule:Rule;onChange:(rule:Rule)=>void;options:Options;depth?:number}){
 const {t}=useTranslation();
 const flag=(key:'exclude'|'include_unknown',value:boolean,change:(v:boolean)=>void)=><label className="checkbox-label"><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/>{t('smart_'+key)}</label>;
 function predicate(p:Predicate,change:(p:Predicate)=>void,edition=false){const fields=edition?['confirmed_languages','platforms','availability']:available;return <div className={'smart-predicate'+(p.field==='organizing_state'?' smart-organization-predicate':'')}><label>{t('smartField')}<select aria-label={t('smartField')} value={p.field} onChange={e=>change({...p,field:e.target.value,values:[]})}>{fields.map(f=><option key={f} value={f}>{t('smartField_'+f)}</option>)}{!edition&&unavailable.map(f=><option disabled key={f} value={f}>{t('smartField_'+f)} · {t('smartUnavailable')}</option>)}</select></label><label>{t('smartMode')}<select aria-label={t('smartMode')} value={p.mode} onChange={e=>change({...p,mode:e.target.value as Predicate['mode']})}>{['any','all','none'].map(v=><option key={v} value={v}>{t('smartMode_'+v)}</option>)}</select></label><label>{t('smartValues')}<select multiple aria-label={t('smartValues')} value={p.values} onChange={e=>change({...p,values:Array.from(e.target.selectedOptions,o=>o.value)})}>{(options[p.field]||[]).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}{p.values.filter(id=>!options[p.field]?.some(o=>o.id===id)).map(id=><option key={id} value={id}>{t('smartUnavailableValue')}</option>)}</select></label>{p.field==='organizing_state'&&<p className="muted smart-organization-hint">{t('smartOrganizationHint')}</p>}{flag('exclude',p.exclude,v=>change({...p,exclude:v}))}{flag('include_unknown',p.include_unknown,v=>change({...p,include_unknown:v}))}</div>;}
 if(rule.kind==='group')return <fieldset className="smart-group"><legend>{t('smartGroup')}</legend><label>{t('smartMatch')}<select aria-label={t('smartMatch')} value={rule.join} onChange={e=>onChange({...rule,join:e.target.value as 'all'|'any'})}><option value="all">{t('smartAll')}</option><option value="any">{t('smartAny')}</option></select></label>{rule.children.map((child,index)=><div className="smart-rule" key={index}><SmartRuleEditor rule={child} options={options} depth={depth+1} onChange={next=>onChange({...rule,children:rule.children.map((v,i)=>i===index?next:v)})}/><button type="button" disabled={rule.children.length===1} onClick={()=>onChange({...rule,children:rule.children.filter((_,i)=>i!==index)})}>{t('smartRemoveCondition')}</button></div>)}<div className="inline"><button type="button" onClick={()=>onChange({...rule,children:[...rule.children,newCondition()]})}>{t('smartAddCondition')}</button>{depth===0&&<button type="button" onClick={()=>onChange({...rule,children:[...rule.children,{kind:'group',join:'any',children:[newCondition()]}]})}>{t('smartAddGroup')}</button>}</div></fieldset>;
 return <div><label>{t('smartCondition')}<select aria-label={t('smartCondition')} value={rule.kind} onChange={e=>onChange(e.target.value==='year'?{kind:'year',from:2000,to:2026,exclude:false,include_unknown:false}:e.target.value==='edition'?{kind:'edition',join:'all',conditions:[{field:'confirmed_languages',mode:'any',values:[],exclude:false,include_unknown:false}],exclude:false,include_unknown:false}:newCondition())}><option value="field">{t('smartWorkField')}</option><option value="year">{t('smartYear')}</option><option value="edition">{t('smartSameEdition')}</option></select></label>{rule.kind==='field'?predicate(rule.predicate,p=>onChange({...rule,predicate:p})):rule.kind==='year'?<><div className="inline"><label>{t('smartFrom')}<input type="number" min={1} max={9999} value={rule.from} onChange={e=>onChange({...rule,from:Number(e.target.value)})}/></label><label>{t('smartTo')}<input type="number" min={1} max={9999} value={rule.to} onChange={e=>onChange({...rule,to:Number(e.target.value)})}/></label></div>{flag('exclude',rule.exclude,v=>onChange({...rule,exclude:v}))}{flag('include_unknown',rule.include_unknown,v=>onChange({...rule,include_unknown:v}))}</>:<><label>{t('smartMatch')}<select aria-label={t('smartMatch')} value={rule.join} onChange={e=>onChange({...rule,join:e.target.value as 'all'|'any'})}><option value="all">{t('smartAll')}</option><option value="any">{t('smartAny')}</option></select></label>{rule.conditions.map((p,index)=><div className="smart-rule" key={index}>{predicate(p,next=>onChange({...rule,conditions:rule.conditions.map((v,i)=>i===index?next:v)}),true)}<button type="button" disabled={rule.conditions.length===1} onClick={()=>onChange({...rule,conditions:rule.conditions.filter((_,i)=>i!==index)})}>{t('smartRemoveCondition')}</button></div>)}<button type="button" onClick={()=>onChange({...rule,conditions:[...rule.conditions,{field:'availability',mode:'any',values:[],exclude:false,include_unknown:false}]})}>{t('smartAddCondition')}</button>{flag('exclude',rule.exclude,v=>onChange({...rule,exclude:v}))}{flag('include_unknown',rule.include_unknown,v=>onChange({...rule,include_unknown:v}))}</>}</div>;
}
