import {SmartRulePreview} from './SmartRulePreview';
import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,computeRules} from './api';
import {SmartRuleEditor,type Options} from './SmartRuleEditor';
import {summarizeRule,newDefinition,type SmartList,type SmartResult} from './smartLists';
export function SmartListsPanel({canWrite,onOpen}:{canWrite:boolean;onOpen?:(key:string,title:string)=>void}){
 const {t}=useTranslation(),gate=useRef(false),receipt=useRef({key:'',id:''});
 const computation=useRef<AbortController|null>(null);
 const [computing,setComputing]=useState(false);
 useEffect(()=>()=>computation.current?.abort(),[]);
 const [rows,setRows]=useState<SmartList[]>([]),[next,setNext]=useState<string|null>(null),[detail,setDetail]=useState<SmartList|null>(null),[result,setResult]=useState<SmartResult|null>(null),[draft,setDraft]=useState<SmartList|null>(null),[conversion,setConversion]=useState<{snapshot:string;total:number;name:string}|null>(null),[deleting,setDeleting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[options,setOptions]=useState<Options>({});
 async function run(fn:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{gate.current=false;setBusy(false);}}
 async function index(after?:string){const p=await api<{lists:SmartList[];next_after:string|null}>(`/smart-lists?include_deleted=${canWrite}${after?'&after='+encodeURIComponent(after):''}`);setRows(old=>after?[...old,...p.lists]:p.lists);setNext(p.next_after);}
 async function open(id:string){const [d,r]=await Promise.all([api<SmartList>(`/smart-lists/${encodeURIComponent(id)}`),api<SmartResult>(`/smart-lists/${encodeURIComponent(id)}/results`)]);setDetail(d);setResult(r);setNotice('');}
 async function post(path:string,body:object){const key=JSON.stringify([path,body]);if(receipt.current.key!==key)receipt.current={key,id:crypto.randomUUID()};const r=await api<any>(path,{...body,request_id:receipt.current.id});receipt.current={key:'',id:''};return r;}
 async function compute(){if(!detail)return;const controller=new AbortController();computation.current=controller;setComputing(true);setNotice('');
  const path=`/smart-lists/${detail.id}/compute`,body={revision:detail.revision},key=JSON.stringify([path,body]);
  if(receipt.current.key!==key)receipt.current={key,id:crypto.randomUUID()};
  try{const computed=await computeRules<{snapshot:string}>(detail.id,{...body,request_id:receipt.current.id},controller.signal);
   if(controller.signal.aborted)return;
   const fresh=await api<SmartResult>(`/smart-lists/${detail.id}/results?snapshot=${encodeURIComponent(computed.snapshot)}`);
   if(controller.signal.aborted)return;
   setResult(fresh);receipt.current={key:'',id:''};
  }catch(e){if(!controller.signal.aborted)throw e;}finally{if(computation.current===controller){computation.current=null;setComputing(false);}}
 }
 function cancelCompute(){computation.current?.abort();setNotice(t('smartComputeCancelled'));}
 useEffect(()=>{void run(async()=>{await index();const [tags,roots,relations]=await Promise.all([api<{id:string;name:string}[]>('/custom-tags'),api<{id:string;label:string}[]>('/roots'),api<Options>('/smart-lists/options')]);const values=(field:string,ids:string[])=>ids.map(id=>({id,name:t(field+id,{defaultValue:id})}));setOptions({...relations,personal_tags:tags,related_personal_tags:tags,source_locations:roots.map(r=>({id:r.id,name:r.label})),status:values('',['backlog','playing','completed','on_hold','dropped']),favorite:values('smartFavorite_',['true','false']),organizing_state:values('smartOrganization_',['organized','unorganized','pending','partial']),matching_state:values('smartState_',['matched','unmatched']),confirmed_languages:values('smartLanguage_',['ja','en','zh','zh-Hans','zh-Hant','ko','fr','de','es','ru']),platforms:values('',['Windows','Linux','macOS']),availability:values('smartState_',['available','offline','missing','unverified'])});});},[]);
 useEffect(()=>{if(!detail||draft||conversion||deleting)return;let live=true;const timer=setInterval(()=>{if(gate.current)return;void api<SmartResult>(`/smart-lists/${encodeURIComponent(detail.id)}/results${result?.snapshot?'?snapshot='+encodeURIComponent(result.snapshot):''}`).then(fresh=>{if(live)setResult(old=>old?{...old,needs_repair:fresh.needs_repair,update_pending:fresh.update_pending,update_error:fresh.update_error,definition_changed:fresh.definition_changed,newer_available:fresh.newer_available||(!old.computed&&fresh.computed)}:fresh);}).catch(()=>{if(live)setNotice(t('smartUpdatesOffline'));});},5000);return()=>{live=false;clearInterval(timer);};},[detail?.id,result?.snapshot,draft,conversion,deleting,t]);
 return <section className="lists-page"><header className="section-heading"><h1>{t('smartLists')}</h1><button disabled={busy||!!draft||!!conversion||deleting} onClick={()=>void run(()=>detail?open(detail.id):index())}>{t('refreshView')}</button></header>{busy&&<p role="status">{t('loading')}</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {draft?<form onSubmit={e=>{e.preventDefault();void run(async()=>{await post(`/smart-lists/${draft.id}`,{revision:draft.revision,edit:{action:'save',name:draft.name,description:draft.description,pinned:draft.pinned,definition:draft.definition}});setDraft(null);await open(draft.id);await index();});}}><fieldset disabled={busy} className="smart-editor"><label>{t('listName')}<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t('smartDescription')}<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={draft.pinned} onChange={e=>setDraft({...draft,pinned:e.target.checked})}/>{t('smartPin')}</label><div className="inline"><label>{t('smartScope')}<select aria-label={t('smartScope')} value={draft.definition.scope} onChange={e=>setDraft({...draft,definition:{...draft.definition,scope:e.target.value as 'collection'|'stored_references'}})}><option value="collection">{t('smartCollection')}</option><option value="stored_references">{t('smartReferences')}</option></select></label><label>{t('smartSort')}<select value={draft.definition.sort} onChange={e=>setDraft({...draft,definition:{...draft.definition,sort:e.target.value as 'title'|'year'}})}><option value="title">{t('smartTitle')}</option><option value="year">{t('smartYear')}</option></select></label><label className="checkbox-label"><input type="checkbox" checked={draft.definition.descending} onChange={e=>setDraft({...draft,definition:{...draft.definition,descending:e.target.checked}})}/>{t('smartDescending')}</label></div><p className="smart-rule-summary">{summarizeRule(draft.definition.rule,t,options)}</p><SmartRuleEditor rule={draft.definition.rule} options={options} onChange={rule=>setDraft({...draft,definition:{...draft.definition,rule}})}/><SmartRulePreview definition={draft.definition}/><div className="inline"><button type="button" onClick={()=>setDraft(null)}>{t('cancel')}</button><button type="submit">{t('smartSave')}</button></div></fieldset></form>:conversion?<section><h2>{t('smartConvert')}</h2><p>{t('smartConvertCount',{count:conversion.total})}</p><label>{t('listName')}<input disabled={busy} value={conversion.name} onChange={e=>setConversion({...conversion,name:e.target.value})}/></label><div className="inline"><button disabled={busy} onClick={()=>setConversion(null)}>{t('cancel')}</button><button disabled={busy||!conversion.name.trim()} onClick={()=>void run(async()=>{await post(`/smart-lists/${detail!.id}/to-manual`,{snapshot:conversion.snapshot,expected_total:conversion.total,name:conversion.name});setConversion(null);setNotice(t('smartConverted'));})}>{t('smartConfirmConvert')}</button></div></section>:detail?<>
 <button disabled={busy} onClick={()=>{setDetail(null);setResult(null);void run(()=>index());}}>{t('back')}</button><h2>{detail.name} <small>{t('smartBadge')}</small></h2><p>{detail.description}</p><p className="smart-rule-summary">{summarizeRule(detail.definition.rule,t,options)}</p>{(detail.needs_repair||result?.needs_repair)&&<p role="alert">{t('smartRepair')}</p>}{result?.definition_changed&&<p role="status">{t('smartDefinitionChanged')}</p>}
 {canWrite&&<div className="inline">{detail.deleted?<button disabled={busy} onClick={()=>void run(async()=>{await post(`/smart-lists/${detail.id}`,{revision:detail.revision,edit:{action:'restore'}});await open(detail.id);})}>{t('restore')}</button>:<><button disabled={busy} onClick={()=>setDraft(structuredClone(detail))}>{t('smartEdit')}</button><button disabled={busy||detail.needs_repair} onClick={()=>void run(compute)}>{t('smartCompute')}</button>{computing&&<button onClick={cancelCompute}>{t('smartCancelCompute')}</button>}<button disabled={busy||!result?.computed||result.needs_repair||result.definition_changed} onClick={()=>setConversion({snapshot:result!.snapshot!,total:result!.total!,name:detail.name})}>{t('smartConvert')}</button><button disabled={busy} onClick={()=>setDeleting(true)}>{t('smartDelete')}</button></>}</div>}
 {deleting&&<section><p>{t('smartDeleteConfirm',{name:detail.name})}</p><button disabled={busy} onClick={()=>setDeleting(false)}>{t('cancel')}</button><button disabled={busy} onClick={()=>void run(async()=>{await post(`/smart-lists/${detail.id}`,{revision:detail.revision,edit:{action:'delete'}});setDeleting(false);await open(detail.id);})}>{t('smartConfirmDelete')}</button></section>}
 {result?.update_pending&&<p role="status">{t('smartUpdatePending')}</p>}{result?.update_error&&<p role="alert">{result.update_error}</p>}{result?.newer_available&&<p role="status">{t('smartNewResults')} <button disabled={busy} onClick={()=>void run(()=>open(detail.id))}>{t('smartShowNewResults')}</button></p>}
 {!result?.computed?<p>{t('smartNotComputed')}</p>:<><p role="status">{t('smartResultCount',{count:result.total,unknown:result.unknown_count})}</p><p>{t('smartComputedAt',{time:new Date(result.created!*1000).toLocaleString()})}</p><ol className="list-members">{result.entries.map(e=><li key={e.position} value={e.position+1}>{onOpen?<button className="metadata-link" onClick={()=>onOpen(e.work_key,e.title)}>{e.title}</button>:e.title}</li>)}</ol>{result.next_after!=null&&<button disabled={busy} onClick={()=>void run(async()=>{const page=await api<SmartResult>(`/smart-lists/${detail.id}/results?snapshot=${encodeURIComponent(result.snapshot!)}&after=${result.next_after}`);setResult({...page,entries:[...result.entries,...page.entries]});})}>{t('listMore')}</button>}</>}
 </>:<>{canWrite&&<button disabled={busy} onClick={()=>setDraft({id:crypto.randomUUID(),name:'',description:'',pinned:false,revision:0,deleted:false,needs_repair:false,definition:newDefinition()})}>{t('smartCreate')}</button>}<div className="list-index">{rows.map(row=><button key={row.id} disabled={busy} onClick={()=>void run(()=>open(row.id))}><strong>{row.name}</strong><span>{t('smartBadge')}{row.deleted?' · '+t('tagDeleted'):''}</span></button>)}</div>{next&&<button disabled={busy} onClick={()=>void run(()=>index(next))}>{t('listMore')}</button>}</>}
 </section>;
}
