import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {X,FolderOpen} from 'lucide-react';
import {api,folder,isDesktop,type Root} from './api';
type Preview={old_path:string;new_path:string;files:number;found:number;missing:number;changed:number;jobs:number;plans:number;digest:string};
export function SourceRemap({root,onClose,onSaved}:{root:Root;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t}=useTranslation();const [path,setPath]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));setPreview(null);}finally{setBusy(false);}};
 return <div className="scrim"><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="remap-title"><button className="drawer-close" disabled={busy} aria-label={t('close')} onClick={onClose}><X size={18}/></button><h2 id="remap-title">{t('remapSource')}</h2><p>{t('remapHint')}</p><label>{t('from')}<p className="path">{root.path}</p></label><label>{t('newSourcePath')}<input value={path} disabled={busy} onChange={e=>{setPath(e.target.value);setPreview(null);}}/></label><div className="inline">{isDesktop&&<button disabled={busy} onClick={()=>void act(async()=>{const p=await folder();if(p){setPath(p);setPreview(null);}})}><FolderOpen size={16}/>{t('browse')}</button>}<button disabled={busy||!path} onClick={()=>void act(async()=>setPreview(await api<Preview>(`/roots/${root.id}/remap/preview`,{path})))}>{t('reviewMapping')}</button></div>{preview&&<><div className="plan-item"><span>{t('to')}</span><p>{preview.new_path}</p><p>{t('mappingFiles',{total:preview.files,found:preview.found,missing:preview.missing,changed:preview.changed})}</p><p>{t('mappingInvalidates',{jobs:preview.jobs,plans:preview.plans})}</p><p>{t('mappingVerify')}</p></div><footer><button className="primary" disabled={busy} onClick={()=>void act(async()=>{await api(`/roots/${root.id}/remap`,{path,digest:preview.digest});await onSaved();onClose();})}>{t('confirmMapping')}</button></footer></>}{busy&&<p role="status">{t('loading')}</p>}{error&&<p className="error-text" role="alert">{error}</p>}</aside></div>;
}
