import {useTagMembership} from './useTagMembership';
import {TagWorkPicker} from './TagWorkPicker';
import {TagNameWarning} from './TagNameWarning';
import {useEffect,useRef,useState} from 'react';import {useTranslation} from 'react-i18next';import {api} from './api';import {type CustomTag} from './CustomTagForm';
type Tag=Omit<CustomTag,'work_ids'>&{work_count:number;revision:number;deleted:boolean;undo_available?:boolean;entity_count?:number;smart_list_count?:number;impact_revision?:number};
export function TagManager({titleMode,onChanged,onClose,onBusy}:{titleMode:'display'|'original';onChanged:(tags:CustomTag[])=>void;onClose:()=>void;onBusy:(busy:boolean)=>void}){
 const {t}=useTranslation(),request=useRef({key:'',id:''}),sending=useRef(false);const [tags,setTags]=useState<Tag[]>([]),[id,setId]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[rename,setRename]=useState<{tag:Tag;name:string}|null>(null),[deletion,setDeletion]=useState<Tag|null>(null);const tag=tags.find(t=>t.id===id);const coverage=useTagMembership(tag,selected);
 async function load(){const rows=await api<Tag[]>('/custom-tags?include_deleted=true&summary=true');setTags(rows);setId(old=>rows.some(t=>t.id===old)?old:rows[0]?.id||'');onChanged(rows.filter(t=>!t.deleted).map(t=>({...t,work_ids:[]})));}
 useEffect(()=>{void load().catch(e=>setError(String(e)));},[]);
 async function edit(action:string){const target=action==='delete'?deletion:action==='rename'?rename?.tag:tag;if(!target||sending.current)return;const body={...(action==='delete'?{impact_revision:target.impact_revision}:{}),...(action==='rename'?{name:rename?.name}:{}),revision:target.revision,action,work_ids:['add','remove'].includes(action)?[...selected].sort():[]};const key=JSON.stringify([target.id,body]);if(request.current.key!==key)request.current={key,id:crypto.randomUUID()};sending.current=true;setBusy(true);onBusy(true);setError('');setNotice('');try{const result=await api<{batch?:{processed:number;changed:number;unchanged:number;failed:number}}>(`/custom-tags/${target.id}`,{...body,request_id:request.current.id});setNotice(result.batch?t('tagBatchResult',result.batch):t('tagEditSaved'));await load();setDeletion(null);setRename(null);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{sending.current=false;setBusy(false);onBusy(false);}}
 return <section className="custom-tag-form">{rename?<section><label>{t('tagNewName')}<input autoFocus maxLength={80} disabled={busy} value={rename.name} onChange={e=>setRename({...rename,name:e.target.value})}/></label><TagNameWarning name={rename.name} tags={tags} excludeId={rename.tag.id}/><div className="inline"><button disabled={busy} onClick={()=>setRename(null)}>{t('cancel')}</button><button disabled={busy||!rename.name.trim()} onClick={()=>void edit('rename')}>{t('tagSaveName')}</button></div></section>:deletion?<section aria-label={t('tagDeletePreview')}><h3>{t('tagDeletePreview')}</h3><p>{t('tagDeleteImpact',{name:deletion.name,count:deletion.work_count})}</p>{deletion.entity_count!=null&&deletion.smart_list_count!=null&&deletion.impact_revision!=null?<><p>{t('tagDeleteEntities',{count:deletion.entity_count})}</p><p>{t('tagDeleteSmartLists',{count:deletion.smart_list_count})}</p></>:<p role="alert">{t('tagImpactUnavailable')}</p>}<p>{t('tagDeleteRecovery')}</p><div className="inline"><button disabled={busy} onClick={()=>setDeletion(null)}>{t('cancel')}</button><button disabled={busy||deletion.entity_count==null||deletion.smart_list_count==null||deletion.impact_revision==null} onClick={()=>void edit('delete')}>{t('tagConfirmDelete')}</button></div></section>:<><label>{t('customTagName')}<select disabled={busy} value={id} onChange={e=>setId(e.target.value)}>{tags.map(tag=><option key={tag.id} value={tag.id}>{tag.name}{tag.deleted?' · '+t('tagDeleted'):''}</option>)}</select></label><button disabled={busy} onClick={()=>void load().catch(e=>setError(String(e)))}>{t('refreshView')}</button>{tag&&<>{tag.undo_available&&<button disabled={busy} onClick={()=>void edit('undo')}>{t('tagUndo')}</button>}{!tag.deleted&&<button disabled={busy} onClick={()=>setRename({tag:{...tag},name:tag.name})}>{t('tagRename')}</button>}{coverage.error?<p role="alert">{coverage.error}</p>:coverage.loading?<p role="status">{t('loading')}</p>:<p>{t('tagCoverage',{count:coverage.members.length,total:selected.length})}</p>}{!tag.deleted&&<><TagWorkPicker selected={selected} onChange={setSelected} titleMode={titleMode} disabled={busy} tag={tag}/><div className="inline"><button disabled={busy||!selected.length} onClick={()=>void edit('add')}>{t('tagAddSelected')}</button><button disabled={busy||!selected.length} onClick={()=>void edit('remove')}>{t('tagRemoveSelected')}</button></div></>}<button disabled={busy} onClick={()=>tag.deleted?void edit('restore'):setDeletion({...tag})}>{t(tag.deleted?'tagRestore':'tagDelete')}</button></>}</>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}<footer><button disabled={busy} onClick={onClose}>{t('done')}</button></footer></section>;
}
