import {TaskMessages} from './TaskMessages';
import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {api,bytes,type Job,type Plan} from './api';
type Entry={seq:number;job_id:string;code:string;created:number;details:Record<string,string|number|boolean|null>};
type Page={items:Entry[];next:number|null};
export function Timeline({onPlan}:{onPlan?:(plan:Plan)=>void}){const {t,i18n}=useTranslation(),generation=useRef(0);const [items,setItems]=useState<Entry[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [task,setTask]=useState<Job|null>(null),[selectedTask,setSelectedTask]=useState<number|null>(null);
 const detailGeneration=useRef(0);
 async function openPlan(id:string){const gen=++detailGeneration.current;setBusy(true);setError('');try{const plan=await api<Plan>(`/plans/${encodeURIComponent(id)}`);if(gen===detailGeneration.current)onPlan?.(plan);}catch(e){if(gen===detailGeneration.current)setError(e instanceof Error?e.message:String(e));}finally{if(gen===detailGeneration.current)setBusy(false);}}
 async function openTask(id:string,seq:number){const gen=++detailGeneration.current;setBusy(true);setError('');setSelectedTask(seq);setTask(null);try{const value=await api<Job>(`/jobs/${encodeURIComponent(id)}`);if(gen===detailGeneration.current)setTask(value);}catch(e){if(gen===detailGeneration.current)setError(e instanceof Error?e.message:String(e));}finally{if(gen===detailGeneration.current)setBusy(false);}}
 async function load(cursor:number|null){const gen=generation.current;setBusy(true);setError('');try{const p=await api<Page>(`/timeline${cursor===null?'':`?before=${cursor}`}`);if(gen!==generation.current)return;setItems(old=>cursor===null?p.items:[...old,...p.items]);setNext(p.next);}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:String(e));}finally{if(gen===generation.current)setBusy(false);}}
 useEffect(()=>{generation.current++;void load(null);return()=>{generation.current++;detailGeneration.current++;};},[]);
 return <section className="section"><h2>{t('timeline')}</h2><p>{t('timelineHint')}</p><button disabled={busy} onClick={()=>void load(null)}>{t('refreshView')}</button>{items.map(item=><article className="plan-item" key={item.seq}><strong>{t('timeline_'+item.code.replaceAll('.','_'))}</strong> · <time>{new Date(item.created*1000).toLocaleString(i18n.language)}</time>{item.job_id&&<p>{t('timelineJob')}: {item.job_id}</p>}<dl>{Object.entries(item.details).map(([key,value])=><div className="inline" key={key}><dt>{t('timelineField_'+key,{defaultValue:key})}</dt><dd>{value===null?'—':['from','to','state','kind'].includes(key)&&item.code.startsWith('file.')?t(key==='kind'?'planKind_'+value:String(value),{defaultValue:String(value)}):String(value)}</dd></div>)}</dl><div className="inline">{onPlan&&typeof item.details.plan_id==='string'&&<button disabled={busy} onClick={()=>void openPlan(String(item.details.plan_id))}>{t('timelineOpenPlan')}</button>}{item.job_id&&<button disabled={busy} onClick={()=>void openTask(item.job_id,item.seq)}>{t('timelineOpenTask')}</button>}</div>{selectedTask===item.seq&&item.job_id&&task&&<section className="audit-task-detail" aria-label={t('timelineCurrentTask')}><h3>{t('timelineCurrentTask')}</h3><p>{t('timelineTaskSnapshotHint')}</p><p className="path">{task.id}</p><span className={'pill '+task.state}>{t(task.state)}</span><p>{t('processed')}: {task.processed.toLocaleString()} · {bytes(task.bytes)} · {t('errors')}: {task.errors}</p><TaskMessages activity={task.current_path} message={task.message} state={task.state}/><button disabled={busy} onClick={()=>void openTask(task.id,item.seq)}>{t('refreshView')}</button><button onClick={()=>{detailGeneration.current++;setSelectedTask(null);setTask(null);setBusy(false);}}>{t('close')}</button></section>}</article>)}{busy&&<p role="status">{t('loading')}</p>}{error&&<p role="alert">{error}</p>}{!busy&&!error&&items.length===0&&<p>{t('timelineEmpty')}</p>}{next!==null&&<button disabled={busy} onClick={()=>void load(next)}>{t('historyOlder')}</button>}</section>;
}
