use rusqlite::{Connection,params};
use serde_json::{json,Value};
use axum::{extract::{State,Path},http::HeaderMap,Json};
pub fn reconcile(c:&Connection)->rusqlite::Result<()>{
 let mut q=c.prepare("SELECT id,state,errors,message FROM jobs WHERE kind='acquire' AND state IN ('failed','interrupted','cancelled')")?;
 let rows=q.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?)))?.collect::<rusqlite::Result<Vec<_>>>()?;
 for(id,state,errors,message)in rows{let key=json!([state,errors,message]).to_string();c.execute("INSERT INTO issues(job_id,category,kind,reason,evidence_key,created,updated) VALUES(?1,'acquire',?2,?3,?4,?5,?5) ON CONFLICT(job_id,category) DO UPDATE SET kind=excluded.kind,reason=excluded.reason,evidence_key=excluded.evidence_key,state='open',revision=issues.revision+1,updated=excluded.updated WHERE issues.evidence_key!=excluded.evidence_key OR issues.state='resolved'",params![id,format!("acquire_{state}"),message,key,crate::db::now()])?;}
 // Pending/running/paused retries retain triage. Only this exact job completing resolves it.
 c.execute("UPDATE issues SET state='resolved',revision=revision+1,updated=?1 WHERE category='acquire' AND state!='resolved' AND EXISTS(SELECT 1 FROM jobs WHERE id=issues.job_id AND state='completed')",[crate::db::now()])?;Ok(())
}
pub async fn task(State(a):State<crate::App>,h:HeaderMap,Path(id):Path<i64>)->crate::Result<Value>{
 if crate::access::authenticate(&a,&h)?.role=="web"{return Err(crate::ApiError("Desktop access required".into()));}
 let c=a.db.lock().map_err(|e|crate::ApiError(e.to_string()))?;
 // Explicit projection: never return the full job spec or archive password.
 let result=c.query_row("SELECT j.id,j.state,j.message,json_extract(j.spec,'$.destination'),json_extract(j.spec,'$.final_folder'),coalesce(json_extract(j.spec,'$.extract'),0),coalesce(json_extract(j.spec,'$.reuse_existing'),0),coalesce(json_array_length(j.spec,'$.files'),0) FROM issues i JOIN jobs j ON j.id=i.job_id WHERE i.seq=?1 AND i.category='acquire' AND j.kind='acquire'",[id],|r|Ok(json!({"id":r.get::<_,String>(0)?,"state":r.get::<_,String>(1)?,"message":r.get::<_,String>(2)?,"destination":r.get::<_,Option<String>>(3)?,"final_folder":r.get::<_,Option<String>>(4)?,"extract":r.get::<_,bool>(5)?,"reuse_existing":r.get::<_,bool>(6)?,"files":r.get::<_,i64>(7)?})))?;Ok(Json(result))
}
#[cfg(test)]mod tests{
 use super::*;
 fn fixture()->(tempfile::TempDir,crate::db::Db){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();{let c=db.lock().unwrap();for id in ["copy-a","copy-b"]{c.execute("INSERT INTO jobs(id,kind,state,spec,message,errors,created,updated) VALUES(?1,'acquire','failed',?2,'Generated failure',1,1,1)",params![id,json!({"resource_id":"same-resource","destination":id,"files":[]}).to_string()]).unwrap();}}(t,db)}
 #[test]fn same_resource_destinations_are_independent_and_retry_retains_issue(){let(_t,db)=fixture();let c=db.lock().unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM issues",[],|r|r.get::<_,i64>(0)).unwrap(),2);crate::issues::change(&c,1,1,"deferred").unwrap();c.execute("UPDATE jobs SET state='queued' WHERE id='copy-a'",[]).unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues WHERE job_id='copy-a'",[],|r|r.get::<_,String>(0)).unwrap(),"deferred");c.execute("UPDATE jobs SET state='completed' WHERE id='copy-b'",[]).unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues WHERE job_id='copy-a'",[],|r|r.get::<_,String>(0)).unwrap(),"deferred");c.execute("UPDATE jobs SET state='failed',errors=2 WHERE id='copy-a'",[]).unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues WHERE job_id='copy-a'",[],|r|r.get::<_,String>(0)).unwrap(),"open");c.execute("UPDATE jobs SET state='completed' WHERE id='copy-a'",[]).unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM issues WHERE state='resolved'",[],|r|r.get::<_,i64>(0)).unwrap(),2);}
 #[test]fn issue_identity_and_deferral_survive_backup_restore(){let(t,db)=fixture();{let c=db.lock().unwrap();reconcile(&c).unwrap();crate::issues::change(&c,1,1,"deferred").unwrap();}let backup=crate::backup::export(&db,t.path()).unwrap();let dest=crate::backup::restore_new(&backup,&t.path().join("restored"),None).unwrap();let restored=crate::db::open(&dest.join("library.sqlite")).unwrap();let c=restored.lock().unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT seq||':'||job_id||':'||state FROM issues WHERE seq=1",[],|r|r.get::<_,String>(0)).unwrap(),"1:copy-a:deferred");}
 #[test]fn schema_sixteen_migration_adds_job_identity_without_changing_triage(){let(t,db)=fixture();{let c=db.lock().unwrap();c.execute_batch("DROP INDEX issue_job; ALTER TABLE issues DROP COLUMN job_id; INSERT INTO issues(resource_id,category,kind,state,reason,evidence_key,created,updated) VALUES('r','matching','unmatched','deferred','reason','key',1,1); PRAGMA user_version=16;").unwrap();}drop(db);let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let c=db.lock().unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues WHERE resource_id='r'",[],|r|r.get::<_,String>(0)).unwrap(),"deferred");assert_eq!(c.query_row("SELECT count(*) FROM issues WHERE job_id IS NOT NULL",[],|r|r.get::<_,i64>(0)).unwrap(),2);}
}
