//! Editions and shared resource references are catalog relationships, never extra file copies.
use crate::db::{Db,id,now};
use rusqlite::{Connection,params,OptionalExtension};
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
type R<T>=Result<T,String>;
fn sql<T>(r:rusqlite::Result<T>)->R<T>{r.map_err(|e|e.to_string())}
#[derive(Clone,Serialize,Deserialize,Debug,PartialEq)]pub struct Binding{pub work_id:String,pub release_id:Option<String>,pub role:String}
#[derive(Serialize,Deserialize)]pub struct EditBindings{pub revision:i64,pub primary_work_id:Option<String>,pub bindings:Vec<Binding>}
#[derive(Serialize,Deserialize)]pub struct EditionInput{pub platforms:Option<Vec<String>>,pub origin:Option<String>,pub notes:Option<String>,pub label:String,#[serde(default)]pub languages:Vec<String>,#[serde(default)]pub edition_type:String,#[serde(default)]pub released_date:String,pub vndb_id:Option<String>,pub work_ids:Vec<String>,pub revision:Option<i64>}
pub fn migrate(c:&Connection,version:i64)->R<()>{
 sql(c.execute_batch("CREATE TABLE IF NOT EXISTS releases(id TEXT PRIMARY KEY,label TEXT NOT NULL,languages TEXT NOT NULL DEFAULT '[]',edition_type TEXT NOT NULL DEFAULT '',released_date TEXT NOT NULL DEFAULT '',vndb_id TEXT,revision INTEGER NOT NULL DEFAULT 1);
 CREATE UNIQUE INDEX IF NOT EXISTS release_vndb ON releases(vndb_id) WHERE vndb_id IS NOT NULL AND vndb_id!='';
 CREATE TABLE IF NOT EXISTS work_releases(work_id TEXT NOT NULL REFERENCES works(id),release_id TEXT NOT NULL REFERENCES releases(id),PRIMARY KEY(work_id,release_id));
 CREATE INDEX IF NOT EXISTS work_releases_release ON work_releases(release_id,work_id);
 CREATE INDEX IF NOT EXISTS works_identity_state ON works(id,merged_into);
 CREATE INDEX IF NOT EXISTS works_merged_parent ON works(merged_into,id);
 CREATE TABLE IF NOT EXISTS resource_bindings(resource_id TEXT NOT NULL REFERENCES resources(id),work_id TEXT NOT NULL REFERENCES works(id),release_id TEXT,role TEXT NOT NULL CHECK(role IN ('main','patch','extra','unknown')),PRIMARY KEY(resource_id,work_id),FOREIGN KEY(work_id,release_id) REFERENCES work_releases(work_id,release_id));
 CREATE INDEX IF NOT EXISTS bindings_work ON resource_bindings(work_id);
 CREATE TABLE IF NOT EXISTS resource_history(id TEXT PRIMARY KEY,resource_id TEXT NOT NULL,before_json TEXT NOT NULL,after_json TEXT NOT NULL,created INTEGER NOT NULL);"))?;
 let columns=sql(sql(c.prepare("PRAGMA table_info(resources)"))?.query_map([],|r|r.get::<_,String>(1)))?.collect::<rusqlite::Result<Vec<_>>>().map_err(|e|e.to_string())?;
 if !columns.iter().any(|s|s=="revision"){sql(c.execute("ALTER TABLE resources ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",[]))?;}
 for (column,definition) in [("platforms","TEXT NOT NULL DEFAULT '[]'"),("origin","TEXT NOT NULL DEFAULT ''"),("notes","TEXT NOT NULL DEFAULT ''")]{let has:bool=sql(c.query_row("SELECT EXISTS(SELECT 1 FROM pragma_table_info('releases') WHERE name=?1)",[column],|r|r.get(0)))?;if !has{sql(c.execute(&format!("ALTER TABLE releases ADD COLUMN {column} {definition}"),[]))?;}}
 sql(c.execute_batch("CREATE TABLE IF NOT EXISTS work_preferences(work_id TEXT PRIMARY KEY REFERENCES works(id),preferred_release_id TEXT,FOREIGN KEY(work_id,preferred_release_id) REFERENCES work_releases(work_id,release_id));CREATE TABLE IF NOT EXISTS preference_history(id TEXT PRIMARY KEY,work_id TEXT NOT NULL,before_release TEXT,after_release TEXT,created INTEGER NOT NULL);"))?;
 if version<3{
  let rows={let mut s=sql(c.prepare("SELECT r.id,r.work_id,r.release_label FROM resources r JOIN works w ON w.id=r.work_id"))?;let rows=sql(sql(s.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?))))?.collect::<rusqlite::Result<Vec<_>>>())?;rows};
  for(rid,wid,label)in rows{let release=legacy_release(c,&wid,&label)?;sql(c.execute("INSERT OR IGNORE INTO resource_bindings(resource_id,work_id,release_id,role) VALUES(?1,?2,?3,'unknown')",params![rid,wid,release]))?;}
 }Ok(())
}
pub fn bindings(c:&Connection,rid:&str)->R<Vec<Binding>>{let mut s=sql(c.prepare("SELECT work_id,release_id,role FROM resource_bindings WHERE resource_id=?1 ORDER BY work_id"))?;let rows=sql(sql(s.query_map([rid],|r|Ok(Binding{work_id:r.get(0)?,release_id:r.get(1)?,role:r.get(2)?})))?.collect::<rusqlite::Result<Vec<_>>>())?;Ok(rows)}
pub fn legacy_release(c:&Connection,wid:&str,label:&str)->R<Option<String>>{
 if label.trim().is_empty()||label=="Unclassified edition"{return Ok(None);}
 let found:Option<String>=sql(c.query_row("SELECT e.id FROM releases e JOIN work_releases w ON w.release_id=e.id WHERE w.work_id=?1 AND e.label=?2 ORDER BY e.id LIMIT 1",params![wid,label],|r|r.get(0)).optional())?;
 if found.is_some(){return Ok(found);}let rid=id();sql(c.execute("INSERT INTO releases(id,label) VALUES(?1,?2)",params![rid,label]))?;sql(c.execute("INSERT INTO work_releases(work_id,release_id) VALUES(?1,?2)",params![wid,rid]))?;Ok(Some(rid))
}
fn available_work(c:&Connection,wid:&str)->R<()>{let n:i64=sql(c.query_row("SELECT count(*) FROM works WHERE id=?1 AND merged_into IS NULL",[wid],|r|r.get(0)))?;if n!=1{return Err("Work is unavailable".into());}Ok(())}
pub fn list(c:&Connection)->R<Value>{edition_rows(c,None,None,true)}
pub fn list_for_work(c:&Connection,work_id:Option<&str>)->R<Value>{edition_rows(c,work_id,None,true)}
pub fn summaries_for_work(c:&Connection,work_id:&str)->R<Value>{edition_rows(c,Some(work_id),None,false)}
pub fn one(c:&Connection,id:&str)->R<Option<Value>>{Ok(edition_rows(c,None,Some(id),true)?.as_array().and_then(|rows|rows.first()).cloned())}
fn edition_rows(c:&Connection,work_id:Option<&str>,edition_id:Option<&str>,members:bool)->R<Value>{
 let filter=if work_id.is_some(){" WHERE id IN (SELECT release_id FROM work_releases WHERE work_id=?1)"}else if edition_id.is_some(){" WHERE id=?1"}else{""};
 let query=format!("SELECT id,label,languages,edition_type,released_date,vndb_id,revision,platforms,origin,notes FROM releases{filter} ORDER BY label,id");let mut s=sql(c.prepare(&query))?;let values=work_id.or(edition_id).into_iter().collect::<Vec<_>>();
 let mut rows=sql(sql(s.query_map(rusqlite::params_from_iter(values),|r|Ok(json!({"id":r.get::<_,String>(0)?,"label":r.get::<_,String>(1)?,"languages":serde_json::from_str::<Value>(&r.get::<_,String>(2)?).unwrap_or(json!([])),"edition_type":r.get::<_,String>(3)?,"released_date":r.get::<_,String>(4)?,"vndb_id":r.get::<_,Option<String>>(5)?,"revision":r.get::<_,i64>(6)?,"platforms":serde_json::from_str::<Value>(&r.get::<_,String>(7)?).unwrap_or(json!([])),"origin":r.get::<_,String>(8)?,"notes":r.get::<_,String>(9)?}))))?.collect::<rusqlite::Result<Vec<_>>>())?;
 for row in &mut rows{if members{let mut s=sql(c.prepare("SELECT work_id FROM work_releases wr JOIN works w ON w.id=wr.work_id WHERE release_id=?1 AND w.merged_into IS NULL ORDER BY work_id"))?;let works=sql(sql(s.query_map([row["id"].as_str().unwrap()],|r|r.get::<_,String>(0)))?.collect::<rusqlite::Result<Vec<_>>>())?;row["work_ids"]=json!(works);}else{let count:i64=sql(c.query_row("SELECT count(*) FROM work_releases wr JOIN works w ON w.id=wr.work_id WHERE release_id=?1 AND w.merged_into IS NULL",[row["id"].as_str().unwrap()],|r|r.get(0)))?;row["work_count"]=json!(count);row["work_id"]=json!(work_id);}}
 Ok(json!(rows))
}
pub fn save(db:&Db,release:Option<&str>,input:EditionInput)->R<Value>{
 let c=db.lock().map_err(|e|e.to_string())?;let mut checkpoint=sql(crate::checkpoint::LargeEdition::new(&c,release,input.work_ids.len()))?;let tx=sql(c.unchecked_transaction())?;
 let value=save_in(&tx,release,input,false)?;sql(tx.commit())?;checkpoint.committed();Ok(value)
}
pub(crate) fn save_in(tx:&Connection,release:Option<&str>,input:EditionInput,preserve_existing:bool)->R<Value>{
 if input.platforms.as_ref().is_some_and(|p|p.len()>20||p.iter().any(|s|s.trim().is_empty()||s.len()>50)){return Err("Use up to 20 platform names of 1 to 50 bytes".into());}
 if input.origin.as_ref().is_some_and(|v|!["","official","community"].contains(&v.as_str())){return Err("Unknown recorded edition origin".into());}
 if input.notes.as_ref().is_some_and(|v|v.len()>10000){return Err("Edition notes are limited to 10000 bytes".into());}
 if input.label.trim().is_empty()||input.label.len()>300{return Err("Enter an edition label up to 300 characters".into());}
 if !["","original","translated","remaster","bundle","other"].contains(&input.edition_type.as_str()){return Err("Unknown edition type".into());}
 if input.languages.iter().any(|s|s.len()>32||s.trim().is_empty())||input.languages.len()>20{return Err("Invalid edition languages".into());}
 if !input.released_date.is_empty()&&!regex::Regex::new(r"^\d{4}(-\d{2}(-\d{2})?)?$").unwrap().is_match(&input.released_date){return Err("Use YYYY, YYYY-MM or YYYY-MM-DD for the edition date".into());}
 let external=input.vndb_id.filter(|s|!s.is_empty());if external.as_ref().is_some_and(|s|!regex::Regex::new(r"^r[1-9][0-9]*$").unwrap().is_match(s)){return Err("VNDB release IDs start with r followed by digits".into());}
 let unique:std::collections::BTreeSet<_>=input.work_ids.iter().collect();if unique.is_empty()||unique.len()!=input.work_ids.len(){return Err("Choose distinct works for this edition".into());}
 if !preserve_existing{let mut check=sql(tx.prepare("SELECT EXISTS(SELECT 1 FROM works WHERE id=?1 AND merged_into IS NULL)"))?;for w in &input.work_ids{if !sql(check.query_row([w],|r|r.get::<_,bool>(0)))?{return Err("Work is unavailable".into());}}}
 let rid=release.map(str::to_owned).unwrap_or_else(id);let revision=if let Some(r)=release{let revision:i64=sql(tx.query_row("SELECT revision FROM releases WHERE id=?1",[r],|r|r.get(0)))?;if Some(revision)!=input.revision{return Err("Edition changed. Reload before saving.".into());}revision+1}else{1};
 let old_works={let mut s=sql(tx.prepare("SELECT work_id FROM work_releases WHERE release_id=?1"))?;let rows=sql(sql(s.query_map([&rid],|r|r.get::<_,String>(0)))?.collect::<rusqlite::Result<Vec<_>>>())?;rows};
 let previous:std::collections::BTreeSet<_>=old_works.iter().collect();
 let removed=previous.difference(&unique).copied().collect::<Vec<_>>();let added=unique.difference(&previous).copied().collect::<Vec<_>>();
 for w in &removed{let preferred:i64=sql(tx.query_row("SELECT count(*) FROM work_preferences WHERE work_id=?1 AND preferred_release_id=?2",params![w,rid],|r|r.get(0)))?;if preferred>0{return Err("Clear this work preferred edition before removing the work from the edition".into());}let n:i64=sql(tx.query_row("SELECT count(*) FROM resource_bindings WHERE release_id=?1 AND work_id=?2",params![rid,w],|r|r.get(0)))?;if n>0{return Err("Move this work's resources out of the edition before removing the work".into());}}
 sql(tx.execute("INSERT INTO releases(id,label,languages,edition_type,released_date,vndb_id,revision) VALUES(?1,?2,?3,?4,?5,?6,?7) ON CONFLICT(id) DO UPDATE SET label=excluded.label,languages=excluded.languages,edition_type=excluded.edition_type,released_date=excluded.released_date,vndb_id=excluded.vndb_id,revision=excluded.revision",params![rid,input.label.trim(),json!(input.languages).to_string(),input.edition_type,input.released_date,external,revision]))?;
 sql(tx.execute("UPDATE releases SET platforms=coalesce(?2,platforms),origin=coalesce(?3,origin),notes=coalesce(?4,notes) WHERE id=?1",params![rid,input.platforms.map(|p|json!(p).to_string()),input.origin,input.notes]))?;
 {let mut insert=sql(tx.prepare("INSERT INTO work_releases(work_id,release_id) VALUES(?1,?2)"))?;for w in added{sql(insert.execute(params![w,rid]))?;}}
 // Update the union before removing memberships: each affected work advances exactly once.
 sql(tx.execute("UPDATE works SET revision=revision+1 WHERE id IN (SELECT work_id FROM work_releases WHERE release_id=?1)",[&rid]))?;
 {let mut delete=sql(tx.prepare("DELETE FROM work_releases WHERE work_id=?1 AND release_id=?2"))?;for w in removed{sql(delete.execute(params![w,rid]))?;}}
 sql(tx.execute("UPDATE resources SET release_label=?2,revision=revision+1 WHERE EXISTS(SELECT 1 FROM resource_bindings b WHERE b.resource_id=resources.id AND b.work_id=resources.work_id AND b.release_id=?1)",params![rid,input.label.trim()]))?;Ok(json!({"id":rid,"revision":revision}))
}
pub fn set_bindings_in(c:&Connection,rid:&str,input:EditBindings)->R<Value>{
 let (revision,old_primary):(i64,Option<String>)=sql(c.query_row("SELECT revision,work_id FROM resources WHERE id=?1",[rid],|r|Ok((r.get(0)?,r.get(1)?))))?;
 if revision!=input.revision{return Err("Resource changed. Reload its references before saving.".into());}
 let unique:std::collections::BTreeSet<_>=input.bindings.iter().map(|b|&b.work_id).collect();if unique.len()!=input.bindings.len(){return Err("A resource can reference each work once".into());}
 if input.bindings.is_empty()!=input.primary_work_id.is_none()||input.primary_work_id.as_ref().is_some_and(|p|!unique.contains(p)){return Err("Choose a primary work from this resource's references".into());}
 for b in &input.bindings{available_work(c,&b.work_id)?;if !["main","patch","extra","unknown"].contains(&b.role.as_str()){return Err("Invalid resource role".into());}if let Some(e)=&b.release_id{let n:i64=sql(c.query_row("SELECT count(*) FROM work_releases WHERE work_id=?1 AND release_id=?2",params![b.work_id,e],|r|r.get(0)))?;if n!=1{return Err("The edition does not belong to this work".into());}}}
 let before=bindings(c,rid)?;sql(c.execute("DELETE FROM resource_bindings WHERE resource_id=?1",[rid]))?;
 for b in &input.bindings{sql(c.execute("INSERT INTO resource_bindings(resource_id,work_id,release_id,role) VALUES(?1,?2,?3,?4)",params![rid,b.work_id,b.release_id,b.role]))?;}
 let label=if let Some(release)=input.bindings.iter().find(|b|Some(&b.work_id)==input.primary_work_id.as_ref()).and_then(|b|b.release_id.as_ref()){sql(c.query_row("SELECT label FROM releases WHERE id=?1",[release],|r|r.get::<_,String>(0)))?}else{"Unclassified edition".into()};
 sql(c.execute("UPDATE resources SET work_id=?2,release_label=?3,revision=revision+1 WHERE id=?1",params![rid,input.primary_work_id,label]))?;
 let affected:std::collections::BTreeSet<_>=before.iter().chain(input.bindings.iter()).map(|b|&b.work_id).chain(old_primary.iter()).collect();for w in affected{sql(c.execute("UPDATE works SET revision=revision+1 WHERE id=?1",[w]))?;}
 sql(c.execute("INSERT INTO resource_history(id,resource_id,before_json,after_json,created) VALUES(?1,?2,?3,?4,?5)",params![id(),rid,json!({"primary_work_id":old_primary,"bindings":before}).to_string(),json!({"primary_work_id":input.primary_work_id,"bindings":input.bindings}).to_string(),now()]))?;Ok(json!({"id":rid,"revision":revision+1}))
}
pub fn set_bindings(db:&Db,rid:&str,input:EditBindings)->R<Value>{let mut c=db.lock().map_err(|e|e.to_string())?;let tx=sql(c.transaction())?;let v=set_bindings_in(&tx,rid,input)?;crate::timeline::manual(&tx,rid,"manual.references")?;sql(tx.commit())?;Ok(v)}
pub fn bind_primary(db:&Db,rid:&str,wid:&str,label:&str,revision:i64)->R<Value>{let mut c=db.lock().map_err(|e|e.to_string())?;let tx=sql(c.transaction())?;available_work(&tx,wid)?;let release=legacy_release(&tx,wid,label)?;let old:Option<String>=sql(tx.query_row("SELECT work_id FROM resources WHERE id=?1",[rid],|r|r.get(0)))?;let mut list=bindings(&tx,rid)?;list.retain(|b|Some(&b.work_id)!=old.as_ref()&&b.work_id!=wid);list.push(Binding{work_id:wid.into(),release_id:release,role:"unknown".into()});let result=set_bindings_in(&tx,rid,EditBindings{revision,primary_work_id:Some(wid.into()),bindings:list})?;crate::timeline::manual(&tx,rid,"manual.bind")?;sql(tx.commit())?;Ok(result)}
#[cfg(test)]mod tests{
 use super::*;
 fn fixture()->(tempfile::TempDir,Db){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();db.lock().unwrap().execute_batch("INSERT INTO roots(id,path,label) VALUES('r','fixture','Fixture');INSERT INTO works(id,title,original_title) VALUES('a','Alpha','Alpha'),('b','Beta','Beta'); INSERT INTO resources(id,root_id,relative_path,title,kind) VALUES('resource','r','game.7z','Archive','archive');").unwrap();(t,db)}
 fn input(works:Vec<String>)->EditionInput{EditionInput{platforms:None,origin:None,notes:None,label:"Japanese original".into(),languages:vec!["ja".into()],edition_type:"original".into(),released_date:"2020-01".into(),vndb_id:Some("r1".into()),work_ids:works,revision:None}}
 #[test]fn shared_edition_and_attachments_preserve_one_resource_and_reject_stale_edits(){let(_t,db)=fixture();let e=save(&db,None,input(vec!["a".into(),"b".into()])).unwrap();let eid=e["id"].as_str().unwrap().to_string();let references=vec![Binding{work_id:"a".into(),release_id:Some(eid.clone()),role:"main".into()},Binding{work_id:"b".into(),release_id:None,role:"extra".into()}];set_bindings(&db,"resource",EditBindings{revision:1,primary_work_id:Some("a".into()),bindings:references.clone()}).unwrap();assert!(set_bindings(&db,"resource",EditBindings{revision:1,primary_work_id:Some("b".into()),bindings:references}).is_err());let mut revised=input(vec!["a".into(),"b".into()]);revised.label="Corrected edition".into();revised.revision=Some(1);save(&db,Some(&eid),revised).unwrap();let c=db.lock().unwrap();assert_eq!(c.query_row("SELECT count(*) FROM resources",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert_eq!(bindings(&c,"resource").unwrap().len(),2);assert_eq!(c.query_row("SELECT release_label FROM resources",[],|r|r.get::<_,String>(0)).unwrap(),"Corrected edition");assert_eq!(bindings(&c,"resource").unwrap()[1].role,"extra");drop(c);let mut remove=input(vec!["b".into()]);remove.revision=Some(2);assert!(save(&db,Some(&eid),remove).is_err());let mut stale=input(vec!["a".into(),"b".into()]);stale.revision=Some(1);assert!(save(&db,Some(&eid),stale).is_err());}
 #[test]fn unrelated_edition_and_invalid_primary_are_rejected_atomically(){let(_t,db)=fixture();let e=save(&db,None,input(vec!["a".into()])).unwrap();let b=Binding{work_id:"b".into(),release_id:Some(e["id"].as_str().unwrap().into()),role:"patch".into()};assert!(set_bindings(&db,"resource",EditBindings{revision:1,primary_work_id:Some("b".into()),bindings:vec![b]}).is_err());assert!(set_bindings(&db,"resource",EditBindings{revision:1,primary_work_id:Some("a".into()),bindings:vec![]}).is_err());assert!(bindings(&db.lock().unwrap(),"resource").unwrap().is_empty());}
 #[test]fn migration_keeps_legacy_editions_and_manual_bindings(){let(t,db)=fixture();db.lock().unwrap().execute_batch("UPDATE resources SET work_id='a',release_label='Retail Japanese';PRAGMA user_version=2;").unwrap();drop(db);let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let c=db.lock().unwrap();let b=bindings(&c,"resource").unwrap();assert_eq!(b.len(),1);assert_eq!(b[0].work_id,"a");assert!(b[0].release_id.is_some());assert_eq!(list(&c).unwrap()[0]["label"],"Retail Japanese");}
 #[test]fn merging_shared_work_keeps_target_role_and_physical_primary(){let(_t,db)=fixture();set_bindings(&db,"resource",EditBindings{revision:1,primary_work_id:Some("a".into()),bindings:vec![Binding{work_id:"a".into(),release_id:None,role:"main".into()},Binding{work_id:"b".into(),release_id:None,role:"extra".into()}]}).unwrap();let revision=|w:&str|db.lock().unwrap().query_row("SELECT revision FROM works WHERE id=?1",[w],|r|r.get(0)).unwrap();crate::grouping::merge(&db,"a","b",revision("a"),revision("b")).unwrap();let c=db.lock().unwrap();let list=bindings(&c,"resource").unwrap();assert_eq!(list.len(),1);assert_eq!(list[0].role,"extra");assert_eq!(c.query_row("SELECT work_id FROM resources",[],|r|r.get::<_,String>(0)).unwrap(),"b");assert!(c.query_row("SELECT count(*) FROM resource_history",[],|r|r.get::<_,i64>(0)).unwrap()>=2);}
 #[test]fn edition_paths_are_stable_and_rescan_keeps_resource_identity(){
 let t=tempfile::tempdir().unwrap();let source=t.path().join("source");let dest=t.path().join("managed");std::fs::create_dir(&source).unwrap();std::fs::create_dir(&dest).unwrap();for name in ["original.zip","patch.zip"]{std::fs::write(source.join(name),name).unwrap();}let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();db.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES('r',?1,'Source')",[source.to_str().unwrap()]).unwrap();db.lock().unwrap().execute("INSERT INTO works(id,title,original_title) VALUES('a','Alpha','Alpha')",[]).unwrap();let scan=|root:&str|{let j=crate::scan::create(&db,crate::scan::ScanSpec{root_id:root.into(),scope:"".into(),exclude:vec![]}).unwrap();crate::scan::run(db.clone(),j);};scan("r");let edition=save(&db,None,input(vec!["a".into()])).unwrap();let eid=edition["id"].as_str().unwrap().to_string();let rows={let c=db.lock().unwrap();let mut s=c.prepare("SELECT id,revision FROM resources").unwrap();s.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,i64>(1)?))).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap()};
 for(rid,revision)in &rows{set_bindings(&db,rid,EditBindings{revision:*revision,primary_work_id:Some("a".into()),bindings:vec![Binding{work_id:"a".into(),release_id:Some(eid.clone()),role:"main".into()}]}).unwrap();let plan=crate::plans::organize(&db,rid,dest.to_str().unwrap()).unwrap();let target=plan["items"][0]["target"].as_str().unwrap();assert!(target.contains(&eid));assert!(target.contains(rid));crate::plans::approve(&db,plan["id"].as_str().unwrap(),plan["digest"].as_str().unwrap()).unwrap();crate::plans::execute(&db,plan["id"].as_str().unwrap()).unwrap();}
 let managed:String=db.lock().unwrap().query_row("SELECT id FROM roots WHERE role='managed'",[],|r|r.get(0)).unwrap();scan(&managed);let c=db.lock().unwrap();assert_eq!(c.query_row("SELECT count(*) FROM resources",[],|r|r.get::<_,i64>(0)).unwrap(),2);assert_eq!(c.query_row("SELECT count(*) FROM resource_files",[],|r|r.get::<_,i64>(0)).unwrap(),2);assert_eq!(c.query_row("SELECT count(*) FROM resource_bindings WHERE release_id=?1",[eid],|r|r.get::<_,i64>(0)).unwrap(),2);
 }
}

pub fn prefer(db:&Db,wid:&str,revision:i64,release:Option<&str>)->R<Value>{
 let mut c=db.lock().map_err(|e|e.to_string())?;let tx=sql(c.transaction())?;available_work(&tx,wid)?;let current:i64=sql(tx.query_row("SELECT revision FROM works WHERE id=?1",[wid],|r|r.get(0)))?;if current!=revision{return Err("Work changed. Reload before selecting a preferred edition.".into());}
 if let Some(release)=release{let belongs:bool=sql(tx.query_row("SELECT EXISTS(SELECT 1 FROM work_releases WHERE work_id=?1 AND release_id=?2)",params![wid,release],|r|r.get(0)))?;if !belongs{return Err("Choose an edition belonging to this work".into());}}
 let old:Option<String>=sql(tx.query_row("SELECT preferred_release_id FROM work_preferences WHERE work_id=?1",[wid],|r|r.get(0)).optional())?.flatten();
 if old.as_deref()==release{return Ok(json!({"id":wid,"revision":current,"preferred_release_id":old}));}
 sql(tx.execute("INSERT INTO work_preferences(work_id,preferred_release_id) VALUES(?1,?2) ON CONFLICT(work_id) DO UPDATE SET preferred_release_id=excluded.preferred_release_id",params![wid,release]))?;
 sql(tx.execute("UPDATE works SET revision=revision+1 WHERE id=?1",[wid]))?;
 sql(tx.execute("INSERT INTO preference_history(id,work_id,before_release,after_release,created) VALUES(?1,?2,?3,?4,?5)",params![id(),wid,old,release,now()]))?;sql(tx.commit())?;Ok(json!({"id":wid,"revision":current+1,"preferred_release_id":release}))
}
#[cfg(test)]mod preference_tests{
 use super::*;use crate::{db,backup,metadata,grouping};
 fn fixture()->(tempfile::TempDir,Db,String,String){let t=tempfile::tempdir().unwrap();let db=db::open(&t.path().join("state/library.sqlite")).unwrap();db.lock().unwrap().execute_batch("INSERT INTO works(id,title,original_title,notes,favorite) VALUES('a','Alpha','Original Alpha','Keep notes',1),('b','Beta','Original Beta','Other notes',0);").unwrap();let a=save(&db,None,input(vec!["a".into(),"b".into()])).unwrap()["id"].as_str().unwrap().into();let b=save(&db,None,input(vec!["b".into()])).unwrap()["id"].as_str().unwrap().into();(t,db,a,b)}
 fn input(works:Vec<String>)->EditionInput{EditionInput{platforms:Some(vec!["Windows".into()]),origin:Some("official".into()),notes:Some("Original disc; patch is a separate resource".into()),label:"Recorded edition".into(),languages:vec!["ja".into()],edition_type:"original".into(),released_date:"2004".into(),vndb_id:None,work_ids:works,revision:None}}
 fn revision(db:&Db,w:&str)->i64{db.lock().unwrap().query_row("SELECT revision FROM works WHERE id=?1",[w],|r|r.get(0)).unwrap()}
 fn chosen(db:&Db,w:&str)->Option<String>{db.lock().unwrap().query_row("SELECT preferred_release_id FROM work_preferences WHERE work_id=?1",[w],|r|r.get(0)).optional().unwrap().flatten()}
 #[test]fn preference_validates_work_revision_without_changing_private_state_or_starting_work(){let(_t,db,a,b)=fixture();let r=revision(&db,"a");assert!(prefer(&db,"a",r,Some(&b)).is_err());prefer(&db,"a",r,Some(&a)).unwrap();assert_eq!(chosen(&db,"a"),Some(a.clone()));assert!(prefer(&db,"a",r,None).is_err());let new=revision(&db,"a");assert_eq!(prefer(&db,"a",new,Some(&a)).unwrap()["revision"],new);metadata::apply(&db,"a",new,&json!({}),&[],Some(json!({"title":"Provider refresh"}))).unwrap();assert_eq!(chosen(&db,"a"),Some(a));let c=db.lock().unwrap();assert_eq!(c.query_row("SELECT notes,favorite,original_title FROM works WHERE id='a'",[],|r|Ok((r.get::<_,String>(0)?,r.get::<_,i64>(1)?,r.get::<_,String>(2)?))).unwrap(),("Keep notes".into(),1,"Original Alpha".into()));assert_eq!(c.query_row("SELECT (SELECT count(*) FROM jobs)+(SELECT count(*) FROM plans)",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(c.query_row("SELECT count(*) FROM preference_history",[],|r|r.get::<_,i64>(0)).unwrap(),1);}
 #[test]fn removing_a_preferred_association_requires_clear_and_old_clients_preserve_new_fields(){let(_t,db,a,_)=fixture();prefer(&db,"a",revision(&db,"a"),Some(&a)).unwrap();let mut v=input(vec!["b".into()]);v.revision=Some(1);assert!(save(&db,Some(&a),v).unwrap_err().contains("preferred"));prefer(&db,"a",revision(&db,"a"),None).unwrap();let mut v=input(vec!["b".into()]);v.revision=Some(1);v.platforms=None;v.origin=None;v.notes=None;save(&db,Some(&a),v).unwrap();let rows=list(&db.lock().unwrap()).unwrap();let e=rows.as_array().unwrap().iter().find(|e|e["id"]==a).unwrap();assert_eq!(e["platforms"],json!(["Windows"]));assert_eq!(e["origin"],"official");assert_eq!(e["notes"],"Original disc; patch is a separate resource");assert_eq!(chosen(&db,"a"),None);}
 #[test]fn preference_and_comparison_fields_survive_restart_and_isolated_restore(){let(t,db,a,_)=fixture();prefer(&db,"a",revision(&db,"a"),Some(&a)).unwrap();let path=t.path().join("state/library.sqlite");drop(db);let db=db::open(&path).unwrap();assert_eq!(chosen(&db,"a"),Some(a.clone()));let export=backup::export(&db,t.path()).unwrap();let manifest=backup::inspect(&export).unwrap();let destination=t.path().join("restored");backup::restore_new(&export,&destination,Some(&manifest.sha256)).unwrap();let restored=db::open(&destination.join("library.sqlite")).unwrap();assert_eq!(chosen(&restored,"a"),Some(a));assert_eq!(list(&db.lock().unwrap()).unwrap(),list(&restored.lock().unwrap()).unwrap());assert_eq!(restored.lock().unwrap().query_row("SELECT count(*) FROM preference_history",[],|r|r.get::<_,i64>(0)).unwrap(),1);}
 #[test]fn merge_preserves_target_preference_and_retains_source_choice_in_history(){let(_t,db,a,b)=fixture();prefer(&db,"a",revision(&db,"a"),Some(&a)).unwrap();prefer(&db,"b",revision(&db,"b"),Some(&b)).unwrap();grouping::merge(&db,"a","b",revision(&db,"a"),revision(&db,"b")).unwrap();assert_eq!(chosen(&db,"b"),Some(b));assert_eq!(chosen(&db,"a"),Some(a));assert!(prefer(&db,"a",revision(&db,"a"),None).is_err());}
 #[test]fn v8_upgrade_preserves_editions_and_defaults_unknown_without_inventing_a_preference(){let(t,db,a,_)=fixture();let path=t.path().join("state/library.sqlite");drop(db);let c=Connection::open(&path).unwrap();c.execute_batch("DROP TABLE work_preferences;DROP TABLE preference_history;ALTER TABLE releases DROP COLUMN platforms;ALTER TABLE releases DROP COLUMN origin;ALTER TABLE releases DROP COLUMN notes;PRAGMA user_version=8;").unwrap();drop(c);let db=db::open(&path).unwrap();assert_eq!(chosen(&db,"a"),None);let rows=list(&db.lock().unwrap()).unwrap();let e=rows.as_array().unwrap().iter().find(|e|e["id"]==a).unwrap();assert_eq!(e["platforms"],json!([]));assert_eq!(e["origin"],"");assert_eq!(e["languages"],json!(["ja"]));assert_eq!(db.lock().unwrap().query_row("SELECT count(*) FROM pragma_foreign_key_check",[],|r|r.get::<_,i64>(0)).unwrap(),0);}
}

