//! Durable, single-worker SHA-256 checks. Completed files survive pause/restart.
use crate::{db::{Db,id,now},plans,scan,roots};
use rusqlite::{Connection,params};
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use sha2::{Digest,Sha256};
use std::{fs,path::Path,io::Read};
type R<T>=Result<T,String>;
fn sql<T>(r:rusqlite::Result<T>)->R<T>{r.map_err(|e|e.to_string())}
#[derive(Serialize,Deserialize)]pub struct Spec{pub root_ids:Vec<String>}
#[derive(Clone)]struct Entry{file_id:String,path:String,size:i64,mtime:String,state:String,sha256:Option<String>}
fn mtime(m:&fs::Metadata)->String{m.modified().ok().and_then(|t|t.duration_since(std::time::UNIX_EPOCH).ok()).map(|t|t.as_nanos().to_string()).unwrap_or_default()}
pub fn create(db:&Db,spec:Spec)->R<String>{
 let unique:std::collections::BTreeSet<_>=spec.root_ids.iter().collect();if unique.is_empty()||unique.len()!=spec.root_ids.len()||unique.len()>100{return Err("Choose one or more distinct sources".into());}
 let mut c=db.lock().map_err(|e|e.to_string())?;let tx=sql(c.transaction())?;roots::require_idle(&tx)?;
 for rid in &spec.root_ids{let path:String=sql(tx.query_row("SELECT path FROM roots WHERE id=?1",[rid],|r|r.get(0)))?;plans::validate_chain(Path::new(&path))?;if !Path::new(&path).is_dir(){return Err("A selected source is unavailable. Reconnect it before checking duplicates.".into());}}
 let marks=vec!["?";spec.root_ids.len()].join(",");
 let rows={let mut s=sql(tx.prepare(&format!("SELECT id,path,size,mtime FROM files WHERE root_id IN ({marks}) AND availability='present' ORDER BY size,path")))?;let rows=sql(sql(s.query_map(rusqlite::params_from_iter(&spec.root_ids),|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?))))?.collect::<rusqlite::Result<Vec<_>>>())?;rows};
 let mut counts=std::collections::BTreeMap::new();for row in &rows{*counts.entry(row.2).or_insert(0usize)+=1;}
 let candidates:Vec<_>=rows.into_iter().filter(|r|counts[&r.2]>1).collect();let jid=id();
 sql(tx.execute("INSERT INTO jobs(id,kind,state,spec,discovered,created,updated,message) VALUES(?1,'hash','queued',?2,?3,?4,?4,'Queued for full SHA-256 verification')",params![jid,json!(spec).to_string(),candidates.len()as i64,now()]))?;
 for(fid,path,size,mtime)in candidates{sql(tx.execute("INSERT INTO hash_entries(job_id,file_id,path,size,mtime) VALUES(?1,?2,?3,?4,?5)",params![jid,fid,path,size,mtime]))?;}sql(tx.commit())?;Ok(jid)
}
fn entries(c:&Connection,jid:&str)->R<Vec<Entry>>{let mut s=sql(c.prepare("SELECT file_id,path,size,mtime,state,sha256 FROM hash_entries WHERE job_id=?1 ORDER BY path"))?;let rows=sql(sql(s.query_map([jid],|r|Ok(Entry{file_id:r.get(0)?,path:r.get(1)?,size:r.get(2)?,mtime:r.get(3)?,state:r.get(4)?,sha256:r.get(5)?})))?.collect::<rusqlite::Result<Vec<_>>>())?;Ok(rows)}
fn unchanged(e:&Entry)->R<()>{plans::validate_chain(Path::new(&e.path))?;let m=fs::symlink_metadata(&e.path).map_err(|err|err.to_string())?;if !m.is_file()||scan::link(&m)||m.len()!=e.size as u64||mtime(&m)!=e.mtime{return Err("Source changed since this check was queued. Scan the source and start a new duplicate check.".into());}Ok(())}
fn catalog_matches(c:&Connection,e:&Entry)->R<bool>{let n:i64=sql(c.query_row("SELECT count(*) FROM files WHERE id=?1 AND path=?2 AND size=?3 AND mtime=?4 AND availability='present'",params![e.file_id,e.path,e.size,e.mtime],|r|r.get(0)))?;Ok(n==1)}
fn checkpoint(db:&Db,jid:&str)->R<bool>{let c=db.lock().map_err(|e|e.to_string())?;let state:String=sql(c.query_row("SELECT state FROM jobs WHERE id=?1",[jid],|r|r.get(0)))?;let next=match state.as_str(){"running"=>return Ok(true),"pausing"=>"paused","cancelling"=>"cancelled",_=>return Ok(false)};sql(c.execute("UPDATE jobs SET state=?2,message='Completed file hashes are saved. The current file restarts on resume.',updated=?3 WHERE id=?1",params![jid,next,now()]))?;Ok(false)}
fn progress(db:&Db,jid:&str,processed:i64,bytes:i64,path:&str)->R<()>{let c=db.lock().map_err(|e|e.to_string())?;sql(c.execute("UPDATE jobs SET processed=?2,bytes=?3,current_path=?4,updated=?5 WHERE id=?1",params![jid,processed,bytes,path,now()]))?;Ok(())}
fn digest(db:&Db,jid:&str,e:&Entry,processed:i64,done_bytes:i64)->R<Option<String>>{
 unchanged(e)?;{let c=db.lock().map_err(|e|e.to_string())?;if !catalog_matches(&c,e)?{return Err("Catalog location changed. Start a new duplicate check.".into());}sql(c.execute("UPDATE hash_entries SET attempts=attempts+1,state='pending',sha256=NULL,error='' WHERE job_id=?1 AND file_id=?2",params![jid,e.file_id]))?;}
 let mut file=fs::File::open(&e.path).map_err(|err|err.to_string())?;let opened=file.metadata().map_err(|err|err.to_string())?;if opened.len()!=e.size as u64||mtime(&opened)!=e.mtime{return Err("Source changed while opening the file".into());}
 let mut buffer=vec![0u8;1024*1024];let mut hasher=Sha256::new();let mut read=0i64;let mut last=std::time::Instant::now();
 loop{if !checkpoint(db,jid)?{return Ok(None);}let n=file.read(&mut buffer).map_err(|err|err.to_string())?;if n==0{break;}hasher.update(&buffer[..n]);read+=n as i64;if last.elapsed()>=std::time::Duration::from_millis(100){progress(db,jid,processed,done_bytes+read,&e.path)?;last=std::time::Instant::now();}}
 let after=file.metadata().map_err(|err|err.to_string())?;unchanged(e)?;if read!=e.size||after.len()!=e.size as u64||mtime(&after)!=e.mtime{return Err("Source changed during hashing".into());}Ok(Some(hex::encode(hasher.finalize())))
}
pub fn run(db:Db,jid:String){if let Err(error)=inner(&db,&jid){crate::diagnostics::record("error","hash.failed",&error,Some(&jid));if let Ok(c)=db.lock(){let _=c.execute("UPDATE jobs SET state='failed',message=?2,updated=?3 WHERE id=?1 AND state='running'",params![jid,error,now()]);}}}
fn inner(db:&Db,jid:&str)->R<()>{
 let saved={let c=db.lock().map_err(|e|e.to_string())?;let claimed=sql(c.execute("UPDATE jobs SET state='running',errors=0,message='Hashing size-matched candidates',updated=?2 WHERE id=?1 AND kind='hash' AND state='queued'",params![jid,now()]))?;if claimed!=1{return Ok(());}entries(&c,jid)?};
 let(mut processed,mut done_bytes,mut errors)=(0i64,0i64,0i64);
 // Reuse only complete hashes whose recorded location and metadata still agree.
 for e in saved.iter().filter(|e|e.state=="completed"){if !checkpoint(db,jid)?{return Ok(());}let c=db.lock().map_err(|e|e.to_string())?;if unchanged(e).is_ok()&&catalog_matches(&c,e)?&&e.sha256.is_some(){processed+=1;done_bytes+=e.size;}else{sql(c.execute("UPDATE hash_entries SET state='pending',sha256=NULL WHERE job_id=?1 AND file_id=?2",params![jid,e.file_id]))?;}}
 progress(db,jid,processed,done_bytes,"")?;let work={let c=db.lock().map_err(|e|e.to_string())?;entries(&c,jid)?};
 for e in work{if !checkpoint(db,jid)?{return Ok(());}if e.state=="completed"{continue;}progress(db,jid,processed,done_bytes,&e.path)?;
  match digest(db,jid,&e,processed,done_bytes){Ok(None)=>return Ok(()),Ok(Some(hash))=>{let c=db.lock().map_err(|e|e.to_string())?;if !catalog_matches(&c,&e)?{return Err("Catalog changed while hashing. Scan the source and start a new check.".into());}sql(c.execute("UPDATE hash_entries SET state='completed',sha256=?3,error='' WHERE job_id=?1 AND file_id=?2",params![jid,e.file_id,hash]))?;sql(c.execute("UPDATE files SET hash=?2 WHERE id=?1",params![e.file_id,hash]))?;done_bytes+=e.size;},Err(error)=>{errors+=1;let c=db.lock().map_err(|e|e.to_string())?;sql(c.execute("UPDATE hash_entries SET state='error',sha256=NULL,error=?3 WHERE job_id=?1 AND file_id=?2",params![jid,e.file_id,error]))?;sql(c.execute("UPDATE jobs SET errors=?2 WHERE id=?1",params![jid,errors]))?;}}
  processed+=1;progress(db,jid,processed,done_bytes,"")?;
 }
 if !checkpoint(db,jid)?{return Ok(());}let c=db.lock().map_err(|e|e.to_string())?;sql(c.execute("UPDATE jobs SET state='completed',processed=?2,bytes=?3,errors=?4,current_path='',message=?5,updated=?6 WHERE id=?1",params![jid,processed,done_bytes,errors,if errors==0{"Duplicate check complete. Review results in Quarantine."}else{"Duplicate check complete with errors. Some files need a new check."},now()]))?;Ok(())
}
pub fn results(db:&Db,jid:&str)->R<Value>{
 let (state,rows,errors)={let c=db.lock().map_err(|e|e.to_string())?;let state:String=sql(c.query_row("SELECT state FROM jobs WHERE id=?1 AND kind='hash'",[jid],|r|r.get(0)))?;let rows=entries(&c,jid)?;let mut s=sql(c.prepare("SELECT path,error FROM hash_entries WHERE job_id=?1 AND state='error' ORDER BY path"))?;let errors=sql(sql(s.query_map([jid],|r|Ok(json!({"path":r.get::<_,String>(0)?,"error":r.get::<_,String>(1)?}))))?.collect::<rusqlite::Result<Vec<_>>>())?;(state,rows,errors)};
 let mut groups=std::collections::BTreeMap::<String,Vec<Value>>::new();let mut stale=0;let mut verified=0;
 for e in rows.iter().filter(|e|e.state=="completed"){let c=db.lock().map_err(|e|e.to_string())?;let valid=catalog_matches(&c,e)?;drop(c);if !valid||unchanged(e).is_err(){stale+=1;continue;}if let Some(hash)=&e.sha256{verified+=1;groups.entry(hash.clone()).or_default().push(json!({"id":e.file_id,"path":e.path,"size":e.size}));}}
 let groups:Vec<_>=groups.into_iter().filter(|(_,files)|files.len()>1).map(|(hash,files)|json!({"sha256":hash,"files":files})).collect();Ok(json!({"job_id":jid,"state":state,"candidates":rows.len(),"verified":verified,"stale":stale,"errors":errors,"groups":groups}))
}
#[cfg(test)]mod tests{
 use super::*;
 fn indexed(root:&Path,db:&Db){db.lock().unwrap().execute("INSERT INTO roots(id,path,label) VALUES('r',?1,'Hashes')",[root.to_str().unwrap()]).unwrap();let j=scan::create(db,scan::ScanSpec{root_id:"r".into(),scope:"".into(),exclude:vec![]}).unwrap();scan::run(db.clone(),j);}
 #[test]fn only_full_hash_matches_are_results_and_changed_files_are_removed(){let t=tempfile::tempdir().unwrap();let root=t.path().join("source");fs::create_dir(&root).unwrap();for(name,data)in [("a.bin",b"identical".as_slice()),("b.bin",b"identical"),("c.bin",b"different"),("unique.bin",b"unique size"),("empty-a",b""),("empty-b",b"")]{fs::write(root.join(name),data).unwrap();}let db=crate::db::open(&t.path().join("state/library.sqlite")).unwrap();indexed(&root,&db);let job=create(&db,Spec{root_ids:vec!["r".into()]}).unwrap();run(db.clone(),job.clone());let report=results(&db,&job).unwrap();assert_eq!(report["state"],"completed");assert_eq!(report["candidates"],5);assert_eq!(report["groups"].as_array().unwrap().len(),2);fs::write(root.join("b.bin"),b"external change").unwrap();let report=results(&db,&job).unwrap();assert_eq!(report["stale"],1);assert_eq!(report["groups"].as_array().unwrap().len(),1);}
 #[test]fn queued_snapshot_change_is_an_error_not_a_duplicate(){let t=tempfile::tempdir().unwrap();let root=t.path().join("source");fs::create_dir(&root).unwrap();fs::write(root.join("a.bin"),b"same").unwrap();fs::write(root.join("b.bin"),b"same").unwrap();let db=crate::db::open(&t.path().join("state/library.sqlite")).unwrap();indexed(&root,&db);let job=create(&db,Spec{root_ids:vec!["r".into()]}).unwrap();fs::write(root.join("b.bin"),b"changed length").unwrap();run(db.clone(),job.clone());let r=results(&db,&job).unwrap();assert_eq!(r["errors"].as_array().unwrap().len(),1);assert!(r["groups"].as_array().unwrap().is_empty());}
 #[test]fn paused_hash_recovers_complete_files_without_rehashing_them(){
 let t=tempfile::tempdir().unwrap();let root=t.path().join("source");fs::create_dir(&root).unwrap();let bytes=vec![17u8;2*1024*1024];for i in 0..32{fs::write(root.join(format!("{i:02}.bin")),&bytes).unwrap();}let path=t.path().join("state/library.sqlite");let db=crate::db::open(&path).unwrap();indexed(&root,&db);let job=create(&db,Spec{root_ids:vec!["r".into()]}).unwrap();let worker_db=db.clone();let worker_job=job.clone();let thread=std::thread::spawn(move||run(worker_db,worker_job));let deadline=std::time::Instant::now()+std::time::Duration::from_secs(10);
 loop{let c=db.lock().unwrap();let done:i64=c.query_row("SELECT count(*) FROM hash_entries WHERE job_id=?1 AND state='completed'",[&job],|r|r.get(0)).unwrap();if done>0{c.execute("UPDATE jobs SET state='pausing' WHERE id=?1 AND state='running'",[&job]).unwrap();break;}assert!(std::time::Instant::now()<deadline);drop(c);std::thread::sleep(std::time::Duration::from_millis(1));}thread.join().unwrap();let saved={let c=db.lock().unwrap();assert_eq!(c.query_row("SELECT state FROM jobs WHERE id=?1",[&job],|r|r.get::<_,String>(0)).unwrap(),"paused");let mut s=c.prepare("SELECT file_id,attempts FROM hash_entries WHERE job_id=?1 AND state='completed'").unwrap();let rows=s.query_map([&job],|r|Ok((r.get::<_,String>(0)?,r.get::<_,i64>(1)?))).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();c.execute("UPDATE jobs SET state='running' WHERE id=?1",[&job]).unwrap();rows};assert!(!saved.is_empty()&&saved.len()<32);drop(db);
 let db=crate::db::open(&path).unwrap();assert_eq!(results(&db,&job).unwrap()["state"],"interrupted");db.lock().unwrap().execute("UPDATE jobs SET state='queued' WHERE id=?1",[&job]).unwrap();run(db.clone(),job.clone());let report=results(&db,&job).unwrap();assert_eq!(report["state"],"completed");assert_eq!(report["verified"],32);assert_eq!(report["groups"][0]["files"].as_array().unwrap().len(),32);let c=db.lock().unwrap();for(fid,attempts)in saved{assert_eq!(c.query_row("SELECT attempts FROM hash_entries WHERE job_id=?1 AND file_id=?2",params![job,fid],|r|r.get::<_,i64>(0)).unwrap(),attempts);}assert_eq!(fs::read(root.join("00.bin")).unwrap(),bytes);
 }
}
