//! Bounded resource selection with the existing complete resource projection.
use axum::{extract::{State,Query},http::HeaderMap,Json};
use serde::{Deserialize,Serialize};use serde_json::{Value,json};use rusqlite::{Connection,params};use crate::{ApiError,App};
pub fn migrate(c:&Connection)->rusqlite::Result<()>{c.execute_batch("CREATE INDEX IF NOT EXISTS resource_title_order ON resources(title,id);")}
#[derive(Default,Deserialize)]pub struct Options{#[serde(default)]query:String,#[serde(default)]status:String,#[serde(default)]root_id:String,#[serde(default)]exclude_id:String,before:Option<String>}
#[derive(Serialize,Deserialize)]#[serde(deny_unknown_fields)]struct Cursor{library:String,revision:i64,query:String,status:String,#[serde(default)]root_id:String,#[serde(default)]exclude_id:String,offset:i64}
pub async fn read(State(a):State<App>,h:HeaderMap,Query(q):Query<Options>)->crate::Result<Value>{crate::auth(&a,&h)?;Ok(Json(page(&a.db.lock().unwrap(),&q)?))}
fn page(c:&Connection,q:&Options)->Result<Value,ApiError>{
 if q.root_id.len()>512||q.exclude_id.len()>512||q.query.len()>512||!["","all","matched","unmatched"].contains(&q.status.as_str()){return Err(ApiError("Invalid resource query".into()));}
 let library=crate::context::library(c)?.id;let revision:i64=c.query_row("SELECT revision FROM smart_catalog_state WHERE singleton=1",[],|r|r.get(0))?;
 let offset=if let Some(raw)=&q.before{if raw.len()>4096{return Err(ApiError("Invalid resource cursor".into()));}let cursor:Cursor=serde_json::from_str(raw).map_err(|_|ApiError("Invalid resource cursor".into()))?;if cursor.library!=library||cursor.revision!=revision||cursor.query!=q.query||cursor.status!=q.status||cursor.root_id!=q.root_id||cursor.exclude_id!=q.exclude_id||cursor.offset<0{return Err(ApiError("Resources changed. Restart from the first page.".into()));}cursor.offset}else{0};
 c.create_scalar_function("resource_search_lower",1,rusqlite::functions::FunctionFlags::SQLITE_UTF8|rusqlite::functions::FunctionFlags::SQLITE_DETERMINISTIC,|ctx|Ok(ctx.get::<String>(0)?.to_lowercase()))?;
 let search=q.query.to_lowercase();
 let filter=" FROM resources r JOIN roots rt ON rt.id=r.root_id WHERE EXISTS(SELECT 1 FROM resource_files rf JOIN files f ON f.id=rf.file_id WHERE rf.resource_id=r.id) AND (?1 IN ('','all') OR (?1='matched' AND r.work_id IS NOT NULL) OR (?1='unmatched' AND r.work_id IS NULL)) AND (?3='' OR r.root_id=?3) AND (?4='' OR r.id<>?4) AND (?2='' OR instr(resource_search_lower(r.title||' '||r.relative_path),?2)>0)";
 let total:i64=c.query_row(&format!("SELECT count(*){filter}"),params![q.status,search,q.root_id,q.exclude_id],|r|r.get(0))?;
 let mut statement=c.prepare(&format!("SELECT r.id{filter} ORDER BY r.title,r.id LIMIT 61 OFFSET ?5"))?;let mut ids=statement.query_map(params![q.status,search,q.root_id,q.exclude_id,offset],|r|r.get::<_,String>(0))?.collect::<rusqlite::Result<Vec<_>>>()?;let more=ids.len()>60;ids.truncate(60);
 let mut items=crate::resource_catalog::selected(c,&ids)?;items.sort_by_key(|item|ids.iter().position(|id|Some(id.as_str())==item["id"].as_str()).unwrap_or(usize::MAX));
 let next=if more{Some(serde_json::to_string(&Cursor{library:library.clone(),revision,query:q.query.clone(),status:q.status.clone(),root_id:q.root_id.clone(),exclude_id:q.exclude_id.clone(),offset:offset+60}).map_err(|e|ApiError(e.to_string()))?)}else{None};
 Ok(json!({"items":items,"next":next,"total":total,"revision":revision,"library_id":library,"offset":offset}))
}
#[cfg(test)]mod tests{use super::*;
#[test]fn resource_pages_match_projection_and_reject_changed_scope(){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let c=db.lock().unwrap();c.execute_batch("INSERT INTO roots(id,path,label) VALUES('root','generated','Generated');INSERT INTO works(id,title,original_title) VALUES('a','A','A'),('b','B','B');INSERT INTO files(id,root_id,path,relative_path,size,mtime,ext,seen_job,availability) VALUES('f','root','f','f',7,'','bin','','missing');").unwrap();for i in 0..125{let id=format!("r{i:03}");c.execute("INSERT INTO resources(id,root_id,relative_path,title,kind,work_id) VALUES(?1,'root',?1,'Same title','folder',?2)",params![id,if i%2==0{Some("a")}else{None}]).unwrap();c.execute("INSERT INTO resource_files VALUES(?1,'f')",[&id]).unwrap();c.execute("INSERT INTO resource_bindings(resource_id,work_id,role) VALUES(?1,'b','patch')",[&id]).unwrap();}c.execute("INSERT INTO resources(id,root_id,relative_path,title,kind) VALUES('empty','root','empty','Empty','folder')",[]).unwrap();let baseline=crate::resource_catalog::rows(&c,None).ok().unwrap();let mut q=Options::default();let mut found=Vec::new();loop{let result=page(&c,&q).ok().unwrap();assert_eq!(result["total"],125);let items=result["items"].as_array().unwrap();assert!(items.len()<=60);for item in items{assert_eq!(baseline.iter().find(|old|old["id"]==item["id"]).unwrap(),item);found.push(item["id"].as_str().unwrap().to_owned());}q.before=result["next"].as_str().map(str::to_owned);if q.before.is_none(){break;}}assert_eq!(found,(0..125).map(|i|format!("r{i:03}")).collect::<Vec<_>>());
 let first=page(&c,&Options::default()).ok().unwrap();let cursor=first["next"].as_str().unwrap().to_owned();assert!(page(&c,&Options{status:"matched".into(),before:Some(cursor.clone()),..Default::default()}).is_err());assert_eq!(page(&c,&Options{status:"matched".into(),..Default::default()}).ok().unwrap()["total"],63);assert_eq!(page(&c,&Options{query:"r124".into(),..Default::default()}).ok().unwrap()["total"],1);let mut foreign:Value=serde_json::from_str(&cursor).unwrap();foreign["library"]=json!("another");assert!(page(&c,&Options{before:Some(foreign.to_string()),..Default::default()}).is_err());assert!(page(&c,&Options{query:"x".repeat(513),..Default::default()}).is_err());assert!(page(&c,&Options{before:Some("invalid".into()),..Default::default()}).is_err());assert!(crate::resource_catalog::selected(&c,&vec!["r000".into();61]).is_err());c.execute("UPDATE files SET size=8 WHERE id='f'",[]).unwrap();assert!(page(&c,&Options{before:Some(cursor),..Default::default()}).is_err());assert!(page(&c,&Options{status:"invalid".into(),..Default::default()}).is_err());c.execute("UPDATE resources SET title='ÉCOLE ΩMEGA',relative_path='資料/ÄPFEL' WHERE id='r124'",[]).unwrap();for query in ["école","ωmega","äpfel","資料"]{let result=page(&c,&Options{query:query.into(),..Default::default()}).ok().unwrap();assert_eq!(result["total"],1);assert_eq!(result["items"][0]["id"],"r124");}
}}

#[cfg(test)]mod http_tests{use super::*;
#[tokio::test]async fn resource_http_enforces_auth_preserves_projection_and_rejects_stale_cursor(){
 let t=tempfile::tempdir().unwrap();let app=crate::initialize(t.path().join("state")).unwrap();crate::access::setup(&app.db,"Generated resource test passphrase",false).unwrap();
 {let c=app.db.lock().unwrap();c.execute_batch("INSERT INTO roots(id,path,label) VALUES('root','generated','Generated');INSERT INTO works(id,title,original_title) VALUES('w','Primary','Primary');INSERT INTO files(id,root_id,path,relative_path,size,mtime,ext,seen_job,availability) VALUES('f','root','f','f',7,'','bin','','unverified');").unwrap();for i in 0..61{let id=format!("r{i:03}");c.execute("INSERT INTO resources(id,root_id,relative_path,title,kind,work_id) VALUES(?1,'root',?1,?1,'folder','w')",[&id]).unwrap();c.execute("INSERT INTO resource_files VALUES(?1,'f')",[&id]).unwrap();c.execute("INSERT INTO resource_bindings(resource_id,work_id,role) VALUES(?1,'w','main')",[&id]).unwrap();}}
 let listener=tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();let base=format!("http://{}",listener.local_addr().unwrap());let run=app.clone();let server=tokio::spawn(async move{axum::serve(listener,crate::router(run)).await.unwrap()});let client=reqwest::Client::builder().no_proxy().build().unwrap();let url=format!("{base}/api/resources/page");
 assert_eq!(client.get(&url).send().await.unwrap().status(),401);assert_eq!(client.get(&url).bearer_auth("invalid").send().await.unwrap().status(),401);
 let response=client.get(&url).bearer_auth(&app.token).send().await.unwrap().error_for_status().unwrap();assert_eq!(response.headers()["cache-control"],"no-store");let first:Value=response.json().await.unwrap();assert_eq!(first["items"].as_array().unwrap().len(),60);assert_eq!(first["total"],61);assert_eq!(first["items"][0]["primary_work_title"],"Primary");assert_eq!(first["items"][0]["unverified"],1);assert_eq!(first["items"][0]["bindings"][0]["role"],"main");let cursor=first["next"].as_str().unwrap();
 let second:Value=client.get(&url).query(&[("before",cursor)]).bearer_auth(&app.token).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();assert_eq!(second["items"].as_array().unwrap().len(),1);assert_eq!(second["items"][0]["id"],"r060");assert!(second["next"].is_null());
 let legacy:Value=client.get(format!("{base}/api/resources")).bearer_auth(&app.token).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();assert_eq!(legacy.as_array().unwrap().len(),61);assert_eq!(first["items"][0],legacy[0]);
 let login=client.post(format!("{base}/api/access/login")).header("Origin",&base).json(&json!({"password":"Generated resource test passphrase","name":"Generated readonly"})).send().await.unwrap().error_for_status().unwrap();let cookie=login.headers()["set-cookie"].to_str().unwrap().split(';').next().unwrap().to_owned();let web:Value=client.get(&url).header("Cookie",&cookie).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();assert_eq!(web,first);
 assert_eq!(client.post(format!("{base}/api/resources/r000/references")).header("Origin",&base).header("Cookie",&cookie).json(&json!({})).send().await.unwrap().status(),403);
 assert_eq!(client.get(&url).query(&[("before",cursor),("status","unmatched")]).bearer_auth(&app.token).send().await.unwrap().status(),400);
 app.db.lock().unwrap().execute("UPDATE files SET availability='missing' WHERE id='f'",[]).unwrap();assert_eq!(client.get(&url).query(&[("before",cursor)]).bearer_auth(&app.token).send().await.unwrap().status(),400);let fresh:Value=client.get(&url).bearer_auth(&app.token).send().await.unwrap().error_for_status().unwrap().json().await.unwrap();assert_eq!(fresh["items"][0]["missing"],1);assert_eq!(fresh["items"][0]["unverified"],0);
 server.abort();let _=server.await;
}}

#[cfg(test)]mod scale_tests{use super::*;
#[test]#[ignore="Generated100k query benchmark; run explicitly"]fn generated_large_resource_reads(){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let mut c=db.lock().unwrap();{let tx=c.transaction().unwrap();tx.execute_batch("INSERT INTO roots(id,path,label) VALUES('root','generated','Generated');INSERT INTO works(id,title,original_title) VALUES('w','Work','Work');INSERT INTO files(id,root_id,path,relative_path,size,mtime,ext,seen_job,availability) VALUES('f','root','generated','generated',7,'','bin','','missing');").unwrap();for i in 0..100000{let id=format!("r{i:06}");tx.execute("INSERT INTO resources(id,root_id,relative_path,title,kind,work_id) VALUES(?1,'root',?1,?1,'folder',?2)",params![id,if i%2==0{Some("w")}else{None}]).unwrap();tx.execute("INSERT INTO resource_files VALUES(?1,'f')",[&id]).unwrap();tx.execute("INSERT INTO resource_bindings(resource_id,work_id,role) VALUES(?1,'w','patch')",[&id]).unwrap();}tx.commit().unwrap();}
 c.execute_batch("DROP INDEX resource_title_order;").unwrap();let first=page(&c,&Options::default()).ok().unwrap();let mut report=Vec::new();for indexed in [false,true]{if indexed{migrate(&c).unwrap();}for offset in [0,49980,99960]{let q=Options{before:Some(serde_json::to_string(&Cursor{library:first["library_id"].as_str().unwrap().into(),revision:first["revision"].as_i64().unwrap(),query:String::new(),status:String::new(),root_id:String::new(),exclude_id:String::new(),offset}).unwrap()),..Default::default()};let start=std::time::Instant::now();let result=page(&c,&q).ok().unwrap();let ms=start.elapsed().as_secs_f64()*1000.;assert_eq!(result["total"],100000);let items=result["items"].as_array().unwrap();assert_eq!(items.len(),if offset==99960{40}else{60});for(i,item)in items.iter().enumerate(){assert_eq!(item["id"],format!("r{:06}",offset+i as i64));assert_eq!(item["bytes"],7);assert_eq!(item["missing"],1);assert_eq!(item["bindings"][0]["work_id"],"w");}report.push(json!({"candidate_index":indexed,"offset":offset,"ms":ms}));}}
 println!("RESOURCE_SCALE {}",json!({"passed":true,"generated_resources":100000,"generated_bindings":100000,"shared_file_rows":1,"scope":"in-process debug SQL projection,not installed/HTTP/real-files/p95","samples":report}));
}}

#[cfg(test)]mod index_tests{use super::*;
#[test]fn resource_index_upgrade_preserves_projection_and_cursor(){
 let t=tempfile::tempdir().unwrap();let path=t.path().join("library.sqlite");let db=crate::db::open(&path).unwrap();let before;
 {let c=db.lock().unwrap();c.execute_batch("DROP INDEX resource_title_order; INSERT INTO roots(id,path,label) VALUES('root','generated','Generated'); INSERT INTO files(id,root_id,path,relative_path,size,mtime,ext,seen_job,availability) VALUES('f','root','f','f',7,'','bin','','unverified');").unwrap();
 for i in (0..65).rev(){let id=format!("r{i:03}");c.execute("INSERT INTO resources(id,root_id,relative_path,title,kind) VALUES(?1,'root',?1,'Same title','folder')",[&id]).unwrap();c.execute("INSERT INTO resource_files VALUES(?1,'f')",[&id]).unwrap();}
 before=page(&c,&Options::default()).ok().unwrap();}
 drop(db);
 for _ in 0..2{let upgraded=crate::db::open(&path).unwrap();let c=upgraded.lock().unwrap();assert_eq!(page(&c,&Options::default()).ok().unwrap(),before);let tail=page(&c,&Options{before:Some(before["next"].as_str().unwrap().into()),..Default::default()}).ok().unwrap();assert_eq!(tail["items"].as_array().unwrap().len(),5);assert_eq!(tail["items"][0]["id"],"r060");let columns=c.prepare("PRAGMA index_info(resource_title_order)").unwrap().query_map([],|r|r.get::<_,String>(2)).unwrap().collect::<rusqlite::Result<Vec<_>>>().unwrap();assert_eq!(columns,vec!["title","id"]);assert_eq!(c.query_row("PRAGMA integrity_check",[],|r|r.get::<_,String>(0)).unwrap(),"ok");}
}
}

#[cfg(test)]mod destination_tests{use super::*;
#[test]fn destination_scope_pages_only_same_root_and_rejects_changed_cursor(){
 let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("db")).unwrap();let c=db.lock().unwrap();
 c.execute_batch("INSERT INTO roots(id,path,label) VALUES('a','a','A'),('b','b','B'); INSERT INTO files(id,root_id,path,relative_path,size,mtime,ext,seen_job,availability) VALUES('f','a','f','f',1,'','bin','','present');").unwrap();
 for root in ["a","b"]{for i in 0..65{let id=format!("{root}{i:03}");c.execute("INSERT INTO resources(id,root_id,relative_path,title,kind) VALUES(?1,?2,?1,?1,'folder')",params![id,root]).unwrap();c.execute("INSERT INTO resource_files VALUES(?1,'f')",[id]).unwrap();}}
 let mut q=Options{root_id:"a".into(),exclude_id:"a000".into(),..Default::default()};let first=page(&c,&q).ok().unwrap();assert_eq!(first["total"],64);assert_eq!(first["items"].as_array().unwrap().len(),60);assert_eq!(first["items"][0]["id"],"a001");
 q.before=Some(first["next"].as_str().unwrap().to_owned());let second=page(&c,&q).ok().unwrap();assert_eq!(second["items"].as_array().unwrap().len(),4);assert_eq!(second["items"][3]["id"],"a064");assert!(second["next"].is_null());
 q.root_id="b".into();assert!(page(&c,&q).is_err());q.root_id="a".into();q.exclude_id="a001".into();assert!(page(&c,&q).is_err());
 q.before=None;q.query="a064".into();assert_eq!(page(&c,&q).ok().unwrap()["total"],1);q.root_id="unknown".into();assert_eq!(page(&c,&q).ok().unwrap()["total"],0);
}}
