//! Persist observed watcher gaps and scan failures, including sources with no resources.
use rusqlite::{Connection,params,OptionalExtension};
use serde_json::json;
pub fn reconcile(c:&Connection)->rusqlite::Result<()>{
 let mut roots=c.prepare("SELECT rt.id,rt.path,w.revision,w.exclude,w.needs_scan,w.gap_after,w.message FROM roots rt JOIN source_watch w ON w.root_id=rt.id")?;
 let rows=roots.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?,r.get::<_,bool>(4)?,r.get::<_,i64>(5)?,r.get::<_,String>(6)?)))?.collect::<rusqlite::Result<Vec<_>>>()?;
 for(root,path,revision,exclude,gap,after,message)in rows{
  // Active retry jobs never erase a previous failure. Only terminal evidence changes it.
  let last:Option<(String,String,i64,String)>=c.query_row("SELECT j.id,j.state,j.errors,j.message FROM jobs j WHERE j.kind='scan' AND json_extract(j.spec,'$.root_id')=?1 AND (j.state IN ('failed','interrupted','cancelled') OR (j.state='completed' AND j.errors>0)) AND NOT EXISTS(SELECT 1 FROM jobs newer WHERE newer.rowid>j.rowid AND newer.kind='scan' AND newer.state='completed' AND newer.errors=0 AND json_extract(newer.spec,'$.root_id')=?1 AND coalesce(json_extract(newer.spec,'$.exclude'),'[]')=coalesce(json_extract(j.spec,'$.exclude'),'[]') AND ((coalesce(json_extract(newer.spec,'$.scope'),'')='' AND coalesce(json_extract(newer.spec,'$.recursive'),1)=1) OR (coalesce(json_extract(newer.spec,'$.scope'),'')=coalesce(json_extract(j.spec,'$.scope'),'') AND coalesce(json_extract(newer.spec,'$.recursive'),1)>=coalesce(json_extract(j.spec,'$.recursive'),1)))) ORDER BY j.rowid DESC LIMIT 1",[&root],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?))).optional()?;
  let failure=last.as_ref().filter(|(_,state,errors,_)|state!="completed"||*errors>0);
  let observed=if let Some((job,state,errors,error))=failure{let kind=if state=="failed"{"scan_failed"}else if state=="completed"{"scan_partial"}else{"scan_interrupted"};Some((kind,format!("Scan {state}: {error}"),json!([path,revision,exclude,job,state,errors,error])))}else if gap{Some(("unscanned",if message.is_empty(){"This source needs a complete scan before its contents are verified.".into()}else{message.clone()},json!([path,revision,exclude,after,message])))}else{None};
  if let Some((kind,reason,evidence))=observed{
   c.execute("INSERT INTO issues(root_id,category,kind,reason,evidence_key,created,updated) VALUES(?1,'source',?2,?3,?4,?5,?5) ON CONFLICT(root_id,category) DO UPDATE SET kind=excluded.kind,reason=excluded.reason,evidence_key=excluded.evidence_key,state='open',revision=issues.revision+1,updated=excluded.updated WHERE issues.evidence_key!=excluded.evidence_key OR issues.state='resolved'",params![root,kind,reason,evidence.to_string(),crate::db::now()])?;
  }else{c.execute("UPDATE issues SET state='resolved',revision=revision+1,updated=?2 WHERE root_id=?1 AND category='source' AND state!='resolved'",params![root,crate::db::now()])?;}
 }
 c.execute("UPDATE issues SET state='resolved',revision=revision+1,updated=?1 WHERE category='source' AND state!='resolved' AND NOT EXISTS(SELECT 1 FROM roots WHERE id=issues.root_id)",[crate::db::now()])?;Ok(())
}
#[cfg(test)]mod tests{
 use super::*;
 fn fixture()->(tempfile::TempDir,crate::db::Db){let t=tempfile::tempdir().unwrap();let source=t.path().join("empty-source");std::fs::create_dir(&source).unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();{let c=db.lock().unwrap();c.execute("INSERT INTO roots(id,path,label) VALUES('root',?1,'Empty source')",[source.to_str().unwrap()]).unwrap();crate::watching::ensure(&c).unwrap();} (t,db)}
 fn job(c:&Connection,id:&str,state:&str,scope:&str,errors:i64){c.execute("INSERT INTO jobs(id,kind,state,spec,errors,message,created,updated) VALUES(?1,'scan',?2,?3,?4,'Generated observation',1,1)",params![id,state,serde_json::json!({"root_id":"root","scope":scope,"recursive":true,"exclude":[]}).to_string(),errors]).unwrap();}
 #[test]fn empty_source_issue_preserves_deferral_and_backup_and_can_queue_scan(){let(t,db)=fixture();{let mut c=db.lock().unwrap();let tx=c.transaction().unwrap();crate::issues::reconcile(&tx).unwrap();assert_eq!(tx.query_row("SELECT kind FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"unscanned");crate::issues::change(&tx,1,1,"deferred").unwrap();crate::issues::reconcile(&tx).unwrap();assert_eq!(tx.query_row("SELECT state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"deferred");tx.commit().unwrap();}
 let backup=crate::backup::export(&db,t.path()).unwrap();let dest=crate::backup::restore_new(&backup,&t.path().join("restored"),None).unwrap();let restored=crate::db::open(&dest.join("library.sqlite")).unwrap();assert_eq!(restored.lock().unwrap().query_row("SELECT root_id||':'||state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"root:deferred");let mut c=db.lock().unwrap();let tx=c.transaction().unwrap();let p=crate::issue_scan::inspect(&tx,1,2).unwrap();let serialized=serde_json::to_value(p).unwrap();assert!(crate::issue_scan::enqueue(&tx,1,2,serialized["digest"].as_str().unwrap()).unwrap().1);tx.commit().unwrap();}
 #[test]fn unrelated_success_does_not_erase_failure_but_covering_success_does(){let(_t,db)=fixture();let c=db.lock().unwrap();c.execute("UPDATE source_watch SET needs_scan=0",[]).unwrap();job(&c,"failed-a","failed","a",1);reconcile(&c).unwrap();crate::issues::change(&c,1,1,"deferred").unwrap();job(&c,"success-b","completed","b",0);reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT kind||':'||state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"scan_failed:deferred");job(&c,"partial-a","completed","a",2);reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT kind||':'||state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"scan_partial:open");job(&c,"success-all","completed","",0);reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"resolved");}
 #[test]fn interrupted_reopens_and_removed_source_resolves(){let(_t,db)=fixture();let c=db.lock().unwrap();reconcile(&c).unwrap();crate::issues::change(&c,1,1,"deferred").unwrap();job(&c,"interrupted","interrupted","",0);reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT kind||':'||state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"scan_interrupted:open");c.execute("DELETE FROM source_watch",[]).unwrap();c.execute("DELETE FROM roots",[]).unwrap();reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"resolved");}
 #[test]fn schema_fifteen_migration_preserves_issue_identity(){let(t,db)=fixture();{let c=db.lock().unwrap();c.execute_batch("DROP TABLE issues; CREATE TABLE issues(seq INTEGER PRIMARY KEY AUTOINCREMENT,resource_id TEXT NOT NULL,category TEXT NOT NULL,kind TEXT NOT NULL,state TEXT NOT NULL,reason TEXT NOT NULL,evidence_key TEXT NOT NULL,revision INTEGER NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL,UNIQUE(resource_id,category)); INSERT INTO issues VALUES(42,'r','matching','unmatched','deferred','reason','evidence',7,1,2); PRAGMA user_version=15;").unwrap();}drop(db);let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let c=db.lock().unwrap();assert_eq!(c.query_row("SELECT seq||':'||revision||':'||state FROM issues",[],|r|r.get::<_,String>(0)).unwrap(),"42:7:deferred");reconcile(&c).unwrap();assert_eq!(c.query_row("SELECT count(*) FROM issues",[],|r|r.get::<_,i64>(0)).unwrap(),2);assert!(std::fs::read_dir(t.path().join("migration-backups")).unwrap().next().is_some());}
}

