use rusqlite::{Connection,params};
use serde_json::{Value,json};
use axum::{extract::{State,Query},http::HeaderMap,Json};
#[derive(serde::Deserialize)]pub struct Page{before:Option<i64>}
pub fn page(c:&Connection,before:Option<i64>)->Result<Value,String>{
 if before.is_some_and(|x|x<=0){return Err("Invalid timeline cursor".into());}
 let mut q=c.prepare("SELECT seq,job_id,code,payload,created FROM events WHERE seq<?1 AND code IN ('manual.bind','manual.references','job.control','issue.triage','match.attempt','match.completed','file.audit.enabled','file.plan.created','file.plan.state','file.operation.recorded','file.operation.state','file.transfer.created','file.transfer.state') ORDER BY seq DESC LIMIT 51").map_err(|e|e.to_string())?;
 let rows=q.query_map([before.unwrap_or(i64::MAX)],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?,r.get::<_,i64>(4)?))).map_err(|e|e.to_string())?.collect::<rusqlite::Result<Vec<_>>>().map_err(|e|e.to_string())?;
 let more=rows.len()>50;let mut items=Vec::new();for(seq,job,code,raw,created)in rows.into_iter().take(50){let p:Value=serde_json::from_str(&raw).unwrap_or_default();let mut details=serde_json::Map::new();for key in ["resource_id","work_id","from","to","state","action","issue_id","revision","matched","review","plan_id","operation_id","kind","files","failed","undo_of","processed","bytes","existing_plans","existing_transfers"]{if let Some(v)=p.get(key){if v.is_null()||v.is_boolean()||v.is_number(){details.insert(key.into(),v.clone());}else if let Some(s)=v.as_str(){details.insert(key.into(),json!(s.chars().take(300).collect::<String>()));}}}items.push(json!({"seq":seq,"job_id":job,"code":code,"created":created,"details":details}));}
 let next=if more{items.last().map(|x|x["seq"].clone()).unwrap_or(Value::Null)}else{Value::Null};Ok(json!({"items":items,"next":next}))
}
pub async fn list(State(a):State<crate::App>,h:HeaderMap,Query(p):Query<Page>)->crate::Result<Value>{if crate::access::authenticate(&a,&h)?.role=="web"{return Err(crate::ApiError("Desktop access required".into()));}let c=a.db.lock().map_err(|e|crate::ApiError(e.to_string()))?;Ok(Json(page(&c,p.before)?))}
pub fn manual(c:&Connection,rid:&str,code:&str)->Result<(),String>{let(before,after):(String,String)=c.query_row("SELECT before_json,after_json FROM resource_history WHERE resource_id=?1 ORDER BY rowid DESC LIMIT 1",[rid],|r|Ok((r.get(0)?,r.get(1)?))).map_err(|e|e.to_string())?;let before:Value=serde_json::from_str(&before).map_err(|e|e.to_string())?;let after:Value=serde_json::from_str(&after).map_err(|e|e.to_string())?;crate::db::event(c,"",code,&json!({"resource_id":rid,"from":before["primary_work_id"],"to":after["primary_work_id"]})).map_err(|e|e.to_string())}
pub fn control(c:&Connection,jid:&str,action:&str)->Result<(),String>{
 let st:String=c.query_row("SELECT state FROM jobs WHERE id=?1",[jid],|r|r.get(0)).map_err(|e|e.to_string())?;let next=match(action,st.as_str()){("pause","running")=>"pausing",("cancel","running")=>"cancelling",("cancel","queued"|"paused"|"interrupted")=>"cancelled",("resume","paused"|"interrupted"|"cancelled"|"failed")=>"queued",_=>return Err("Action not available for this job state".into())};if next=="queued"{crate::roots::require_idle(c)?;c.execute("UPDATE frontier SET state='pending' WHERE job_id=?1 AND state IN ('running','error')",[jid]).map_err(|e|e.to_string())?;}c.execute("UPDATE jobs SET state=?2,updated=?3 WHERE id=?1",params![jid,next,crate::db::now()]).map_err(|e|e.to_string())?;crate::db::event(c,jid,"job.control",&json!({"action":action,"from":st,"to":next})).map_err(|e|e.to_string())
}
#[cfg(test)]mod tests{
 use super::*;
 #[test]fn paging_is_exclusive_and_projection_excludes_raw_evidence(){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();{let c=db.lock().unwrap();for _ in 0..55{crate::db::event(&c,"job","match.attempt",&json!({"state":"review","password":"synthetic","evidence":{"secret":"synthetic"}})).unwrap();}crate::db::event(&c,"job","not-public",&json!({"password":"synthetic"})).unwrap();let first=page(&c,None).unwrap();assert_eq!(first["items"].as_array().unwrap().len(),50);assert!(!first.to_string().contains("synthetic"));crate::db::event(&c,"job","match.completed",&json!({"matched":1})).unwrap();let second=page(&c,first["next"].as_i64()).unwrap();assert_eq!(second["items"].as_array().unwrap().len(),5);assert!(second["next"].is_null());assert!(page(&c,Some(0)).is_err());}let backup=crate::backup::export(&db,t.path()).unwrap();let restored=crate::backup::restore_new(&backup,&t.path().join("restored"),None).unwrap();let copy=crate::db::open(&restored.join("library.sqlite")).unwrap();assert_eq!(page(&db.lock().unwrap(),None).unwrap(),page(&copy.lock().unwrap(),None).unwrap());}
 #[test]fn manual_bind_records_before_after_and_event_failure_rolls_back(){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();db.lock().unwrap().execute_batch("INSERT INTO roots(id,path,label) VALUES('root','generated','Source'); INSERT INTO resources(id,root_id,relative_path,title,kind) VALUES('r','root','a','Alpha','archive'); INSERT INTO works(id,title,original_title) VALUES('w','Alpha','Alpha');").unwrap();crate::editions::bind_primary(&db,"r","w","Edition",1).unwrap();{let c=db.lock().unwrap();let entry=page(&c,None).unwrap();assert_eq!(entry["items"][0]["code"],"manual.bind");assert_eq!(entry["items"][0]["details"]["to"],"w");assert!(entry["items"][0]["details"]["from"].is_null());c.execute_batch("CREATE TRIGGER reject_event BEFORE INSERT ON events BEGIN SELECT RAISE(ABORT,'generated'); END;").unwrap();}assert!(crate::editions::set_bindings(&db,"r",crate::editions::EditBindings{revision:2,primary_work_id:None,bindings:vec![]}).is_err());assert_eq!(db.lock().unwrap().query_row("SELECT work_id FROM resources WHERE id='r'",[],|r|r.get::<_,String>(0)).unwrap(),"w");}
 #[test]fn control_and_audit_commit_together_and_never_record_passwords(){let t=tempfile::tempdir().unwrap();let db=crate::db::open(&t.path().join("library.sqlite")).unwrap();let mut c=db.lock().unwrap();c.execute("INSERT INTO jobs(id,kind,state,spec,created,updated) VALUES('j','scan','running','{}',1,1)",[]).unwrap();{let tx=c.transaction().unwrap();control(&tx,"j","pause").unwrap();tx.commit().unwrap();}assert_eq!(page(&c,None).unwrap()["items"][0]["details"]["to"],"pausing");c.execute_batch("UPDATE jobs SET state='paused'; CREATE TRIGGER reject_event BEFORE INSERT ON events BEGIN SELECT RAISE(ABORT,'generated'); END;").unwrap();{let tx=c.transaction().unwrap();assert!(control(&tx,"j","resume").is_err());}assert_eq!(c.query_row("SELECT state FROM jobs",[],|r|r.get::<_,String>(0)).unwrap(),"paused");}
}
